### ISSUE TITLE
Calculating sum is 10x slower using Statistics

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5067] opened 2023-02-05 22:45 UTC
This task is automatically imported from the old Task Issue Board and it was originally created by Hubert Plociniczak.
Original issue is [here](https://www.pivotaltracker.com/story/show/184351393).
<hr />

Benchmark https://github.com/enso-org/enso/blob/b9dbfd036f2a75e4207b41c3c7a948080ae41abe/test/Benchmarks/src/Vector/Operations.enso#L31 that calculates a sum of a vector is ~10x slower using Statistics (`.compute Statistic Sum`):

```
Sum/iteration:0: 1480.30ms
Sum/iteration:1: 1353.60ms
Sum/iteration:2: 1331.98ms
Sum/iteration:3: 1420.34ms
Sum/iteration:4: 1743.83ms
Sum/iteration:5: 1626.28ms
```
vs 
```
Sum/iteration:0: 101.13ms
Sum/iteration:1: 91.51ms
Sum/iteration:2: 89.40ms
Sum/iteration:3: 87.61ms
Sum/iteration:4: 85.68ms
Sum/iteration:5: 86.97ms
Sum/iteration:6: 98.91ms
Sum/iteration:7: 88.92ms
Sum/iteration:8: 88.73ms
Sum/iteration:9: 91.20ms
```
with `fold`.

## Blockers:
[#184203977](https://www.pivotaltracker.com/story/show/#184203977) blocked

**Comment by JaroslavTulach** [comment] 2023-06-13 16:30
Please give me exact steps to reproduce. I am trying to keep only following in `test/Benchmarks/src/Vector/Operations.enso`:
```haskell
from Standard.Base import all
import Standard.Base.Runtime.State
import Standard.Base

from Standard.Test import Bench

import project.Vector.Utils

polyglot java import java.util.Random

## Bench Utilities ============================================================

vector_size = 10000
iter_size = 100
num_iterations = 10

# The Benchmarks ==============================================================

bench =
    random_vec = Utils.make_random_vec vector_size

    Bench.measure (random_vec.reduce (+)) "Sum by reduce" iter_size num_iterations
    Bench.measure (random_vec.compute Statistic.Sum) "Sum by statistics" iter_size num_iterations

main = bench
```
when I execute:
```bash
sbt:enso> runEngineDistribution --run test/Benchmarks/src/Vector/Operations.enso --in-project test/Benchmarks
Sum by reduce/iteration:0: 10.57ms
Sum by reduce/iteration:1: 7.05ms
...
Sum by reduce/iteration:5: 3.23ms
Sum by reduce/iteration:6: 4.12ms
...
Sum by reduce/iteration:9: 3.25ms
Sum by reduce average: 4.65ms

Sum by statistics/iteration:0: 39.87ms
Sum by statistics/iteration:1: 20.32ms
Sum by statistics/iteration:2: 11.17ms
Sum by statistics/iteration:3: 11.87ms
...
Sum by statistics/iteration:9: 11.74ms
Sum by statistics average: 17.52ms
```
I can see that `reduce (+)` seems to be 3-5x faster than `Statistic.Sum`. Is that what am I supposed to investigate? Why `reduce (+)` is faster than `Statistics.Sum`? If not, please provide steps I can follow to reproduce.

**Comment by JaroslavTulach** [comment] 2023-06-17 03:23
I performed [an evaluation](https://github.com/enso-org/enso/issues/5067#issuecomment-1589651037) and asked what exactly am I supposed to measure/see/fix? I need a reply.

> Benchmark [enso/test/Benchmarks/src/Vector/Operations.enso](https://github.com/enso-org/enso/blob/b9dbfd036f2a75e4207b41c3c7a948080ae41abe/test/Benchmarks/src/Vector/Operations.enso#L31)
that calculates a sum of a vector is ~10x slower using Statistics (.compute Statistic Sum).

What am I supposed to speed up? Enso code of `reduce (+)` or some other (Java) code like `org.enso.base.statistics.CountMinMax`?

I need some guidance. Meanwhile closing this issue as unclear.

**Comment by wdanilo** [comment] 2023-06-18 23:25
@JaroslavTulach do not close the issue. Instead tag it as more info needed.

**Comment by jdunkerley** [comment] 2023-06-19 06:04
Have taken this ticket over as discussed on Friday.

**Comment by JaroslavTulach** [comment] 2023-06-20 09:10
Tasks:
- speed `Statistics` version up
- general advice how to implement such "aggregating"> computations.

**Comment by JaroslavTulach** [comment] 2023-07-10 06:14
The infrastructure for running, measuring and analyzing these benchmarks is [ready](https://github.com/enso-org/enso/pull/7101#discussion_r1257504440). Time to use it to write the right benchmarks.

**Comment by jdunkerley** [comment] 2023-07-10 07:00
So should I take this over until such time as we have benchmarks in the new form?

**Comment by JaroslavTulach** [comment] 2023-07-10 17:46
With https://github.com/enso-org/enso/pull/7101/commits/15843572be9d49c3b46652c48f60650f72b6d011 I see:
```
sbt:runtime> benchOnly VectorOperations.sum
# Benchmark: org.enso.interpreter.bench.benchmarks.meso.VectorOperations.sumStatistic
Iteration: 507.705 ms/op
# Benchmark: org.enso.interpreter.bench.benchmarks.meso.VectorOperations.sum
Iteration: 1.194 ms/op
```
that's **five hundred times** slower for the Java implementation. Wow. I'll continue investigating.

**Comment by JaroslavTulach** [comment] 2023-07-11 07:26
I attribute the slowdown to enormous amount of _across the boundary calls_ from Enso to Java. There is `Moments.add` which seems to be called quite a lot and my hypothesis is that _crossing the boundary_ so frequently is slowing us down. I tried to replace Java with Espresso (then there would be no boundary), but the experiment just revealed [limitations of Espresso](https://graalvm.slack.com/archives/CPSD12R71/p1689059958113089?thread_ts=1689059706.285319&cid=CPSD12R71). I need to invent other experiment.

**Closed as completed** 2023-07-26 10:01 UTC
Labels: p-low, --bug, -compiler, -libs

**Comment by JaroslavTulach** [comment] 2023-08-09 09:39
I finally got a bit of time and also got the idea to use [VisualVM polyglot profiler] here are the [latest findings](https://github.com/enso-org/enso/pull/7390#issuecomment-1670726207).
