### ISSUE TITLE
Node code replaced by input from last port

### ISSUE THREAD

**Issue by xvcgreg** [enso-org/enso#6631] opened 2023-05-10 11:42 UTC
### What type of issue is this?

Intermittent – Occurring irregularly

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [X] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

I have updated API key (string in one of the nodes) then ``ctrl+clicked`` on ``get`` node just to make sure it's computing the update (I had no visual indication of the node being processed (greying out)) - but when I have pressed ``ctrl+enter`` the code of the node was replaced by the last input port that ``get`` node was receiving:

https://github.com/enso-org/enso/assets/108271897/2ebf167c-cd2f-48de-986b-48eb78c894f3

### Expected behaviour

``ctrl+enter`` on node without any changes leaves the code unchanged

### How we can reproduce it?

as in the attached video above

### Enso Version

2023.5.9 nightly

### Browser or standalone distribution

Standalone distribution

### Browser Version or standalone distribution

standalone

### Operating System

Windows

### Operating System Version

Win11pro 22H2 22621.1555

### Hardware you are using

12th Gen Intel(R) Core(TM) i9-12900HK / RTX3060 Laptop / Nvidia Drivers 531.68

**Comment by Akirathan** [comment] 2023-05-15 11:01
It should have probably been fixed by https://github.com/enso-org/enso/commit/b0ce2a8d298a2639842ba771d2ba64947556af05

**Comment by Akirathan** [comment] 2023-05-15 11:02
Closing this as a duplicate of #6411 which was already fixed

**Closed as completed by Akirathan** 2023-05-15 11:02 UTC
Labels: s-duplicate, --bug, --regression
