### ISSUE TITLE
Adding a single node in the middle of the workflow is desynchronizing IDE and Engine and causing IDE to stop sending the updates without notifying the user

### ISSUE THREAD

**Issue by sylwiabr** [enso-org/enso#6634] opened 2023-05-10 13:31 UTC
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

Adding a single node to the workflow is causing desynchronization between IDE and Engine. This leads to responsive IDE (user continue to work and add nodes) that is not updating the Engine so user can easily loose the work.

### Expected behaviour

1. Information about problems should appear.
2. Adding single node should not break the state of the project.

### How we can reproduce it?

Open the project:
[Unnamed_7.enso-project.zip](https://github.com/enso-org/enso/files/11442081/Unnamed_7.enso-project.zip)
add a node at the beginning of the workflow like on the video

https://github.com/enso-org/enso/assets/12892578/3bd9818f-4f76-4e3d-a756-500dcaab7ef8

see the logs:
![image](https://github.com/enso-org/enso/assets/12892578/e2a30144-e0f5-4098-a407-84113c68e51d)

### Enso Version

develop 10.05

### Browser or standalone distribution

Standalone distribution

### Browser Version or standalone distribution

standalone

### Operating System

Windows

**Comment by farmaazon** [comment] 2023-05-10 14:34
It probably would be amended by implementing #5203 but still it's strange that some text operations takes more than 10 seconds.

**Comment by Akirathan** [comment] 2023-05-11 10:45
I am not able to reproduce this. LanguageServer does not die on my machine. Could you pls also attach logs from the language server so that we can see what exactly happens there?

**Comment by sylwiabr** [comment] 2023-05-11 10:48
Language server here was completely fine. It was just the IDE that was messed up.  @jdunkerley can you upload LS logs from our session yesterday?

**Comment by Akirathan** [comment] 2023-05-11 11:24
> Language server here was completely fine. It was just the IDE that was messed up. @jdunkerley can you upload LS logs from our session yesterday?

Right. So what exactly do you mean by this *desynchronization* and how do you know it happened? Hovering over the bottom corner of node does not display its type? The nodes and the edges are grey? Is there a "Connection to the backend lost" error message (I don't see any, so I suppose its a different scenario)? Can't it be caused by the IDE sending a sequence of updates that the engine is not able to cope with?

**EDIT**: I can see in the dev console log that there is something like:
```
Error during sending text change to Language Server: Peer has replied with an error: Error { code: 3003, message: "Invalid version [client version: ..., version: ...]" data: None}
```

So IDE sent `text/applyEdit` message and waited more than 10 seconds for the response from the language server?

**Comment by sylwiabr** [comment] 2023-05-11 11:58
> So IDE sent text/applyEdit message and waited more than 10 seconds for the response from the language server?

yes, and I judged it because of errors in the console

**Comment by Akirathan** [comment] 2023-05-11 13:28
> yes, and I judged it because of errors in the console

That is weird. I still think this might be a problem with language server. Shouldn't there some progress messages sent back to the IDE if the `test/applyEdit` takes too long? Similar to what we do with, e.g., with `executionContext/expressionUpdates`? cc @4e6

**Comment by hubertp** [comment] 2023-05-11 13:31
> Language server here was completely fine. It was just the IDE that was messed up. @jdunkerley can you upload LS logs from our session yesterday?

Well, the fault is somewhere in the middle. We optimistically assume that edits will finish within a reasonable amount of time, except :hankey: :arrow_right: fan when they don't. Yes, an edit should not take so long, whatever the reason, except it is hard to anticipate every reason, this ticket being one example. Especially if it is system dependent. IMHO there is nothing much that one can do, in the case of a timeout, other than #5203  because future edits/actions will fail. Rightfully so.

**Comment by xvcgreg** [comment] 2023-05-24 12:09
Started new project to record some BCs and this happened again on a fresh 2023.5.24 Nightly install and with a new project:

``3003``

![image](https://github.com/enso-org/enso/assets/108271897/c2844083-2f6e-4059-8ade-67a3f5c378dd)
[new 18.txt](https://github.com/enso-org/enso/files/11554360/new.18.txt)

**Comment by hubertp** [comment] 2023-05-30 10:24
Added a bunch of throttling (network + cpu). Things got really slow, as one would expect, and IDE would keep on closing/opening the file due to timeouts (and https://github.com/enso-org/enso/pull/6752) but eventually things would stabilize and recover on its own. So I would say this is now remedied.

**Closed as completed by hubertp** 2023-05-30 10:24 UTC
Labels: --bug, -language-server

**Comment by hubertp** [comment] 2023-05-30 13:16
This doesn't change the fact that for some reason, making changes to this project can be very, very slow. This should be investigated separately? @sylwiabr

**Comment by sylwiabr** [comment] 2023-05-30 14:14
@hubertp here is the ticket for investigation this project on the IDE side https://github.com/enso-org/enso/issues/6637
