### ISSUE TITLE
Remove unit tests that measure some operation

### ISSUE THREAD

**Issue by Akirathan** [enso-org/enso#8204] opened 2023-11-01 14:40 UTC
Recently I stepped into a failing test [FAILED should perform Is_In efficiently for builtin types](https://github.com/enso-org/enso/actions/runs/6720346443/job/18263703151?pr=8202#step:10:4600) that measures `Is_In` operation and fails if it takes longer than 150 ms. These timing sensitive tests should not be part of our testing suite at all. If performance is important, let's keep it in benchmarks.

**Comment by jdunkerley** [comment] 2023-11-01 14:42
@radeusgd can we adjust this test to be a benchmark rather than a unit test.

**Comment by radeusgd** [comment] 2023-11-02 08:48
> fails if it takes longer than 150 ms

This is not entirely true - it measures performance relative to other operations - so it should work regardless of whether its run on a fast or slow machine. The tests have been there for a long time and were failing very rarely.

I think the benefit of this is that we get some kind of notification in case we regress on stuff like this. With benchmarks we don't have any kind of checking/notification, so unless we are tracking them regularly, we can very easily not notice such regressions - and since benchmarks are run only on already merged PRs we'd notice them after the regression is introduced anyway.

But I guess what is fair is that we have these tests for just a few cases and the performance of these operations is not really special in any way compared to all other operations.

Maybe we should try to send us a notification if a new benchmark run is slower by some threshold than the previous run? If we can keep track of this (without too many false positives), tests like this won't be needed indeed.

**Closed as completed** 2023-11-08 12:59 UTC
Labels: -libs
