### ISSUE TITLE
Selector in Component Browser resets it's position

### ISSUE THREAD

**Issue by xvcgreg** [enso-org/enso#6289] opened 2023-04-14 17:15 UTC
### What type of issue is this?

Permanent – Ocurring repeatably

### Is this issue blocking you from using Enso?

- [X] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [X] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

After opening CB and starting to type a function name when you navigate with arrows through the components selector resets it's position back to the middle bottom default one.

### Expected behaviour

Navigating through components with arrows make selector stay in chosen place.

### How we can reproduce it?

open CB
start typing (i.e.: "to")
navigate with arrows (i.e. to "to_vector" component)

watch how selector jumps back in to its default starting position

### Screenshots or screencasts

https://user-images.githubusercontent.com/108271897/232112528-ed1d46db-7391-455a-9963-82e64f29bab4.mp4

### Enso Version

2023.04.13

### Browser or standalone distribution

Standalone distribution

### Browser Version or standalone distribution

standalone

### Operating System

Windows

### Operating System Version

11pro 22H2

### Hardware you are using

12th Gen Intel(R) Core(TM) i9-12900HK / RTX3060 Laptop

**Comment by vitvakatu** [comment] 2023-04-15 10:30
This is a duplicate of #4966

**Comment by farmaazon** [comment] 2023-04-17 07:49
More precisely, this is duplicate of https://github.com/enso-org/enso/issues/6124

**Closed as not planned by farmaazon** 2023-04-17 07:49 UTC
Labels: s-duplicate, --bug, --regression
