### ISSUE TITLE
Opening searcher takes ages and finally ends up with an error breaking the whole project.

### ISSUE THREAD

**Issue by PabloBuchu** [enso-org/enso#7095] opened 2023-06-21 11:46 UTC
I am working on current develop to debug some issues. When I opened a local project and pressed `tab` to open a searcher it took quite a long time (2-3 seconds). When finally opened it ended up throwing bunch of errors. Project was corrupted in the end. When I went back to dashboard and closed the project I've got `Leaked object` error with huge stacktrace.

https://github.com/enso-org/enso/assets/2855109/874caa1c-3b5a-49a4-9dd8-fd1f8060de70

[error.log](https://github.com/enso-org/enso/files/11817140/error.log)

I am using MacOS Ventura

**Comment by hubertp** [comment] 2023-06-21 12:34
Looks like two separate problems. Can't really comment about the crash in the console except that it shouldn't happen.
Any chance you could get detailed logs for those `EnsureCompilerJob` error reported by backend?

**Comment by PabloBuchu** [comment] 2023-06-21 12:42
how to get that?

**Comment by MichaelMauderer** [comment] 2023-06-21 13:10
The big IDE error is not actually a crash, but is caused by leaked objects that are detected after the project was closed. But should definitely be investigated, as this may be caused by a previous error that leaves the IDE in a bad state.

 Unfortunately, I cannot seem to reproduce it.

**Comment by MichaelMauderer** [comment] 2023-06-22 10:47
> how to get that?

@hubertp

**Comment by hubertp** [comment] 2023-06-26 12:23
I always run project manager in verbose mode (`-vv`) don't know how to pass it to IDE (or cloud).

**Comment by wdanilo** [comment] 2023-06-26 12:30
I understand that this happens right now only on @PabloBuchu computer, right? This is a serious issue and we need to debug it. CC @xvcgreg just to track it. I'm not sure though how to debug it in the most efficient way. I'm just telling that this needs to be fixed, as if it happens on one computer, it will probably happen on others as well in the future.

**Comment by xvcgreg** [comment] 2023-06-26 12:40
I'm tracking it, thanks @wdanilo.
@MichaelMauderer please schedule a call with @PabloBuchu to investigate it together as soon as possible.

**Comment by MichaelMauderer** [comment] 2023-06-26 15:16
> I'm tracking it, thanks @wdanilo. @MichaelMauderer please schedule a call with @PabloBuchu to investigate it together as soon as possible.

We are on it.

**Comment by xvcgreg** [comment] 2023-07-04 15:37
@MichaelMauderer do we know where is the issue and what caused it?

**Comment by MichaelMauderer** [comment] 2023-07-06 12:44
> @MichaelMauderer do we know where is the issue and what caused it?

So far, we don't know. I was unable to reproduce the issue. I'm still in contact with @PabloBuchu.

**Comment by PabloBuchu** [comment] 2023-07-07 08:26
Having some weird errors when running `./run wasm test`

```
 Running unittests src/lib.rs (/Users/pawelbuchowski/projects/enso/target/rust/wasm32-unknown-unknown/debug/deps/enso_gui-62651a075c268908.wasm)
 INFO ide_ci::program::command: wasm-packℹ️ Set timeout to 300 seconds...
Running headless tests in Firefox on `http://127.0.0.1:55139/`.
 INFO ide_ci::program::command: wasm-packℹ️ Try find `webdriver.json` for configure browser's capabilities:
 INFO ide_ci::program::command: wasm-packℹ️ Not found
driver status: signal: 9 (SIGKILL)                g new webdriver session...
 INFO ide_ci::program::command: wasm-packℹ️ driver stdout:
 INFO ide_ci::program::command: wasm-packℹ️     1688654548266	geckodriver	INFO	Listening on 127.0.0.1:55139
 INFO ide_ci::program::command: wasm-packℹ️
 INFO ide_ci::program::command: wasm-pack⚠️ Error: non-200 response code: 500
 INFO ide_ci::program::command: wasm-pack⚠️ {"value":{"error":"session not created","message":"Expected browser binary location, but unable to find binary in default location, no 'moz:firefoxOptions.binary' capability provided, and no binary flag set on the command line","stacktrace":""}}
 INFO ide_ci::program::command: wasm-pack⚠️ error: test failed, to rerun pass `--lib`
 INFO ide_ci::program::command: wasm-pack⚠️
 INFO ide_ci::program::command: wasm-pack⚠️ Caused by:
 INFO ide_ci::program::command: wasm-pack⚠️   process didn't exit successfully: `/Users/pawelbuchowski/Library/Caches/.wasm-pack/wasm-bindgen-3db0f537558d06d8/wasm-bindgen-test-runner /Users/pawelbuchowski/projects/enso/target/rust/wasm32-unknown-unknown/debug/deps/enso_gui-62651a075c268908.wasm` (exit status: 1)
 INFO ide_ci::program::command: wasm-pack⚠️ Error: Running Wasm tests with wasm-bindgen-test failed
 INFO ide_ci::program::command: wasm-pack⚠️ Caused by: failed to execute `cargo test`: exited with exit status: 1
 INFO ide_ci::program::command: wasm-pack⚠️   full command: cd "app/gui" && CARGO_TARGET_WASM32_UNKNOWN_UNKNOWN_RUNNER="/Users/pawelbuchowski/Library/Caches/.wasm-pack/wasm-bindgen-3db0f537558d06d8/wasm-bindgen-test-runner" GECKODRIVER="/Users/pawelbuchowski/Library/Caches/.wasm-pack/geckodriver-1756f56661623bb2/geckodriver" WASM_BINDGEN_TEST_ONLY_WEB="1" "cargo" "test" "--target" "wasm32-unknown-unknown" "--color" "always"
 ```
 
Heard maybe you @vitvakatu could help

**Comment by MichaelMauderer** [comment] 2023-07-07 09:10
It seems there is a problem with the web driver. But as I'm not on Mac, I don't quite know how this is handled there. That is why I think @vitvakatu might be able to know more about this. 

Actually, one follow-up question because of `headless tests in Firefox ...`. Do you have Firefox installed? @PabloBuchu

**Comment by vitvakatu** [comment] 2023-07-07 13:28
Hmm, I don't know what might be causing this. For me, running `./run wasm test` on the latest develop works fine. I have the Firefox installed.

**Comment by PabloBuchu** [comment] 2023-07-11 12:39
Ok so the tests passed green (would be nice to know that a firefox is required to run them;)) but I think my local projects are getting worse or this is a separate bug when you try to close a project that wasn't yet compiled

https://github.com/enso-org/enso/assets/2855109/cac5e0aa-3f5f-4d71-a8c1-ea4f4dabfe43

**Comment by PabloBuchu** [comment] 2023-07-11 12:44
so the above is I guess separate issue. but I saw new console error while opening searcher 

```
[7162:0711/144357.944043:ERROR:CONSOLE(1)] "Uncaught (in promise) TypeError: Failed to fetch", source: devtools://devtools/bundled/panels/elements/elements.js (1)
```

**Comment by vitvakatu** [comment] 2023-07-17 09:37
Ok, I can reproduce this second issue, I created a separate task https://github.com/enso-org/enso/issues/7301

But I am unable to reproduce any issues with the searcher. @PabloBuchu is it still happening to you on the latest develop?

**Comment by 4e6** [comment] 2023-07-20 14:04
Cannot reproduce the issue with the searcher. @PabloBuchu please check if it is still happening for you

**Comment by PabloBuchu** [comment] 2023-07-28 09:39
@4e6  So it looks like the problem at least on my setup is tied with visualization. When I created and opened `Colorado_COVID` template I am getting a lot of errors

https://github.com/enso-org/enso/assets/2855109/2094393d-e395-4cbc-9a78-bf68098e254b

I cleaned everything (node modules, target directories etc) and rebuild the develop with `./run ide build --skip-wasm-opt --wasm-profile=dev --backend-source release --backend-release latest`

not sure what can I do more any ideas?

**Comment by MichaelMauderer** [comment] 2023-07-28 12:55
This now really looks like https://github.com/enso-org/enso/issues/7149.

I can even repo this at the moment when creating a new project! So I think this is a different issue from what happened at the start of this issue. It looks like the `executionContext/attachVisualization` method is gone/broken when running the current develop with the currently nightly engine. 

@hubertp Did something here change recently?

**Comment by hubertp** [comment] 2023-07-28 13:08
> @hubertp Did something here change recently?

Recently, no. But it's likely a mismatch between engine and ide, similar to what is mentioned in https://github.com/enso-org/enso/issues/7149#issuecomment-1611500636 and the likely commit. Trying to figure out why it seems to persist for @PabloBuchu

**Comment by hubertp** [comment] 2023-07-28 13:28
Yeap, confirmed that `./run` wasn't pulling latest engine but an old one `2023.06.20`.

**Comment by MichaelMauderer** [comment] 2023-07-28 13:28
Not just for @PabloBuchu, I can repro this on develop, too. Maybe something has changed about which engine is used?

**Comment by hubertp** [comment] 2023-07-28 13:30
@MichaelMauderer Another thought. What does `edition` field say for the offending project's `package.yaml` file?

**Comment by MichaelMauderer** [comment] 2023-07-28 13:32
```
name: New_Project_5
namespace: local
version: 0.0.1
license: ''
authors: []
maintainers: []
edition: 2023.2.1-nightly.2023.6.20
prefer-local-libraries: true
```

That is a newly created empty project.

**Comment by hubertp** [comment] 2023-07-28 13:33
There you go. `edition: 2023.2.1-nightly.2023.6.20`. I'm guessing @PabloBuchu has the same problem.

**Comment by MichaelMauderer** [comment] 2023-07-28 13:36
The question now is, why that is the default. And why was it working before?

**Comment by PabloBuchu** [comment] 2023-07-28 13:36
Yes indeed.. All my newly created projects have edition set to `2023.2.1-nightly.2023.6.20`.. How was I the only one getting such problems and how it looks like on other systems?

**Comment by hubertp** [comment] 2023-07-28 13:38
No idea. I will see where/how is that hardcoded.

**Comment by hubertp** [comment] 2023-07-28 14:19
![Screenshot from 2023-07-28 16-18-16](https://github.com/enso-org/enso/assets/292128/07e73b80-e7b2-42e0-878b-8f9d72c1a574)
Is marked as "latest"

**Comment by hubertp** [comment] 2023-07-28 15:24
So to me it really sounds like it works as expected.
You execute `run` with latest IDE against an incompatible version of engine (`latest`) which is from 2023/06/20. A friend of mine used to say "latest is not a version" and this proves every single time ;)

So maybe the question is why you can't run `nightly` as backend? @PabloBuchu

**Comment by jdunkerley** [comment] 2023-07-31 08:48
20th June is marked as latest as it was the last version to complete all the manual release tests successfully.

Hopefully we can update to a new latest this week.

**Comment by Akirathan** [comment] 2023-07-31 09:01
Related discussion about versioning of Engine+IDE is at https://github.com/orgs/enso-org/discussions/6762#discussioncomment-6090645

<blockquote><img src="https://opengraph.githubassets.com/43be3224a70bce8e00447fa0058339397a74c8a694d61fadf0b7ab4ad012b9ec/orgs/enso-org/discussions/6762" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/orgs/enso-org/discussions/6762">Language Server API · enso-org · Discussion #6762</a></strong></div><div>When I was discussion with @Frizi the issue #6715, we discovered several points about Language Server API to be discussed broader @4e6 @hubertp : What widgets needs to know The widgets need to know...</div></blockquote>

**Comment by GregoryTravis** [comment] 2023-07-31 12:57
I am getting something similar -- all my new projects are set to 2023.2.1-nightly.2023.5.11.

**Comment by jdunkerley** [comment] 2023-09-11 10:52
Current plan is to use installed engine and libraries and warn the user if they have a different edition number.
This will be revisited with more granular control in future.

**Closed as completed by jdunkerley** 2023-09-11 10:52 UTC
Labels: p-highest, s-research-needed, --bug, -compiler, --regression

**Comment by GregoryTravis** [comment] 2023-09-11 14:56
What is the workaround for now?
