### ISSUE TITLE
Starting editing the node with vector added through vector editor and clicking in the background causing the whole node vanish

### ISSUE THREAD

**Issue by sylwiabr** [enso-org/enso#6419] opened 2023-04-25 13:42 UTC
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

https://user-images.githubusercontent.com/12892578/234295385-7e6e1594-0a8e-43da-9e03-c98ba03aca79.mov

### Expected behaviour

Node should remain unmodified on the scene

### Enso Version

Nightly 25.04.2023 with --feature-preview.vector-editor flag

### Browser or standalone distribution

Standalone distribution

### Browser Version or standalone distribution

standalone

### Operating System

MacOS

**Comment by MichaelMauderer** [comment] 2023-04-26 12:24
I just saw this even worse: it seemed to happen for any node where I start editing and click in the background. It might be related to https://github.com/enso-org/enso/issues/6411

**Comment by vitvakatu** [comment] 2023-04-26 12:37
I think this is a duplicate of #6411, and different effects are caused by different preconditions (the previously edited node is important).

**Comment by MichaelMauderer** [comment] 2023-04-26 13:32
> I think this is a duplicate of #6411, and different effects are caused by different preconditions (the previously edited node is important).

We should double-check this issue after the other has been fixed to maker sure we got all the conditions.

**Comment by farmaazon** [comment] 2023-05-11 10:00
Cannot reproduce it anymore, closing.

**Closed as not planned by farmaazon** 2023-05-11 10:00 UTC
Labels: s-no-repro, p-high, --bug
