### ISSUE TITLE
Suggestions Error on linux

### ISSUE THREAD

**Issue by rmflight** [enso-org/enso#1684] opened 2021-04-14 21:42 UTC
### What did you do?

Start the IDE from the command line, and watched the output in the terminal in Pop!OS 20.04 (Ubuntu 20.04)

### What did you expect to see?

Description of what is going on.

### What did you see instead?

What happens is that an error appears, about finding suggestions:

This is the last [info] message

> [info] [2021-04-14T21:29:24.308Z] [org.enso.languageserver.text.CollaborativeBuffer] Buffer opened for Path(f2644d76-41db-46ad-8a38-0adaf7dfc43a,Vector(src, Main.enso)) [client:51e74f29-88e0-4122-8c90-420b020af59b]

And then it starts on [error] messages

> [error] [2021-04-14T21:30:07.523Z] [org.enso.languageserver.runtime.ContextEventsListener] Unable to find suggestion for (Standard.Base.Data.Number.Extensions,Builtins.Main.Integer,up_to)
> [error] [2021-04-14T21:30:07.524Z] [org.enso.languageserver.runtime.ContextEventsListener] Unable to find suggestion for (Standard.Base.Data.Range,Standard.Base.Data.Range.Range,to_vector)
> [error] [2021-04-14T21:30:07.524Z] [org.enso.languageserver.runtime.ContextEventsListener] Unable to find suggestion for (Standard.Base.Data.Vector,Standard.Base.Data.Vector.Vector,map)

And then this one about dead letters:

> [info] [2021-04-14T21:30:39.284Z] [akka.actor.LocalActorRef] Message [org.enso.languageserver.search.SearchProtocol$CompletionResult] from Actor[akka://language-server/user/suggestions-handler#-1970814948] to Actor[akka://language-server/user/$c/request-handler-Completion-b4439717-f434-440b-aabd-8c64ba4f7f71#-1023448089] was not delivered. [1] dead letters encountered. If this is not an expected behavior then Actor[akka://language-server/user/$c/request-handler-Completion-b4439717-f434-440b-aabd-8c64ba4f7f71#-1023448089] may have terminated unexpectedly. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
^C[internal-logger-error] One of the printers failed to write a message: akka.stream.StreamDetachedException: Stage with GraphStageLogic akka.stream.impl.QueueSource$$anon$1@4e34b89f stopped before async invocation was processed

### Enso Version

enso-linux-2.0.0-alpha.3.AppImage

### Additional notes

On my machine, I've gotten suggestions to work once out of maybe 10 starts. I don't know why. I let the Enso instance sit for 5 minutes, and they still don't appear.

**Comment by 4e6** [comment] 2021-04-23 13:19
Can be caused by #1590

**Comment by iamrecursion** [comment] 2021-05-20 12:43
Please let us know if you encounter this again. We think that this should be fixed in the latest version.

**Closed as completed by iamrecursion** 2021-05-20 12:43 UTC
Labels: p-high
