### ISSUE TITLE
Closing not yet compiled project produces very long stacktrace

### ISSUE THREAD

**Issue by PabloBuchu** [enso-org/enso#7258] opened 2023-07-11 12:56 UTC
1. Create / start new local project
2. Go to workspace
3. Immediately when the go back to dashboard button show up go back to projects list 
4. Hit stop on working project
5. Error occurs

https://github.com/enso-org/enso/assets/2855109/f57472ef-6832-4a5a-8795-7c67cff6ffca

[terminal.error.txt](https://github.com/enso-org/enso/files/12014856/terminal.error.txt)
[console_log.error.txt](https://github.com/enso-org/enso/files/12014857/console_log.error.txt)

**Comment by xvcgreg** [comment] 2023-07-11 12:59
Reproduced on Win11 with Nightly 2023.7.11

![image](https://github.com/enso-org/enso/assets/108271897/e29f78c6-09ef-46fe-ba6f-71e0d46154fc)

verbose log:
[20230711-125025-248-enso-project-manager.log](https://github.com/enso-org/enso/files/12014875/20230711-125025-248-enso-project-manager.log)

**Comment by 4e6** [comment] 2023-07-20 13:04
The error in the video points to `unwrap()` here
https://github.com/enso-org/enso/blob/d8d467f62be1c990ecf180da1ac20228c07916e1/lib/rust/ensogl/core/src/display/world.rs#L409-L416

Maybe it's worth adding some error handling there

**Comment by 4e6** [comment] 2023-07-20 14:00
Duplicate of #7301

**Closed as completed by 4e6** 2023-07-20 14:00 UTC
Labels: p-high, --bug
