### ISSUE TITLE
Speed startup by asynchronous initialization of `ReplIO`

### ISSUE THREAD

**Issue by JaroslavTulach** [enso-org/enso#8690] opened 2024-01-05 12:58 UTC
Investigation of 
- https://github.com/enso-org/enso/issues/8553#issuecomment-1878502004

revealed that another reason for slowing the startup by 16% (while measurements were off) is replacement of `DumbTerminal`:

![obrazek](https://github.com/enso-org/enso/assets/26887752/ce10972a-e257-4937-a8af-74b96ee83bb6)

by proper and more capable

```java
org.jline.terminal.impl.jna.JnaTerminalProvider.sysTerminal()
```

As the terminal isn't going to needed for next 1 or 2 seconds, let's defer its initialization into own (low priority) `Thread`.

**Comment by JaroslavTulach** [comment] 2024-01-05 13:00
By initializing in own thread, we can eliminate `Thread.currentThread().setContextClassLoader(prevClassLoader)` - as the thread will die out after performing initialization.

**Comment by JaroslavTulach** [comment] 2024-01-05 13:01
When at it we could rewrite `ReplIO` (and maybe also `Repl`) into Java.

**Comment by jdunkerley** [comment] 2024-01-09 09:56
Closed as duplicate of #8688

**Closed as not planned by jdunkerley** 2024-01-09 09:56 UTC
Labels: -compiler, --low-performance
