### ISSUE TITLE
Selecting nodes for the first time after project opening is almost always leaving one node unselected

### ISSUE THREAD

**Issue by sylwiabr** [enso-org/enso#6488] opened 2023-05-01 12:32 UTC
### What type of issue is this?

Intermittent – Occurring irregularly

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

https://user-images.githubusercontent.com/12892578/235451942-d80afca8-2963-4e4a-a692-8628b4672819.mov

### Expected behaviour

Nodes in selecting area should be selected

### Enso Version

develop @ 6b0c682b08b7745368cec3474cc774c51a5b48f5

### Browser or standalone distribution

Standalone distribution

### Browser Version or standalone distribution

Standalone

### Operating System

MacOS

**Comment by hubertp** [comment] 2023-05-02 08:23
Isn't this because it does the re-sizing of nodes while it is loading the possible values?

**Comment by vitvakatu** [comment] 2023-05-03 12:09
It's a bit annoying to reproduce, but I had the best chance by following the same actions as in the video: having one node far to the right and selecting from the bottom right to the top left.

It doesn't look to be caused by node positions or size changes – after all, nodes don't move when we add placeholders and widgets. We only increase their width. 

It is worth checking this issue after https://github.com/enso-org/enso/pull/6487, as it might be connected.

**Comment by jdunkerley** [comment] 2023-08-31 09:44
Assumed will be fixed as part of the new IDE work.

**Comment by farmaazon** [comment] 2024-02-27 09:59
Not reproduced in GUI2

**Closed as not planned by farmaazon** 2024-02-27 09:59 UTC
Labels: p-lowest, p-medium, d-unknown, --bug
