### ISSUE TITLE
Noise randomness seems not right

### ISSUE THREAD

**Issue by xvcgreg** [enso-org/enso#5878] opened 2023-03-09 17:53 UTC
### What type of issue is this?

Permanent – Ocurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

When applied noise on vector it seems very regular - too regular for a noise, and each time the same (with new project and it's even consistant with one from demo made over 1y ago).

0..100:
![Screenshot 2023-03-09 181154](https://user-images.githubusercontent.com/108271897/224112996-8d2838b5-78ce-4118-a203-f4a20d062a22.png)

0..1000:
![Screenshot 2023-03-09 181155](https://user-images.githubusercontent.com/108271897/224113057-c4b3c858-134e-4d23-b56b-689c88037e39.png)

### Expected behaviour

Noise to be more random, not consistant when created in different project (different noise seed generated per project?).

### How we can reproduce it?

Scatterplot of a vector of noise

### Enso Version

Build: Nightly Release #842

### Browser or standalone distribution

Standalone distribution

### Browser Version or standalone distribution

standalone

### Operating System

Windows

### Operating System Version

11pro

### Hardware you are using

i9 12th gen / discrete gpu

**Comment by jdunkerley** [comment] 2023-03-28 09:29
Closing as duplicate of #5897

**Closed as not planned by jdunkerley** 2023-03-28 09:29 UTC
Labels: p-low, --bug, -libs
