### ISSUE TITLE
Text displays with extra spaces

### ISSUE THREAD

**Issue by GregoryTravis** [enso-org/enso#7492] opened 2023-08-03 15:45 UTC
### What type of issue is this?

Intermittent – Occurring irregularly

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

I'm testing Text.normalize (https://github.com/enso-org/enso/pull/7425), and in some cases, a normalized text string is displayed with extra spaces. Just to be sure, I checked the length and codepoints of the two strings, and they are identical. I even converted the codepoints back to strings, and those display correctly. It also seems correct when run at the command line.

### Expected behaviour

Expect the text to be displayed without a gap.

### How we can reproduce it?

1. Create a text node
2. Normalize it
3. View the output

### Screenshots or screencasts

The "operator1.normalize" node is displaying the string with a gap:

<img width="1358" alt="Screen Shot 2023-08-03 at 11 35 03 AM" src="https://github.com/enso-org/enso/assets/24406074/69938b9e-9578-4573-aeaa-7119e893ee08">

You can see it full screen here:

<img width="419" alt="Screen Shot 2023-08-03 at 11 33 01 AM" src="https://github.com/enso-org/enso/assets/24406074/5b36667e-1aeb-49c8-8197-12714cab761b">

### Enso Version

Local build at 9e9cf0b2ed608c181654c34c0cd668334384cdcc

### Browser or standalone distribution

Standalone distribution (local project)

### Browser Version or standalone distribution

standalone

### Operating System

MacOS

### Operating System Version

Monterey 12.6.3

### Hardware you are using

MacBook Air (M1, 2020)

**Comment by kazcw** [comment] 2023-08-03 15:50
I encountered something similar:

After scrolling a JSON visualization and scrolling back to the beginning, the beginning became space:
![image](https://github.com/enso-org/enso/assets/1047859/fa3338d7-0c7f-47b7-a1f2-1aa9d183a703)

It happened once while I was testing #7475 (though I don't think it was caused by that PR), and I have not been able to reproduce it. On Linux in my case.

**Comment by farmaazon** [comment] 2023-08-04 10:25
I cannot reproduce it on my end, but this may be just an instance of #7332. Let's check after fixing that if you still reproduce the issue.

**Comment by MichaelMauderer** [comment] 2023-08-14 10:01
@GregoryTravis Can you confirm whether this is fixed now?

**Comment by farmaazon** [comment] 2023-08-29 11:45
@GregoryTravis bump ^

**Comment by GregoryTravis** [comment] 2023-08-30 15:37
This is fixed!

**Comment by radeusgd** [comment] 2023-09-04 09:44
I've found a related bug and was directed here. My issue occurs still at latest develop.

https://github.com/enso-org/enso/assets/1436948/08eb8550-532e-47c3-8754-a2b3f867bda8

If I drag-and-drop this text file into Enso:
[text.txt](https://github.com/enso-org/enso/files/12512394/text.txt)

and open the visualization - a part of the text gets displaced:
![image](https://github.com/enso-org/enso/assets/1436948/99d1b5e3-5281-45c1-b811-2bc6459c01fa)

**Comment by radeusgd** [comment] 2023-09-04 10:05
So I did some digging out of curiosity and it seems that my payload contained a Carriage Return (`\r`) and this seems to mess up the visualization. If replaced by Line Feed (`\n`) it goes back to normal.

For comparison:
![image](https://github.com/enso-org/enso/assets/1436948/fd7a5168-b425-42da-b1c6-8cfc1d0f4388)

**Comment by radeusgd** [comment] 2023-09-04 10:12
(Note that it did not work for me on shorter inputs like `'a\rb'` or `'abc\rdef'`. I suspect the input may need to be long enough to trigger and trip the chunking mechanism. You can always use the sentence from the repro file.)

**Comment by farmaazon** [comment] 2024-02-23 14:39
We don't use lazy JSON visualization in GUI. If we do, it will be tested again against such issues. Closing for now.

**Closed as not planned by farmaazon** 2024-02-23 14:39 UTC
Labels: s-invalid, p-lowest, --bug, -viz
