### ISSUE TITLE
Investigate restart loop when hearbeat is missed in LS

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5094] opened 2023-02-05 22:47 UTC
This task is automatically imported from the old Task Issue Board and it was originally created by Hubert Plociniczak.
Original issue is [here](https://www.pivotaltracker.com/story/show/184250661).
<hr />

I had a recent occasion when LS started to misbehave after missing a hearbeat. Not sure what was the reason but it led to a constant restart loop when it would start loosing a hearbeat after a few seconds of the server being up.

Tasks to investigate:
- reproduce the problem in an isolated setting
- potentially add heartbeat retry with exponential backoff
- add tests, if possible

Thus making it more resilient to failures.

**Comment by hubertp** [comment] 2023-05-16 07:19
Haven't seen it in a while. Closing since unable to reproduce.

**Closed as completed by hubertp** 2023-05-16 07:19 UTC
Labels: p-low, x-chore, -language-server
