### ISSUE TITLE
Project rename text field in the dashboard is no longer editable

### ISSUE THREAD

**Issue by radeusgd** [enso-org/enso#6974] opened 2023-06-07 08:35 UTC
When I'm in the dashboard and I right click on a project (a closed project) and click rename, the rename dialog box shows up:

<img width="369" alt="image" src="https://github.com/enso-org/enso/assets/1436948/5dde49c2-7e4e-469e-96c8-f0dfea225ff1">

However, the text field in this box is not editable anymore (it used to work, so it seems like a regression). I can select text within it using my mouse, but it seems to not react to any keyboard events - so it is impossible to type anything in it.

**Comment by farmaazon** [comment] 2023-06-07 08:39
Duplicate of [#6828](https://github.com/enso-org/enso/issues/6828)

**Closed as not planned** 2023-06-07 08:40 UTC
Labels: s-duplicate, --regression
