### ISSUE TITLE
When in full screen visualization mode, you cannot interact with the JS Visualisation

### ISSUE THREAD

**Issue by jdunkerley** [enso-org/enso#7609] opened 2023-08-18 09:15 UTC
You get a single click and then the visualization is no longer responsive.

https://github.com/enso-org/enso/assets/4699705/eac03581-2481-443b-9808-5167f1c9d87f

**Comment by vitvakatu** [comment] 2023-08-18 09:36
Duplicate of https://github.com/enso-org/enso/issues/7524

**Closed as not planned by vitvakatu** 2023-08-18 09:36 UTC
Labels: s-duplicate, --breaking, p-highest, --bug, --regression
