### ISSUE TITLE
Dragging fullscreen visualisation view also moves camera in graph editor

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5075] opened 2023-02-05 22:46 UTC
This task is automatically imported from the old Task Issue Board and it was originally created by Greg Ociepka.
Original issue is [here](https://www.pivotaltracker.com/story/show/184345926).
<hr />

Repro steps:
1. launch fullscreen visualisation
2. drag the view with the mouse
3. exit fullscreen view

See the attached video for example

## Comments:
 (Greg Ociepka - Jan 30, 2023)
<hr />
Seems related to the navigator. Clearly GUI only issue.  (Michael Mauderer - Feb 1, 2023)
<hr />

**Comment by farmaazon** [comment] 2023-03-21 09:09
Reopening it, as Geo Map full screen visualization is still affected.

**Comment by sylwiabr** [comment] 2023-03-30 11:17
The grid view visualization is still not working properly. If a user open table vis on a full screen, click on a table and scroll the view the nodes are scrolled as well.

**Comment by wdanilo** [comment] 2023-03-30 11:21
@sylwiabr could you post a screencast, please? Also, does it happen when you have mouse inertia (scrolling after stopping scrolling) or it moves nodes even if you close the visualization after completely scrolling it?

**Comment by sylwiabr** [comment] 2023-03-30 11:30
The only thing that has to happen is a click on the table in full screen view + scroll, does not have to be with inertia 

https://user-images.githubusercontent.com/12892578/228822063-d752f742-0784-4b03-b19f-b4842a553a4d.mov

**Comment by vitvakatu** [comment] 2023-05-02 17:28
@wdanilo, we accidentally stole this issue from you today. Do you still have plans to work on it? 
If not, can you share the current progress with @Procrat?

**Comment by sylwiabr** [comment] 2023-05-03 06:44
I removed this issue from @wdanilo so feel free to reassign :) @vitvakatu @Procrat 

extra info - the issue is there if you click on the full screen visualization

**Closed as completed** 2023-05-05 09:04 UTC
Labels: p-high, --bug, --regression
