### ISSUE TITLE
IDE is freezing on startup 

### ISSUE THREAD

**Issue by sylwiabr** [enso-org/enso#6746] opened 2023-05-18 07:04 UTC
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

IDE is freezing on startup twice:
1. When IDE is waiting for the nodes.
2. When I have a project with larger amount of nodes with widgets(after nodes are already colored). It can be observed i.e. on COVID template.

### Expected behaviour

IDE should be responsive. Cursor should not freeze in the middle of the screen.

### Screenshots or screencasts

https://github.com/enso-org/enso/assets/12892578/f8511563-d9a3-4a1e-a4a4-b257898de379

### Enso Version

Nightly 18.05

### Browser or standalone distribution

Standalone distribution (local project)

### Browser Version or standalone distribution

standalone

### Operating System

MacOS

**Comment by Frizi** [comment] 2023-05-18 11:20
This is a duplicate of https://github.com/enso-org/enso/issues/6630

**Closed as not planned by Frizi** 2023-05-18 11:20 UTC
Labels: --bug
