### ISSUE TITLE
Cannot open .enso-project files

### ISSUE THREAD

**Issue by kazcw** [enso-org/enso#10282] opened 2024-06-13 16:19 UTC
When importing a .enso-project file by clicking on it (tested on Mac), Enso opens and the newly imported project appears in the dashboard, but the imported project fails to open.

<img width="1196" alt="Screenshot 2024-06-13 at 09 17 16" src="https://github.com/enso-org/enso/assets/1047859/69a54d01-37c1-4fa0-aa93-b3cf9489e77c">

**Comment by hubertp** [comment] 2024-06-19 15:04
Assigning to myself to identify where is the problem.

**Comment by hubertp** [comment] 2024-06-20 10:14
I can't reproduce so I assume that this will be a mac-only bug.

**Comment by hubertp** [comment] 2024-06-20 10:56
Seems to be Mac-only bug as I couldn't reproduce. Also based on other user logs it doesn't look like backend even gets a request to start the project. So giving back the ticket.

**Comment by jdunkerley** [comment] 2024-06-26 14:42
This is happening on Windows as well in current release.

**Comment by jdunkerley** [comment] 2024-06-26 14:46
**To clarify:**
Enso projects should always be loaded into the local drive and opened from there if double-clicked.
If they want to upload they should drag the project to the cloud drive or click upload button.

**Comment by somebody1234** [comment] 2024-06-27 07:29
@jdunkerley i think that's it... thanks, lol

**Closed as completed** 2024-06-27 17:48 UTC
Labels: p-highest, --bug, -project-manager, g-dashboard
