### ISSUE TITLE
Local dashboard broken when there is no enso-projects folder

### ISSUE THREAD

**Issue by AdRiley** [enso-org/enso#10432] opened 2024-07-03 08:12 UTC
If I don't have a enso-projects folder (if I am a new user for example) then the dashboard is stuck in a spinning state and the product is unusable.

![image](https://github.com/enso-org/enso/assets/1720119/a1505f6c-d7fa-4775-a66c-92301e0fd23e)

**Comment by farmaazon** [comment] 2024-07-03 08:19
Duplicate of https://github.com/enso-org/enso/issues/10387

**Closed as not planned by farmaazon** 2024-07-03 08:19 UTC
Labels: s-duplicate, p-highest, --bug, g-dashboard
