### ISSUE TITLE
Initial space automatically inserted after creating node breaks methods

### ISSUE THREAD

**Issue by kazcw** [enso-org/enso#6542] opened 2023-05-04 05:57 UTC
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [X] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

When I create a new node using the output of a previous node, e.g. by:
- Dragging from the output of an existing node and releasing the mouse,
- Typing `.some_method` or selecting a method from the component browser,
- Commit changes (by clicking somewhere outside the node).
After committing the changes, the resulting new node has a space between the name of the input node and the `.method`. This space causes a syntax error.

### Expected behaviour

Should be able to define new nodes that call methods on previous nodes

### Enso Version

current `develop` (bb8f910b)

### Browser or standalone distribution

Standalone distribution

### Browser Version or standalone distribution

standalone

### Operating System

Linux

**Comment by 4e6** [comment] 2023-05-04 16:45
It's easier to see on the screencast

[6542-initial-space.webm](https://user-images.githubusercontent.com/357683/236270633-5aa3e84a-c4da-41fc-9dc1-4ddea71d44f0.webm)

**Comment by wdanilo** [comment] 2023-05-04 18:14
Duplicate of: https://github.com/enso-org/enso/issues/6484

**Closed as not planned** 2023-05-04 18:14 UTC
Labels: s-duplicate, --bug

**Comment by farmaazon** [comment] 2023-05-08 09:15
@kazcw just don't type initial `.` and everything should work smoothly

It should be obvious to the user once we implement #5232 as the input will be prepopulated with `operator1.` string.
