### ISSUE TITLE
Full-screen visualization is blank when opening it for the first time

### ISSUE THREAD

**Issue by Akirathan** [enso-org/enso#6770] opened 2023-05-18 18:36 UTC
Select an arbitrary node, and open a full-screen visualization before normal visualization - that will display blank full screen.
You need first to toggle normal visualization in order for the full-screen visualization to show anything. All the nodes seem to be affected.

[blank-full-viz.webm](https://github.com/enso-org/enso/assets/14013887/723d25eb-32ce-4878-a500-4b72ac722537)

**Comment by farmaazon** [comment] 2023-05-19 07:40
@MichaelMauderer is this the same issue as you're working on? https://github.com/enso-org/enso/issues/6561

**Comment by MichaelMauderer** [comment] 2023-05-22 09:03
This should be fixed with my PR for "no update for the full screen visualization if it was opened before IDE got the data - it is never updated and needs reopening," in https://github.com/enso-org/enso/issues/6561

**Comment by farmaazon** [comment] 2023-05-22 09:12
Ok, so closing as duplicate of https://github.com/enso-org/enso/issues/6561

**Closed as completed by farmaazon** 2023-05-22 09:12 UTC
Labels: s-duplicate, --regression, -viz
