### ISSUE TITLE
Visualisation on node with error doesn't show on spacebar press

### ISSUE THREAD

**Issue by xvcgreg** [enso-org/enso#6492] opened 2023-05-01 14:00 UTC
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

While having node selected space bar doesn't show visualisation of error.

https://user-images.githubusercontent.com/108271897/235462244-782200ef-ce0f-4be2-bd16-3631c6d3de2a.mp4

Visualisation of error is only visible while hovering on the output port of the node.

### Expected behaviour

Space bar pressed while node with error is selected shows the error message (warnings viz)

### How we can reproduce it?

on node with error
select it 
press spacebar

### Enso Version

2023.5.1 nightly

### Browser or standalone distribution

Standalone distribution

### Browser Version or standalone distribution

standalone

### Operating System

Windows

### Operating System Version

Win11pro 22H2 22621.1555

### Hardware you are using

12th Gen Intel(R) Core(TM) i9-12900HK / RTX3060 Laptop / Nvidia Drivers 531.68

**Comment by hubertp** [comment] 2023-05-01 14:05
Probably a duplicate of https://github.com/enso-org/enso/issues/6454

**Comment by sylwiabr** [comment] 2023-05-01 15:01
Actually this is an error, not a warning (there is type error message at some point) - nodes with errors does not have the visualization as they are not producing result (unlike the nodes with warnings). The boarder of the node is red, not yellow like for a warning. We should have an option to show error message permanently but this is not a valid bug.

**Closed as not planned by sylwiabr** 2023-05-01 15:01 UTC
Labels: s-wontfix, --bug, -viz

**Comment by xvcgreg** [comment] 2023-05-02 09:00
@sylwiabr visualization should work no matter what it is - error or warning. After pressing space I should get the same visualisation as on hover over output.

**Comment by sylwiabr** [comment] 2023-05-02 09:09
The warnings showing in the visualization is a temporary hack that should be revisited and improved (there is an issue for this) so it should be fixed by fixing warnings displaying correctly, not going with merging errors into visualizations. @xvcgreg
