### ISSUE TITLE
Changing a collapsed function does not recalculate on return

### ISSUE THREAD

**Issue by jdunkerley** [enso-org/enso#11272] opened 2024-10-08 13:44 UTC
To reproduce:
- Create a simple graph with 2 numerical constants
- Add a node multiplying them
- Create collapsed function with * and rhs constant.
- Enter, and change constant value.

Graph is not re-evaluated on the change

https://github.com/user-attachments/assets/cfbe795f-db86-4394-aeeb-909d83cdefde

**Comment by hubertp** [comment] 2024-10-08 18:34
Confirmed.

**Comment by farmaazon** [comment] 2024-10-09 07:35
I think this is exactly the same issue as in https://github.com/enso-org/enso/issues/11251

**Comment by hubertp** [comment] 2024-10-09 10:32
> I think this is exactly the same issue as in #11251

I don't think so. `collapsed` works just fine. `Main.collapsed` does not.
Only similarity might stem from the fact that dataflow analysis produces ~~wrong~~ incomplete results.

**Comment by farmaazon** [comment] 2024-10-09 12:00
> I don't think so. `collapsed` works just fine. `Main.collapsed` does not. Only similarity might stem from the fact that dataflow analysis produces ~wrong~ incomplete results.

I don't understand. #11251 is not about `collapsed` vs `Main.collapsed`? I also used `Main.` notation in my project there...

**Comment by hubertp** [comment] 2024-10-09 18:36
> I don't understand. #11251 is not about `collapsed` vs `Main.collapsed`? I also used `Main.` notation in my project there...

This ticket is about re-execution of values depending on the result of the (collapsed) function. Pretty sure the problem is lack of cache invalidation for the culprit nodes. We still execute the program, I've seen it in the logs.

#11251 appears to not have executed (part of) the program at all, or the node would have received the result.

**Comment by hubertp** [comment] 2024-10-11 09:14
A slightly different observation - it looks like there might be something wrong with instrumentation. Outdated results happen for assignments wrapped in ExpressionNodeWrappers, while those resulting in correct values go through IRToTruffle and do not involve any wrappers.

In that sense it might indeed be similar to #11251 as @4e6 also expressed some potential problems with instrumentation.

**Comment by hubertp** [comment] 2024-10-13 21:01
@4e6 I can confirm that your investigation into #11251 explains this bug as well, as described in https://github.com/enso-org/enso/issues/11251#issuecomment-2407988104

**Comment by hubertp** [comment] 2024-10-18 15:02
Fixed in #11251

**Closed as completed by hubertp** 2024-10-18 15:02 UTC
Labels: p-highest, --regression, -language-server
