### ISSUE TITLE
GUI2 crashes when reloading the dev page

### ISSUE THREAD

**Issue by radeusgd** [enso-org/enso#8504] opened 2023-12-09 16:03 UTC
I had some troubles with refreshing computations in GUI2, so I tried refreshing the tab. First time it worked. Second time it stopped responding and the `npm run dev` process printed the following logs before exiting:
```
new session with ws://127.0.0.1:59665
LS connection initialized.
new session with ws://127.0.0.1:59665
LS connection initialized.
Session release failed.
 LsRpcError: Language server request 'text/closeFile' failed.
    at LanguageServer.request (file:///C:/NBO/enso/app/gui2/vite.config.ts.timestamp-1702136560814-5c68798522b88.mjs:328:15)
    at async Promise.all (index 0)
    at async file:///C:/NBO/enso/app/gui2/vite.config.ts.timestamp-1702136560814-5c68798522b88.mjs:1816:7 {
  cause: JSONRPCError: Request timeout request took longer than 15000 ms to resolve
      at new JSONRPCError (C:\NBO\enso\node_modules\@open-rpc\client-js\build\Error.js:24:28)
      at Timeout._onTimeout (C:\NBO\enso\node_modules\@open-rpc\client-js\build\transports\TransportRequestManager.js:134:20)
      at listOnTimeout (node:internal/timers:569:17)
      at process.processTimers (node:internal/timers:512:7) {
    code: 7777,
    data: undefined
  },
  request: 'text/closeFile',
  params: {
    path: {
      rootId: '2f35cb68-2106-465c-99a4-55945930d287',
      segments: [Array]
    }
  }
}
file:///C:/NBO/enso/app/gui2/vite.config.ts.timestamp-1702136560814-5c68798522b88.mjs:326
        throw new LsRpcError(new RemoteRpcError(remoteError.data), method, params);
              ^

LsRpcError: Language server request 'text/openFile' failed.
    at LanguageServer.request (file:///C:/NBO/enso/app/gui2/vite.config.ts.timestamp-1702136560814-5c68798522b88.mjs:326:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  cause: RemoteRpcError {
    code: 1005,
    message: 'IO operation timeout',
    data: undefined
  },
  request: 'text/openFile',
  params: {
    path: {
      rootId: '2f35cb68-2106-465c-99a4-55945930d287',
      segments: [ 'src', 'Main.enso' ]
    }
  }
}

Node.js v18.14.1
npm ERR! Lifecycle script `dev` failed with error:
npm ERR! Error: command failed
npm ERR!   in workspace: enso-gui2@0.1.0
npm ERR!   at location: C:\NBO\enso\app\gui2
```

**Comment by somebody1234** [comment] 2023-12-09 16:10
may be a duplicate of:
- #8398

**Comment by farmaazon** [comment] 2023-12-11 09:11
Yes, it is.

**Comment by somebody1234** [comment] 2023-12-11 22:03
Closing as duplicate

**Closed as not planned by somebody1234** 2023-12-11 22:03 UTC
Labels: s-duplicate, --bug, -gui
