### ISSUE TITLE
Welcome screen regressions

### ISSUE THREAD

**Issue by sylwiabr** [enso-org/enso#5963] opened 2023-03-16 09:37 UTC
### What type of issue is this?

Permanent – Ocurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [x] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

Missing `Create new project` button, regressions in projects list, text on examples list is placed wrongly

### Expected behaviour

Correct rendering of welcome screen

### Screenshots or screencasts

<img width="1283" alt="image" src="https://user-images.githubusercontent.com/12892578/225576025-948b0644-080b-4bee-871b-46fc83bcc055.png">

### Enso Version

e9600f5eac47ecafc4424ac7df4b6e429dc8e446

### Browser or standalone distribution

Standalone distribution

### Browser Version or standalone distribution

Standalone

### Operating System

MacOS

**Comment by vitvakatu** [comment] 2023-03-16 09:51
Bisecting now, as I also faced this issue and got interested.

**Comment by vitvakatu** [comment] 2023-03-16 10:22
It is caused by https://github.com/enso-org/enso/pull/5798
@PabloBuchu please prepare a fix or revert of the PR.

**Comment by somebody1234** [comment] 2023-03-16 12:48
looks like this happens because of the addition of `tailwind.css`. this specific issue is because of `* { box-sizing: border-box; }`.
it can be fixed (temporarily) by adding `<style>img { box-sizing: content-box; }</style>` to `app/ide-desktop/lib/content/src/index.html`

not sure if there's a better fix

**Comment by somebody1234** [comment] 2023-03-16 13:06
fix has been pushed and PR opened

**Comment by wdanilo** [comment] 2023-03-17 06:46
@somebody1234 @PabloBuchu @indiv0 how this regression happened? Was the PR causing this regression not tested? Was there Q/A process for the PR? Guys, please follow our PR rules – for every PR there should be all checkboxes clicked and there should be another person delegated doing Q/A. Starting today, let's merge only PRs that have explicit comment that Q/A was done (just like we do in the GUI and Engine teams).

**Comment by indiv0** [comment] 2023-03-17 08:14
@wdanilo this regression was my fault. It was one of the issues I was tracking that needed to be fixed, but it slipped through. Next time I will leave a comment or FIXME in the code or github comments as a reminder. I'm not sure if there was independent Q/A on this PR either. We will perform explicit Q/A from now on.

**Closed as completed** 2023-03-17 08:23 UTC
Labels: --bug, --regression
