### ISSUE TITLE
CB should not show `local.project_name` when searching for a phrase this is a part of the project name

### ISSUE THREAD

**Issue by sylwiabr** [enso-org/enso#7610] opened 2023-08-18 12:28 UTC
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

When searching for `new` `local.New_Project_16` appeared on the top of the search and it should not be visible at all

### Expected behaviour

as described

### Screenshots or screencasts

![image](https://github.com/enso-org/enso/assets/12892578/baddda27-0aeb-4321-a66f-04d7a9577831)

### Enso Version

nightly 17.08

### Browser or standalone distribution

Standalone distribution (local project)

### Browser Version or standalone distribution

standalone

### Operating System

MacOS

**Comment by farmaazon** [comment] 2023-08-29 11:55
`local.New_Project_16` is not only a project name, but also a reference to the project's main module. The filtering used to browse all possible entities, and this is by design.

@sylwiabr are you sure this is a bug? Maybe we just don't want to display any modules in search?

**Comment by somebody1234** [comment] 2023-08-29 11:59
i think it doesn't matter too much whether it's present, but i *do* think it's not too useful as the very first entry

**Comment by farmaazon** [comment] 2023-08-29 12:34
So it's more about broken scoring than showing wrong entries?

**Comment by somebody1234** [comment] 2023-08-29 12:43
i'd say yes, it looks like the issues here are:

- appeared on the top of the search
  - this is explicitly a scoring issue
- should not be visible at all
  - it's not possible to hide it completely, because it *is* visible by design
  - but it is true that if it is far enough up the results list, then for all intents and purposes it's as if it wasn't there

re: displaying modules, if there's nothing useful that can be done with them then they probably shouldn't show up. but assuming you can drag a new node out and access static methods from there, then they should probably stay?

**Comment by farmaazon** [comment] 2023-08-30 07:35
[We planned](https://github.com/enso-org/enso/issues/4967) to make it working this way, that selecting a module will put its name with dot at the end, and the module content will be displayed in CB.

**Comment by farmaazon** [comment] 2024-03-12 09:40
Fixed in new GUI - the module name is not the best match.

**Closed as not planned by farmaazon** 2024-03-12 09:40 UTC
Labels: s-info-needed, d-easy, p-low, --bug, -gui
