### ISSUE TITLE
Animation looks like Enso's frozen/non responsive

### ISSUE THREAD

**Issue by xvcgreg** [enso-org/enso#6599] opened 2023-05-08 11:12 UTC
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

When I have switched from one project to another by ``Ctrl+o`` the animation played several time and froze on grey logo representation. For the user It  looks like it's broken and it hangs on it for a long time. 

### Expected behaviour

Animation playing until Enso's ready to display the graph

### How we can reproduce it?

open project X (can be small)
wait till it fully loads
press ``ctrl+o``
chose some large project
observe the animation

### Screenshots or screencasts

https://user-images.githubusercontent.com/108271897/236809371-866dde69-28be-4c86-87ba-040d8cfc18bc.mp4

### Enso Version

2023.5.6 nightly

### Browser or standalone distribution

Standalone distribution

### Browser Version or standalone distribution

standalone

### Operating System

Windows

### Operating System Version

Win11pro 22H2 22621.1555

### Hardware you are using

12th Gen Intel(R) Core(TM) i9-12900HK / RTX3060 Laptop / Nvidia Drivers 531.68

**Comment by wdanilo** [comment] 2023-05-09 09:34
Greg, when reporting such issues, yo should have logs enabled in the recording. You are enabling logs too late - could you re-record this with `showLogs` enabled on the beginning, please? Otherwise, its impossible to understand where the app hangs.

**Comment by xvcgreg** [comment] 2023-05-09 11:54
Sure, here it is:

https://github.com/enso-org/enso/assets/108271897/1dde0e9f-9229-412a-a57d-32f47fc5f0ea

**Comment by wdanilo** [comment] 2023-05-10 04:29
@Procrat would your PR (https://github.com/enso-org/enso/pull/6321) fix this?

**Comment by Procrat** [comment] 2023-05-10 07:58
> @Procrat would your PR (#6321) fix this?

It might, but I've never encountered this bug before, so I wouldn't bet on it.

**Comment by Frizi** [comment] 2023-05-15 09:58
Reproduced and profiled (see attached file). I believe this is strictly a performance issue related to initialization of all node views, and possibly drop of the ones from previously loaded project. The spinner locks up, because the whole main thread is busy for a long time. We cannot run animations while the main thread is locked for such a long time on a single task.


![image](https://github.com/enso-org/enso/assets/919491/e7405981-6cfc-4dcf-82b9-1dd1f4e710e7)
[Profile-20230515T115534.zip](https://github.com/enso-org/enso/files/11476570/Profile-20230515T115534.zip)

**Comment by wdanilo** [comment] 2023-05-17 05:35
Thanks @Frizi. I believe that in such a case, it is a WONTFIX for now. We should get back to it when we improve the performance of node/graph initialization. Probably after new FRP lands.

**Closed as not planned** 2023-05-19 10:03 UTC
Labels: s-wontfix, --bug, --low-performance
