### ISSUE TITLE
Node changing width rapidly when connecting a parameter

### ISSUE THREAD

**Issue by radeusgd** [enso-org/enso#6851] opened 2023-05-25 14:58 UTC
Video:

https://github.com/enso-org/enso/assets/1436948/3e5b5b98-f345-43bb-a57f-4d1e00f3c2c5

Sometimes when I create a new connection, I can see that the node is being recomputed and for a brief moment, its other input ports (placeholders) disappear, only to reappear after ~1s as it is recomputed.

This creates an ugly 'flickering' on the stage - the node briefly becomes much smaller than it used to, only to return to its original size after a moment.

Can we do something to prevent the 'flickering'? For example by still displaying the old layout (possibly somehow greyed-out to indicate that a 'change is in progress') while it is being recomputed?

**Comment by wdanilo** [comment] 2023-05-26 05:46
I believe this is duplicate of one task @Frizi has on hist plate. @Frizi could you confirm and close this if I'm right, please?

**Comment by radeusgd** [comment] 2023-05-26 10:39
Likely a related issue:

https://github.com/enso-org/enso/assets/1436948/806864d5-16c7-47b7-af65-6e07665daa22

When I insert a new node from the Searcher, for a brief moment it so happens that there are parameters displayed next to it - but these parameters are from **some other** method - i.e. for `aggregate` an `order` parameter is displayed - but `aggregate` has no such parameter. After a short moment that is replaced with the later 'correct' set of parameters. But ideally, no parameters should rather be displayed than wrong ones.

I'm not sure if these two issues are related or not - I think they may be but if it's unrelated that may need to be split off as a separate issue.

**Comment by wdanilo** [comment] 2023-05-26 10:59
@farmaazon is this the same issue? I remember I was chatting with you about it and you explained to me then why it works now this way.

**Comment by farmaazon** [comment] 2023-05-26 11:06
This (the @radeusgd comment) is tracked by https://github.com/enso-org/enso/issues/6349

(I don't blame you, I was hard to dig it up).

**Comment by farmaazon** [comment] 2023-05-26 11:09
> Can we do something to prevent the 'flickering'? For example by still displaying the old layout (possibly somehow greyed-out to indicate that a 'change is in progress') while it is being recomputed?

I think we _can_ do something. We remove arguments, because we receive "Pending" expression update, which removes method_pointer. But we can preserve method_pointers in case of Pending payloads.

**Closed as completed** 2023-06-26 09:44 UTC
Labels: d-easy, p-high
