### ISSUE TITLE
Wrongly placed visualization and no node visible until typing the first letter.

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5183] opened 2023-02-05 22:51 UTC
This task is automatically imported from the old Task Issue Board and it was originally created by Greg Ociepka.
Original issue is [here](https://www.pivotaltracker.com/story/show/184327438).
<hr />

There is a regression introduced by Wojciech PR (https://github.com/enso-org/enso/pull/3678). After pressing tab we can see this (see pic attached). The node is visible and vis position correct after typing any letter. This regression is introduced because now we are not redrawing texts like crazy, and thus, an empty text does not empit its size FRP signals when not needed. So the current behavior of the text API is correct, but the app behavior is not. Because the PR was blocking multiple other PRs and we had trouble merging it, we merged it and this regression will be fixed in my upcoming PR.

https://discord.com/channels/401396655599124480/1026689608710361088

**Comment by sylwiabr** [comment] 2023-04-03 07:46
It looks like it was fixed on newest develop (3.04.2023)

**Comment by farmaazon** [comment] 2023-04-03 11:12
Yes, I can confirm it is no longer an issue. Closing.

**Closed as completed by farmaazon** 2023-04-03 11:12 UTC
Labels: p-low, --bug, --regression
