### ISSUE TITLE
Renaming a project silently fails with no explanation

### ISSUE THREAD

**Issue by JaroslavTulach** [enso-org/enso#6214] opened 2023-04-06 07:58 UTC
### Renaming Problem

I am not able to rename a project. I change the name in the IDE, but when I check via CLI, there is still the `Unnamed` project and its `package.yaml` continues to say `Unnamed`:
```
~/enso/projects$ cat Unnamed/package.yaml 
name: Unnamed
namespace: local
version: 0.0.1
license: ''
authors: []
maintainers: []
edition: 0.0.0-dev
prefer-local-libraries: true
```
yet the IDE shows the renamed name:
![IDE shows the right name](https://user-images.githubusercontent.com/26887752/230310940-5dcb2e79-db38-4c7b-b679-c62415d70c3b.png)

### Snake Case is the Cause!

I was wondering why the rename fails for weeks or even months, now I have finally taken a look in the log:
```
[error] [2023-04-06T07:43:04.408Z] [org.enso.projectmanager.requesthandler.ProjectRenameHandler] 
Request Number(3) failed due to ValidationFailure(Project name should be in upper snake case: Book_Club_9.).
```
OK, renaming to `Book_Club_9` works. However we cannot just print a warning to the log file. We have to display something to the IDE user!

### Minimal Expected Behavior

When renaming to `BookClub9` is rejected, a message is displayed to the user explaining the cause and the IDE returns back to the previous (`Unknown`) project name.

**Comment by MichaelMauderer** [comment] 2023-04-06 09:08
Related #5065. Can probably both the solved together.

**Comment by farmaazon** [comment] 2023-04-12 07:58
I'd even say this is a duplicate of https://github.com/enso-org/enso/issues/5065, as the error message is also mentioned there.

**Comment by JaroslavTulach** [comment] 2023-04-12 11:49
> I'd even say this is a duplicate of #5065, as the error message is also mentioned there.

Does a duplicate increases a change of fixing the problem?

**Comment by farmaazon** [comment] 2023-04-13 09:30
> > I'd even say this is a duplicate of #5065, as the error message is also mentioned there.
> 
> Does a duplicate increases a change of fixing the problem?

Not really. It was already planned with @sylwiabr for Design Partners release, but then some more important stuff suddenly arrived (widgets on nodes, execution modes), we'll see if we manage to make this as planned.

**Closed as not planned by farmaazon** 2023-04-13 09:30 UTC
Labels: s-duplicate, p-medium, --bug
