### ISSUE TITLE
For a brief moment, wrong parameters show up on a node

### ISSUE THREAD

**Issue by radeusgd** [enso-org/enso#7228] opened 2023-07-06 11:19 UTC
https://github.com/enso-org/enso/assets/1436948/5b4a8149-8e45-4c9f-ae05-726af7df9687

Repro:
1. Create some table (e.g. load a CSV/Excel)
2. Press Tab to open the CB.
3. Type `join` and press Enter.

The `join` node shows up. For a brief moment we can see it has only 1 parameter - `selector`. But the `Table.join` method does not have such a parameter at all. After a short time, this is replaced with the proper parameters (`right`, `join_kind` etc.).

The node should not display incorrect parameters. Ideally, it should somehow indicate that the parameter metadata is still being loaded so that I know I have to wait for it to be displayed.

**Comment by farmaazon** [comment] 2023-07-06 14:02
Duplicate of #6349

**Closed as not planned by farmaazon** 2023-07-06 14:02 UTC
Labels: s-duplicate, --bug

**Comment by radeusgd** [comment] 2023-07-07 08:43
> Duplicate of #6349

I thought that #6349 was about wrong ports being stuck there, here they appear only for a brief moment, so it looked like a separate problem to me. Possibly, they both may have the same solution.
