### ISSUE TITLE
Back to the Dashboard button visible in the full screen visualisation mode

### ISSUE THREAD

**Issue by xvcgreg** [enso-org/enso#6881] opened 2023-05-29 16:44 UTC
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

The button is visible after entering full scrn visualisation: 
![image](https://github.com/enso-org/enso/assets/108271897/6f7a38a7-f64e-4ce2-87f2-8572db33fcf9)

### Expected behaviour

I actually dont know how it's supposed to look like, and how it was designed to look with data visualisations. I'd expect it either to be hidden during full scrn vis or entire top bar present (alongside this button).

### Enso Version

2023.5.26 nightly

### Browser or standalone distribution

Standalone distribution (local project)

### Browser Version or standalone distribution

standalone

### Operating System

Windows

### Operating System Version

Win11pro 22H2 22621.1555

### Hardware you are using

12th Gen Intel(R) Core(TM) i9-12900HK / RTX3060 Laptop / Nvidia Drivers 531.68

**Comment by farmaazon** [comment] 2023-05-30 07:55
Duplicate of #6839

**Closed as not planned** 2023-05-30 10:08 UTC
Labels: s-duplicate, --bug
