### ISSUE TITLE
Arguments disappear when connecting an edge to an already connected port

### ISSUE THREAD

**Issue by xvcgreg** [enso-org/enso#5896] opened 2023-03-12 17:55 UTC
### What type of issue is this?

Permanent – Ocurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

I'm having function with already connected 2 arguments. When I replace the second port it replaces all arguments within this function to the only one most recently connected. 

https://user-images.githubusercontent.com/108271897/224562969-c3e945ad-d2ea-42ed-84be-c51dd553e59c.mp4

### Expected behaviour

Just last port is replaced with new input.

### How we can reproduce it?

as seen on the vid

### Enso Version

Build: Nightly Release #842

### Browser or standalone distribution

Standalone distribution

### Browser Version or standalone distribution

standalone

### Operating System

Windows

### Operating System Version

11pro 22H2

### Hardware you are using

12th Gen Intel(R) Core(TM) i9-12900HK / RTX3060 Laptop

**Comment by xvcgreg** [comment] 2023-03-12 20:06
This might be handy

```[info] [2023-03-12T17:28:45.559Z] [akka.actor.LocalActorRef] Message [org.enso.languageserver.requesthandler.RequestTimeout$] from Actor[akka://language-server/user/json-connection-controller-158191a7-5612-4fac-86c8-a02e740057f1/request-handler-DetachVisualisation-73e7797c-6940-4c0f-8a79-12bdbcf09d95#-26270604] to Actor[akka://language-server/user/json-connection-controller-158191a7-5612-4fac-86c8-a02e740057f1/request-handler-DetachVisualisation-73e7797c-6940-4c0f-8a79-12bdbcf09d95#-26270604] was not delivered. [1] dead letters encountered. If this is not an expected behavior then Actor[akka://language-server/user/json-connection-controller-158191a7-5612-4fac-86c8-a02e740057f1/request-handler-DetachVisualisation-73e7797c-6940-4c0f-8a79-12bdbcf09d95#-26270604] may have terminated unexpectedly. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
[warn] [2023-03-12T17:28:45.737Z] [enso] Visualisation evaluation failed: Cannot encode class org.enso.interpreter.runtime.error.DataflowError to byte array..
[warn] [2023-03-12T17:28:46.971Z] [enso] Visualisation evaluation failed: Cannot encode class org.enso.interpreter.runtime.error.DataflowError to byte array..
[error] [2023-03-12T17:29:49.329Z] [org.enso.languageserver.search.SuggestionsHandler] Cannot Remove [Local(externalId=Some(8cc43506-898b-40a8-be9b-97bfc2c605db),module=local.Enso_101.Main,name=operator4,returnType=Standard.Base.Any.Any,scope=Scope(Position(21,6),Position(28,42)),documentation=None)].
[error] [2023-03-12T17:32:54.484Z] [org.enso.languageserver.requesthandler.visualisation.DetachVisualisationHandler] Request [Number(1429)] timed out.
[info] [2023-03-12T17:32:59.479Z] [akka.actor.LocalActorRef] Message [org.enso.languageserver.requesthandler.RequestTimeout$] from Actor[akka://language-server/user/json-connection-controller-158191a7-5612-4fac-86c8-a02e740057f1/request-handler-DetachVisualisation-970f2bc4-f201-42dc-8e73-26a136b8943b#1924005382] to Actor[akka://language-server/user/json-connection-controller-158191a7-5612-4fac-86c8-a02e740057f1/request-handler-DetachVisualisation-970f2bc4-f201-42dc-8e73-26a136b8943b#1924005382] was not delivered. [2] dead letters encountered. If this is not an expected behavior then Actor[akka://language-server/user/json-connection-controller-158191a7-5612-4fac-86c8-a02e740057f1/request-handler-DetachVisualisation-970f2bc4-f201-42dc-8e73-26a136b8943b#1924005382] may have terminated unexpectedly. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
[warn] [2023-03-12T17:33:19.72Z] [enso] Visualisation thread interrupted 8fc27a8d-38e5-4f18-9cca-c1185fd159c8.
[warn] [2023-03-12T17:33:20.992Z] [enso] Visualisation evaluation failed: Type error: expected a function, but got 200 (Integer)..
[warn] [2023-03-12T17:33:21.513Z] [enso] Visualisation evaluation failed: Type error: expected a function, but got 200 (Integer)..
[warn] [2023-03-12T17:33:24.259Z] [enso] Visualisation evaluation failed: Method `throw_wrapped_if_error` of 200 (Integer) could not be found..
[warn] [2023-03-12T17:33:24.673Z] [enso] Visualisation evaluation failed: Method `throw_wrapped_if_error` of 200 (Integer) could not be found..
[warn] [2023-03-12T17:33:24.929Z] [enso] Visualisation evaluation failed: Method `throw_wrapped_if_error` of 200 (Integer) could not be found..
[warn] [2023-03-12T17:33:25.652Z] [enso] Execution of function main interrupted.
[warn] [2023-03-12T17:33:29.234Z] [enso] Visualisation evaluation failed: Syntax error: Syntax is not supported yet: qualifiedNameSegment..
[warn] [2023-03-12T17:33:31.264Z] [enso] Visualisation evaluation failed: Type error: expected a function, but got 300 (Integer)..
[warn] [2023-03-12T17:33:31.728Z] [enso] Visualisation evaluation failed: Type error: expected a function, but got 300 (Integer)..
[error] [2023-03-12T17:33:35.917Z] [org.enso.languageserver.search.SuggestionsHandler] Cannot Remove [Function(externalId=Some(17c32ff2-8432-4ffb-a88c-1e4afa2bb77c),module=local.Enso_101.Main,name=operator3,arguments=List(Argument(name=<internal-679>,reprType=Standard.Base.Any.Any,isSuspended=false,hasDefault=false,defaultValue=None,tagValues=None)),returnType=Standard.Base.Any.Any,scope=Scope(Position(21,6),Position(29,19)),documentation=None)].
[warn] [2023-03-12T17:33:49.239Z] [enso] Visualisation evaluation failed: Cannot encode class org.enso.interpreter.runtime.error.DataflowError to byte array..
[warn] [2023-03-12T17:33:55.513Z] [enso] Visualisation evaluation failed: Cannot encode class org.enso.interpreter.runtime.error.DataflowError to byte array..
[warn] [2023-03-12T17:33:55.873Z] [enso] Visualisation evaluation failed: Cannot encode class org.enso.interpreter.runtime.error.DataflowError to byte array..
[warn] [2023-03-12T17:33:57.136Z] [enso] Visualisation evaluation failed: Cannot encode class org.enso.interpreter.runtime.error.DataflowError to byte array..
[warn] [2023-03-12T17:34:02.631Z] [enso] Visualisation evaluation failed: Cannot encode class org.enso.interpreter.runtime.error.DataflowError to byte array..
[warn] [2023-03-12T17:34:24.068Z] [enso] Visualisation evaluation failed: Cannot encode class org.enso.interpreter.runtime.error.DataflowError to byte array..
[warn] [2023-03-12T17:34:49.702Z] [enso] Visualisation evaluation failed: Cannot encode class org.enso.interpreter.runtime.error.DataflowError to byte array..
[warn] [2023-03-12T17:34:49.971Z] [enso] Visualisation evaluation failed: Cannot encode class org.enso.interpreter.runtime.error.DataflowError to byte array..
[warn] [2023-03-12T17:34:53.722Z] [enso] Visualisation evaluation failed: Cannot encode class org.enso.interpreter.runtime.error.DataflowError to byte array..
[warn] [2023-03-12T17:34:55.191Z] [enso] Visualisation evaluation failed: Cannot encode class org.enso.interpreter.runtime.error.DataflowError to byte array..
[warn] [2023-03-12T17:34:55.64Z] [enso] Visualisation evaluation failed: Cannot encode class org.enso.interpreter.runtime.error.DataflowError to byte array..
[warn] [2023-03-12T17:35:01.461Z] [enso] Visualisation evaluation failed: Cannot encode class org.enso.interpreter.runtime.error.DataflowError to byte array..
[warn] [2023-03-12T17:35:13.385Z] [enso] Visualisation evaluation failed: Cannot encode class org.enso.interpreter.runtime.error.DataflowError to byte array..
[error] [2023-03-12T17:35:22.499Z] [org.enso.languageserver.search.SuggestionsHandler] Cannot Remove [Function(externalId=Some(17c32ff2-8432-4ffb-a88c-1e4afa2bb77c),module=local.Enso_101.Main,name=operator3,arguments=List(Argument(name=<internal-736>,reprType=Standard.Base.Any.Any,isSuspended=false,hasDefault=false,defaultValue=None,tagValues=None)),returnType=Standard.Base.Any.Any,scope=Scope(Position(21,6),Position(29,28)),documentation=None)].
[warn] [2023-03-12T17:35:40.831Z] [enso] Visualisation evaluation failed: Cannot encode class org.enso.interpreter.runtime.error.DataflowError to byte array..```

**Comment by wdanilo** [comment] 2023-03-15 03:14
@xvcgreg please format your messages correctly. The above message is formatted wrongly, please fix it.

**Comment by hubertp** [comment] 2023-03-15 08:48
@JaroslavTulach should we have an additional case for `DataFlowError` in https://github.com/enso-org/enso/blob/5c4660b5aade6c392ba635e32799636bcb770fc7/engine/runtime/src/main/java/org/enso/interpreter/instrument/job/VisualizationResult.java#L46?

I doubt this is the reason for the missing argument problem, though. The latter seems like an IDE issue. Maybe something that @Frizi was touching recently?

**Comment by hubertp** [comment] 2023-03-15 09:30
Assigned. Looks like it could be related to recent changes.

**Comment by Frizi** [comment] 2023-03-15 13:03
My changes from #5774 are not present in the version that this issue was found on. I cannot reproduce it on recent develop. To be confirmed once we have a new build.

**Comment by JaroslavTulach** [comment] 2023-03-17 06:08
> @JaroslavTulach should we have an additional case for `DataFlowError` in
> 
> https://github.com/enso-org/enso/blob/5c4660b5aade6c392ba635e32799636bcb770fc7/engine/runtime/src/main/java/org/enso/interpreter/instrument/job/VisualizationResult.java#L46
> ?

If we want to avoid log messages like:
```
[warn] [2023-03-12T17:34:02.631Z] [enso] Visualisation evaluation failed: Cannot encode class org.enso.interpreter.runtime.error.DataflowError to byte array..
```
then yes, we should.

**Comment by hubertp** [comment] 2023-03-17 14:20
@JaroslavTulach I did that in https://github.com/enso-org/enso/pull/4076, which wasn't merged in the end, and the problem came back. @4e6 is my PR still the wrong way to deal with this?

**Comment by sylwiabr** [comment] 2023-04-27 10:30
can not reproduce it with package from develop @ ae94a9f40d3e98b9068da716b8b6416bba517a19

**Closed as completed by sylwiabr** 2023-04-27 10:30 UTC
Labels: p-high, --bug
