### ISSUE TITLE
Cursor keys when editing a node move both the caret position and the selected item in the Component Browser

### ISSUE THREAD

**Issue by jdunkerley** [enso-org/enso#6124] opened 2023-03-29 10:56 UTC
When typing `cross` to find `cross_join` when I then press left to choose the carat moves the CB moves and then CB updates and reselects something random.

https://user-images.githubusercontent.com/4699705/228512681-8ab275a4-471f-4265-b530-0632099feaf3.mp4

**Comment by vitvakatu** [comment] 2023-03-29 11:32
Known issue, caused by lack of focus handling in CB. See #4966

**Comment by farmaazon** [comment] 2023-03-30 08:12
With the new cursor-aware CB, the lack of focus implementation is more frustrating, and the focus epic is not planned for Beta release even. I will look at the epic and take a task (or create a new one) to make at least initial implementation for Design Partners.

**Comment by xvcgreg** [comment] 2023-04-19 08:24
Regarding bug #6289:
This feature worked in build 2023.3.22
But stopped working in build 2023.3.23

When pressing arrow keys to navigate through CB the expected behavior should be like here:

https://user-images.githubusercontent.com/108271897/233014757-07241fa8-8a66-4e5a-aa55-64d106d06ff8.mp4


Now it just resets its position:

https://user-images.githubusercontent.com/108271897/233015175-8ca6747f-6488-4a18-94c3-97b871f02828.mp4

**Comment by vitvakatu** [comment] 2023-04-19 08:37
@xvcgreg, thank you for investigating, but I can probably pinpoint the exact PR that caused this: https://github.com/enso-org/enso/pull/5770, merged on March 22nd. It was expected behavior, and this issue is already scheduled to be fixed before the release.

**Comment by xvcgreg** [comment] 2023-04-20 07:51
@vitvakatu Thanks.

**Closed as completed** 2023-07-26 22:13 UTC
Labels: p-high, --bug, --regression
