### ISSUE TITLE
Add a way to run a single node in a different context in engine.

### ISSUE THREAD

**Issue by farmaazon** [enso-org/enso#10719] opened 2024-07-31 09:34 UTC
To implement #10486, we need to have a way of re-running a single node. With possibility of enabling output context on this node (like it would have `Standard.Base.Runtime.with_enabled_context Standard.Base.Runtime.Context.Output "design" <| ` attached to the expression).

**Comment by hubertp** [comment] 2024-08-06 08:50
This will likely end up as a duplicate of #10730

**Comment by JaroslavTulach** [comment] 2024-08-26 09:18
Re-running a node in different "context" _without modifying a source_ needs some changes in the `language-server` protocol - up to @4e6  and Hubert. I can only imagine we get a request to _re-run a method_ while:
- specifying UUID of the node(s) to _force to recompute_ (e.g. clean from [RuntimeCache](https://github.com/enso-org/enso/blob/e9d3f59a919658e565cd9606f060beb2b551c715/engine/runtime-instrument-common/src/main/java/org/enso/interpreter/instrument/RuntimeCache.java#L16) before recomputing).
- specifying [environment name](https://github.com/enso-org/enso/blob/e9d3f59a919658e565cd9606f060beb2b551c715/engine/runtime/src/main/java/org/enso/interpreter/runtime/state/ExecutionEnvironment.java#L31) or [context identification](https://github.com/enso-org/enso/blob/e9d3f59a919658e565cd9606f060beb2b551c715/engine/runtime/src/main/java/org/enso/interpreter/runtime/state/ExecutionEnvironment.java#L47) (maybe?) to enable when re-computing the node

The next part of work is in [IdExecutionInstrument](https://github.com/enso-org/enso/blob/e9d3f59a919658e565cd9606f060beb2b551c715/engine/runtime-instrument-id-execution/src/main/java/org/enso/interpreter/instrument/IdExecutionInstrument.java#L49):
- [onEnter](https://github.com/enso-org/enso/blob/e9d3f59a919658e565cd9606f060beb2b551c715/engine/runtime-instrument-id-execution/src/main/java/org/enso/interpreter/instrument/IdExecutionInstrument.java#L200) if the right node (with specified UUID) is being entered then change the [State](https://github.com/enso-org/enso/blob/e9d3f59a919658e565cd9606f060beb2b551c715/engine/runtime/src/main/java/org/enso/interpreter/runtime/state/State.java#L30)
- [onReturnValue](https://github.com/enso-org/enso/blob/e9d3f59a919658e565cd9606f060beb2b551c715/engine/runtime-instrument-id-execution/src/main/java/org/enso/interpreter/instrument/IdExecutionInstrument.java#L222) or [onReturnExceptional](https://github.com/enso-org/enso/blob/e9d3f59a919658e565cd9606f060beb2b551c715/engine/runtime-instrument-id-execution/src/main/java/org/enso/interpreter/instrument/IdExecutionInstrument.java#L260) change the [State](https://github.com/enso-org/enso/blob/e9d3f59a919658e565cd9606f060beb2b551c715/engine/runtime/src/main/java/org/enso/interpreter/runtime/state/State.java#L30) back

Changing the state may require
- https://github.com/enso-org/enso/issues/7117#issuecomment-1606665237

e.g. to store `State` as _"thread local variable"_ - but that's something we should do anyway.

**Comment by 4e6** [comment] 2024-08-29 15:14
I propose to update the [`executionContext/recompute` ](https://github.com/enso-org/enso/blob/develop/docs/language-server/protocol-language-server.md#executioncontextrecompute )request with the new optional `expressionConfigs` parameter that tells to execute provided expressions in a specific execution environment

```typescript
interface ExecutionContextRecomputeParameters {
  /** The execution context identifier. */
  contextId: ContextId;
  /** The expressions that will be invalidated before the execution. */
  invalidatedExpressions?: "all" | ExpressionId[];
  /** The execution environment that will be used in the execution. */
  executionEnvironment?: ExecutionEnvironment;
  /** The configuration of how to execute each expression. */
  expressionConfigs?: ExpressionConfig[];
}

interface ExpressionConfig {
  /** The expression identifier. */
  expressionId: UUID;
  /** Run the expression in a specified execution environment. */
  executionEnvironment?: ExecutionEnvironment;
}
```

**Comment by JaroslavTulach** [comment] 2024-08-29 17:37
Updating `recompute` is good approach.

Alternative:
```typescript
invalidatedExpressions?: "all" | ExpressionId[] | ExpressionConfig[]
```

Maybe you want to use `ExpressionId` even in `expressionId: ` definition and not `UUID`?

**Closed as completed** 2024-10-09 12:09 UTC
Labels: p-high, x-new-feature, -language-server
