### ISSUE TITLE
First letter entered in component browser stays rendered after canceling the node creation with Esc

### ISSUE THREAD

**Issue by xvcgreg** [enso-org/enso#6318] opened 2023-04-17 17:37 UTC
### What type of issue is this?

Permanent – Ocurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [x] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

First letter entered in component browser stays rendered after canceling the node creation with Esc

https://user-images.githubusercontent.com/108271897/232565728-919226b4-4748-4e2d-bb12-2363ddf9c5ea.mp4

### Expected behaviour

All letters disappear after the cancelation.

### How we can reproduce it?

1. press TAB
2. start entering letters/numbers
3. cancel node creation with ESC key

### Enso Version

2023.4.15

### Browser or standalone distribution

Standalone distribution

### Browser Version or standalone distribution

standalone

### Operating System

Windows

### Operating System Version

11pro 22H2

### Hardware you are using

12th Gen Intel(R) Core(TM) i9-12900HK / RTX3060 Laptop

**Comment by kazcw** [comment] 2023-04-17 19:16
I'm not able to reproduce this on Linux / current develop (b700679d35) / backend-release=latest. I will try on a Windows machine...

**Comment by kazcw** [comment] 2023-04-17 19:26
I can reproduce this on Windows, 4/15 nightly. I'll look in to it.

**Comment by kazcw** [comment] 2023-04-18 00:05
This is a case of the same bug as #6320 (note the same GL error in debug logs). I'll close this one, as the other description is more general

**Closed as completed by kazcw** 2023-04-18 00:05 UTC
Labels: s-duplicate, p-high, --bug, --regression
