### ISSUE TITLE
Redundant `from` declarations give unclear error

### ISSUE THREAD

**Issue by GregoryTravis** [enso-org/enso#8104] opened 2023-10-18 16:03 UTC
```
## PRIVATE
   Conversion method to a Table from a Vector.
Table.from (that:Vector) (fields : (Vector | Nothing) = Nothing) = that.to_table fields
Table.from (that:Vector) (fields : (Vector | Nothing) = Nothing) = 12
```

Results in the error below, when running test/Tests/src/Data/XML/XML_Spec.enso. The cause isn't clear from the error message. The failing test does not need to actually use `from` to trigger the error.

```
Read XML:  [2/7, 525ms]
    - [FAILED] Can read from a file [210ms]
        Reason: An unexpected dataflow error (Module_Not_In_Package_Error.Error) has been matched (at /Users/gmt/dev/enso/enso/test/Tests/src/Data/XML/XML_Spec.enso:15:13-44).
        at <enso> Enso_Project.enso_project(/Users/gmt/dev/enso/enso/built-distribution/enso-engine-0.0.0-dev-macos-amd64/enso-0.0.0-dev/lib/Standard/Base/0.0.0-dev/src/Meta/Enso_Project.enso:101:5-52)
        at <enso> XML_Spec.spec<arg-0>(/Users/gmt/dev/enso/enso/test/Tests/src/Data/XML/XML_Spec.enso:9:17-28)
        at <enso> XML_Spec.spec<arg-0>(/Users/gmt/dev/enso/enso/test/Tests/src/Data/XML/XML_Spec.enso:9:17-33)
        at <enso> XML_Spec.spec<arg-0>(/Users/gmt/dev/enso/enso/test/Tests/src/Data/XML/XML_Spec.enso:9:17-41)
        at <enso> XML_Spec.spec(/Users/gmt/dev/enso/enso/test/Tests/src/Data/XML/XML_Spec.enso:9:17-56)
        at <enso> XML_Spec.main<arg-1>(/Users/gmt/dev/enso/enso/test/Tests/src/Data/XML/XML_Spec.enso:226:28-31)
        at <enso> Test_Suite.type.run<arg-1>(/Users/gmt/dev/enso/enso/built-distribution/enso-engine-0.0.0-dev-macos-amd64/enso-0.0.0-dev/lib/Standard/Test/0.0.0-dev/src/Test_Suite.enso:69:17-21)
        at <enso> Test_Suite.type.run<arg-1>(/Users/gmt/dev/enso/enso/built-distribution/enso-engine-0.0.0-dev-macos-amd64/enso-0.0.0-dev/lib/Standard/Test/0.0.0-dev/src/Test_Suite.enso:68-70)
        at <enso> Test_Reporter.wrap_junit_testsuites(/Users/gmt/dev/enso/enso/built-distribution/enso-engine-0.0.0-dev-macos-amd64/enso-0.0.0-dev/lib/Standard/Test/0.0.0-dev/src/Test_Reporter.enso:18:14-19)
        at <enso> Test_Suite.type.run(/Users/gmt/dev/enso/enso/built-distribution/enso-engine-0.0.0-dev-macos-amd64/enso-0.0.0-dev/lib/Standard/Test/0.0.0-dev/src/Test_Suite.enso:67-70)
        at <enso> Test_Suite.type.run_main(/Users/gmt/dev/enso/enso/built-distribution/enso-engine-0.0.0-dev-macos-amd64/enso-0.0.0-dev/lib/Standard/Test/0.0.0-dev/src/Test_Suite.enso:40:13-39)
        at <enso> XML_Spec.main(/Users/gmt/dev/enso/enso/test/Tests/src/Data/XML/XML_Spec.enso:226:8-31)
```

**Comment by radeusgd** [comment] 2023-11-06 16:14
I could not reproduce this issue beyond what is already included within #7853

@GregoryTravis can you see if you can reproduce this issue anymore?

If not, I will close it as duplicate of #7853

**Comment by GregoryTravis** [comment] 2023-11-06 18:26
I'm getting a different error now:

```
diff --git a/distribution/lib/Standard/Table/0.0.0-dev/src/Data/Table.enso b/distribution/lib/Standard/Table/0.0.0-dev/src/Data/Table.enso
index 7fd22e609..a391c8731 100644
--- a/distribution/lib/Standard/Table/0.0.0-dev/src/Data/Table.enso
+++ b/distribution/lib/Standard/Table/0.0.0-dev/src/Data/Table.enso
@@ -2689,6 +2689,7 @@ Text.from (that : Table) (format:Delimited_Format = Delimited_Format.Delimited '
 ## PRIVATE
    Conversion method to a Table from a Vector.
 Table.from (that:Vector) (fields : (Vector | Nothing) = Nothing) = that.to_table fields
+Table.from (that:Vector) (fields : (Vector | Nothing) = Nothing) = that.to_table fields

 ## Convert an `XML_Element` into a `Table`
```

I'm getting:

```
Execution finished with an error: java.lang.IllegalArgumentException: requirement failed: end:88 must be less than or equal to length:87
        at <java> scala.Predef$.require(Predef.scala:337)
        at <java> fansi.Str.$anonfun$overlayAll$2(Fansi.scala:187)
        at <java> fansi.Str.$anonfun$overlayAll$2$adapted(Fansi.scala:179)
        at <java> scala.collection.IterableOnceOps.foreach(IterableOnce.scala:576)
        at <java> scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:574)
        at <java> scala.collection.AbstractIterable.foreach(Iterable.scala:933)
        at <java> scala.collection.IterableOps$WithFilter.foreach(Iterable.scala:903)
        at <java> fansi.Str.overlayAll(Fansi.scala:179)
        at <java> fansi.Str.overlay(Fansi.scala:167)
```

**Comment by radeusgd** [comment] 2023-11-07 10:25
So that seems to be the exact same error as in #7853, so I will close this as a duplicate.

**Closed as not planned by radeusgd** 2023-11-07 10:25 UTC
Labels: s-duplicate, p-low, -compiler
