### ISSUE TITLE
Occasional AssertError while executing stdlib tests

### ISSUE THREAD

**Issue by hubertp** [enso-org/enso#11175] opened 2024-09-26 06:38 UTC
```
 INFO ide_ci::program::command: bash ⚠️ Exception in thread "main" java.lang.AssertionError: Failed to log failed conversion of null to string and payload Error Error.type UnresolvedSymbol<==>
 INFO ide_ci::program::command: bash ⚠️ 	at org.enso.runtime/org.enso.interpreter.runtime.error.PanicException.computeMessage(PanicException.java:95)
 INFO ide_ci::program::command: bash ⚠️ 	at org.enso.runtime/org.enso.interpreter.runtime.error.PanicException.getMessage(PanicException.java:76)
 INFO ide_ci::program::command: bash ⚠️ 	at org.enso.runtime/org.enso.interpreter.runtime.error.PanicException.toString(PanicException.java:106)
 INFO ide_ci::program::command: bash ⚠️ 	at java.base/java.lang.Throwable.<init>(Throwable.java:319)
 INFO ide_ci::program::command: bash ⚠️ 	at java.base/java.lang.Exception.<init>(Exception.java:103)
 INFO ide_ci::program::command: bash ⚠️ 	at java.base/java.io.IOException.<init>(IOException.java:98)
 INFO ide_ci::program::command: bash ⚠️ 	at org.enso.runner/org.enso.runner.Main.withProfiling(Main.java:1217)
 INFO ide_ci::program::command: bash ⚠️ 	at org.enso.runner/org.enso.runner.Main.launch(Main.java:1462)
 INFO ide_ci::program::command: bash ⚠️ 	at org.enso.runner/org.enso.runner.Main.launch(Main.java:1414)
 INFO ide_ci::program::command: bash ⚠️ 	at org.enso.runner/org.enso.runner.Main.main(Main.java:1031)
 INFO ide_ci::program::command: bash ⚠️ Caused by: java.lang.AssertionError: No polyglot context is entered. A language or context reference must not be used if there is no polyglot context entered.
 INFO ide_ci::program::command: bash ⚠️ 	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotFastThreadLocals.assertValidGet(PolyglotFastThreadLocals.java:481)
 INFO ide_ci::program::command: bash ⚠️ 	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotFastThreadLocals$ContextReferenceImpl.get(PolyglotFastThreadLocals.java:513)
 INFO ide_ci::program::command: bash ⚠️ 	at org.enso.runtime/org.enso.interpreter.runtime.EnsoContext.get(EnsoContext.java:247)
 INFO ide_ci::program::command: bash ⚠️ 	at org.enso.runtime/org.enso.interpreter.runtime.error.PanicException.computeMessage(PanicException.java:91)
 INFO ide_ci::program::command: bash ⚠️ 	... 9 more
 ```
Source https://github.com/enso-org/enso/actions/runs/11036714355/job/30655819392?pr=10823#step:7:2605
Happens randomly on various jobs. The above represents an already expanded debug info.

**Comment by JaroslavTulach** [comment] 2024-09-26 06:50
Duplicate of[#11127

**Closed as not planned by JaroslavTulach** 2024-09-26 06:50 UTC
Labels: -compiler

**Comment by hubertp** [comment] 2024-09-26 06:52
Thanks, looks like my search skills failed me.
