### ISSUE TITLE
Using wasm `drop` method results in warnings flood

### ISSUE THREAD

**Issue by PabloBuchu** [enso-org/enso#6505] opened 2023-05-02 12:15 UTC
This is an issue to fix leftovers after implementing `wasm.drop` method. Original problem was rised during QAing https://github.com/enso-org/enso/pull/6365#issuecomment-1521870772

Steps to reproduce:
1. Open Enso with `-debug.dev-tools` flag
2. Navigate to console pane
3. Type `ensoglApp.wasm.drop()`
4. Warnings will flood both console and terminal

https://drive.google.com/file/d/1Oy3-D5JGYy4PbJhYAXYXB3Ouuks_zL45/view?usp=share_link

**Comment by wdanilo** [comment] 2023-05-03 14:38
This is more serious than it looks. If we are still trying to render after the drop, when Pawel will create a new project after the drop and re-initialize the app, we can have WebGL errors in the new instance because of that.

**Comment by xvcgreg** [comment] 2023-06-26 12:41
@farmaazon, unfortunately, @PabloBuchu can still observe the regression here

**Comment by farmaazon** [comment] 2023-06-26 14:09
@xvcgreg what do you mean? Do you have any additional info?

**Comment by xvcgreg** [comment] 2023-06-26 14:13
@farmaazon just a direct message from @PabloBuchu that he can observe the problem still - please contact him directly as he has observed the issue.

**Comment by wdanilo** [comment] 2023-06-26 14:14
@PabloBuchu should post here the details probably.

**Comment by PabloBuchu** [comment] 2023-06-26 14:29
@farmaazon sorry was to fast to reopen.. I can't know reproduce it.. Normal drop works fine as intendent, but couple of times I got framebuffer warnings again.

Closing for now

cc @wdanilo @xvcgreg

**Comment by PabloBuchu** [comment] 2023-07-04 07:58
@farmaazon is this related to this bug or is it because my project failed for some other problems? When I closed the project I got a lot 
`[90352:0704/095711.010502:ERROR:CONSOLE(6)] "console.assert", source: devtools://devtools/bundled/panels/console/console.js (6)`

and 

`GL_INVALID_FRAMEBUFFER_OPERATION: Framebuffer is incomplete: Attachment has zero size.` errors.


https://github.com/enso-org/enso/assets/2855109/1d79125e-dcc7-4080-9aea-598234f6a138

**Comment by farmaazon** [comment] 2023-07-04 09:08
I don't know where "console.assert" messages come from, but the warnings suggest there is still some rendering done, so probably it's somehow relevant.

**Comment by jdunkerley** [comment] 2023-08-30 09:29
Closing as wont be fixed given VueJS move.

**Closed as not planned by jdunkerley** 2023-08-30 09:29 UTC
Labels: p-high, --bug
