### ISSUE TITLE
Preview Vizualisations when holding down CTRL/CMD

### ISSUE THREAD

**Issue by AdRiley** [enso-org/enso#10092] opened 2024-05-27 08:55 UTC
As a user I would like a way to quickly look at visualisations across a number of components.

When I am holding the CTRL/CMD key and hovering a component the visualisation should temporarily open.
The z-order needs to make the Viz on top.

**Comment by farmaazon** [comment] 2024-05-27 09:36
Duplicate of #8533

**Closed as not planned** 2024-05-27 09:36 UTC
Labels: s-duplicate, p-medium, x-new-feature, -gui
