### ISSUE TITLE
Wrong suggested arguments displayed on a node if a named argument is used not in its own position

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5507] opened 2023-02-05 23:07 UTC
This task is automatically imported from the old Task Issue Board and it was originally created by Radosław Waśko.
Original issue is [here](https://www.pivotaltracker.com/story/show/181503011).
<hr />

### Steps to reproduce
1. Create the following function:
    ```
    foo arg1 arg2=42 arg3="bar" =
        arg1+arg2.to_text+arg3
    ```
2. Create a node `here.foo "a" arg3="baz"` and see what it looks like.
3. Look at the graphical representation.

### Expected

The node should contain a greyed out `arg2` allowing to provide the last missing (though defaulted) argument.

### Actual

The node contains one more expected argument - but its name is `arg3` - the argument from the last position, even though because of the named argument application, the `arg3` is already provided (so the suggestion would duplicate it) and the actualy missing argument is arg2.

See the picture attached in the comment.

## Comments:
 (Radosław Waśko - Mar 8, 2022)
<hr />
Interestingly though - when I connect something to this greyed out port with name `arg3`, the actual behaviour (as illustrated on the attached image) is that the argument `arg2` gets applied.

 (Radosław Waśko - Mar 8, 2022)
<hr />

**Comment by farmaazon** [comment] 2023-02-21 13:10
@Frizi I heard you are working on this? Am I right? Is this a duplicate of some other task?

**Comment by Frizi** [comment] 2023-02-21 13:15
Yes, this is basically a duplicate of #5083

**Closed as completed** 2023-02-21 13:17 UTC
Labels: s-duplicate, d-intermediate, p-high, --bug
