### ISSUE TITLE
Cannot convert Column to Column

### ISSUE THREAD

**Issue by GregoryTravis** [enso-org/enso#8551] opened 2023-12-14 19:28 UTC
I am getting this error in my [Map_Error WIP](https://github.com/enso-org/enso/tree/8371-column-conversion):

```
    - [FAILED] should report missing columns [85ms]
        Reason: An unexpected panic was thrown: (Unsupported_Argument_Types.Error [[org.enso.table.data.table.Column]] Cannot convert 'org.enso.table.data.table.Column@5cbebfba'(language: Java, type: org.enso.table.data.table.Column) to Java type 'org.enso.table.data.table.Column': Unsupported target type.)
        at <enso> Table.type.new<arg-1>(/Users/gmt/dev/enso/enso/built-distribution/enso-engine-0.0.0-dev-macos-aarch64/enso-0.0.0-dev/lib/Standard/Table/0.0.0-dev/src/Data/Table.enso:125:26-44)
        at <enso> Table.type.new<arg-1>(/Users/gmt/dev/enso/enso/built-distribution/enso-engine-0.0.0-dev-macos-aarch64/enso-0.0.0-dev/lib/Standard/Table/0.0.0-dev/src/Data/Table.enso:125:13-45)
        at <enso> Panic.catch(Internal)
```

Occurring in [this test](https://github.com/enso-org/enso/blob/8371-column-conversion/test/Table_Tests/src/Common_Table_Operations/Conversion_Spec.enso#L536)

The panic itself happens [on constructing a Java Table](https://github.com/enso-org/enso/blob/8371-column-conversion/distribution/lib/Standard/Table/0.0.0-dev/src/Data/Table.enso#L125), and _only happens when there is a warning attached to `cols`._

Currently the branch is at revision https://github.com/enso-org/enso/commit/ee92e19ee629678619f03ab738272d544b4281f2

**Comment by JaroslavTulach** [comment] 2023-12-18 05:31
Looks like this has the same cause as #8552 - with following changes (and on top of latest develop that includes #5585):
```diff
enso$ git diff
diff --cc engine/runtime/src/main/java/org/enso/interpreter/runtime/error/WithWarnings.java
index 2bbe92e555,a0318b3254..0000000000
--- engine/runtime/src/main/java/org/enso/interpreter/runtime/error/WithWarnings.java
+++ engine/runtime/src/main/java/org/enso/interpreter/runtime/error/WithWarnings.java
@@@ -57,18 -57,13 +59,19 @@@ public final class WithWarnings impleme
     * @param value value to be wrapped in warnings
     * @param maxWarnings maximal number of warnings allowed to be attached to the value
     * @param warnings warnings originally attached to a value
 -   * @param limitReached if `true`, indicates that `warnings` have already been limited for a custom-method, `false` otherwise
 +   * @param limitReached if `true`, indicates that `warnings` have already been limited for a
 +   *     custom-method, `false` otherwise
     * @param additionalWarnings additional warnings to be appended to the list of `warnings`
     */
 -  private WithWarnings(Object value, int maxWarnings, EconomicSet<Warning> warnings, boolean limitReached, Warning... additionalWarnings) {
 +  private WithWarnings(
 +      Object value,
 +      int maxWarnings,
 +      EconomicSet<Warning> warnings,
 +      boolean limitReached,
 +      Warning... additionalWarnings) {
      assert !(value instanceof WithWarnings);
      this.warnings = cloneSetAndAppend(maxWarnings, warnings, additionalWarnings);
+     assert this.warnings.size() > 0;
      this.value = value;
      this.limitReached = limitReached || this.warnings.size() >= maxWarnings;
      this.maxWarnings = maxWarnings;
```
I am getting again an `AssertError` indicating there is an allocation of `WithWarnings` without any warning:
```
enso$ JAVA_OPTS=-ea ./built-distribution/enso-engine-0.0.0-dev-linux-amd64/enso-0.0.0-dev/bin/enso --in-project test/Table_Tests --run test/Table_Tests/src/Common_Table_Operations/Conversion_Spec.enso

Execution finished with an error: java.lang.AssertionError
        at <java> org.enso.runtime/org.enso.interpreter.runtime.error.WithWarnings.wrap(WithWarnings.java:86)
        at <java> org.enso.runtime/org.enso.interpreter.runtime.data.vector.Array.readArrayElement(Array.java:110)
        at <java> org.enso.runtime/org.enso.interpreter.runtime.data.vector.ArrayGen$InteropLibraryExports$Cached.readArrayElement(ArrayGen.java:124)
        at <java> org.graalvm.truffle/com.oracle.truffle.api.interop.InteropLibrary$Asserts.readArrayElement(InteropLibrary.java:3996)
        at <java> org.graalvm.truffle/com.oracle.truffle.api.interop.InteropLibraryGen$CachedDispatch.readArrayElement(InteropLibraryGen.java:8819)
        at <java> org.enso.runtime/org.enso.interpreter.runtime.data.vector.Vector$Generic.readArrayElement(Vector.java:228)
        at <java> org.enso.runtime/org.enso.interpreter.runtime.data.vector.ArrayLikeAtNode.vectorAt(ArrayLikeAtNode.java:63)
        at <java> org.enso.runtime/org.enso.interpreter.runtime.data.vector.ArrayLikeAtNodeGen.executeAt(ArrayLikeAtNodeGen.java:86)
        at <java> org.enso.runtime/org.enso.interpreter.node.expression.builtin.immutable.AtVectorNode.execute(AtVectorNode.java:23)
        at <java> org.enso.runtime/org.enso.interpreter.node.expression.builtin.immutable.AtVectorMethodGen.handleExecute(AtVectorMethodGen.java:171)
        at <java> org.enso.runtime/org.enso.interpreter.node.expression.builtin.immutable.AtVectorMethodGen$1Inlineable.call(AtVectorMethodGen.java:91)
        at <java> ....
        at <enso> Function.<<<arg-0>(/home/devel/NetBeansProjects/enso/enso/built-distribution/enso-engine-0.0.0-dev-linux-amd64/enso-0.0.0-dev/lib/Standard/Base/0.0.0-dev/src/Function.enso:46:32-37)
        at <enso> Function.<<(/home/devel/NetBeansProjects/enso/enso/built-distribution/enso-engine-0.0.0-dev-linux-amd64/enso-0.0.0-dev/lib/Standard/Base/0.0.0-dev/src/Function.enso:46:26-38)
        at <enso> wrapped_function(/home/devel/NetBeansProjects/enso/enso/built-distribution/enso-engine-0.0.0-dev-linux-amd64/enso-0.0.0-dev/lib/Standard/Base/0.0.0-dev/src/Internal/Array_Like_Helpers.enso:69:18-27)
        at <enso> Array_Like_Helpers.vector_from_function(Internal)
        at <enso> Array_Like_Helpers.vector_from_function(/home/devel/NetBeansProjects/enso/enso/built-distribution/enso-engine-0.0.0-dev-linux-amd64/enso-0.0.0-dev/lib/Standard/Base/0.0.0-dev/src/Internal/Array_Like_Helpers.enso:87:15-68)
        at <enso> Vector.map(/home/devel/NetBeansProjects/enso/enso/built-distribution/enso-engine-0.0.0-dev-linux-amd64/enso-0.0.0-dev/lib/Standard/Base/0.0.0-dev/src/Data/Vector.enso:614:9-93)
        at <enso> Table.type.new(/home/devel/NetBeansProjects/enso/enso/built-distribution/enso-engine-0.0.0-dev-linux-amd64/enso-0.0.0-dev/lib/Standard/Table/0.0.0-dev/src/Data/Table.enso:106-112)
        at <enso> Table.parse<arg-1>(/home/devel/NetBeansProjects/enso/enso/built-distribution/enso-engine-0.0.0-dev-linux-amd64/enso-0.0.0-dev/lib/Standard/Table/0.0.0-dev/src/Data/Table.enso:981:13-33)
        at <enso> case_branch(/home/devel/NetBeansProjects/enso/enso/built-distribution/enso-engine-0.0.0-dev-linux-amd64/enso-0.0.0-dev/lib/Standard/Base/0.0.0-dev/src/Errors/Problem_Behavior.enso:85-86)
        at <enso> Problem_Behavior.attach_problems_before(/home/devel/NetBeansProjects/enso/enso/built-distribution/enso-engine-0.0.0-dev-linux-amd64/enso-0.0.0-dev/lib/Standard/Base/0.0.0-dev/src/Errors/Problem_Behavior.enso:81-89)

```

**Comment by JaroslavTulach** [comment] 2023-12-18 05:31
Closing as duplicate of #8552

**Closed as completed by JaroslavTulach** 2023-12-18 05:31 UTC
Labels: p-low, --bug, -compiler
