### ISSUE TITLE
Nodes disappear on CB open with Tab key

### ISSUE THREAD

**Issue by xvcgreg** [enso-org/enso#6193] opened 2023-04-04 08:16 UTC
### What type of issue is this?

Permanent – Ocurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [x] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

When I press ``Tab`` key nodes in the graph editor disappear.

https://user-images.githubusercontent.com/108271897/229730376-bd7c9b41-9e25-4613-a905-32443448bc22.mp4

Workaround: zoom out then back in - nodes appear back

### Expected behavior

On ``Tab`` press CB opens and nodes are still visible

### How we can reproduce it?

1. press ``Tab``
2. observe nodes disappear (visualizations attached to nodes stay visible)

### Enso Version

Nightly Release # 862

### Browser or standalone distribution

Standalone distribution

### Browser Version or standalone distribution

standalone

### Operating System

Windows

### Operating System Version

11pro 22H2

### Hardware you are using

12th Gen Intel(R) Core(TM) i9-12900HK / RTX3060 Laptop

**Comment by xvcgreg** [comment] 2023-04-04 08:18
[20230404 - Nodes disappear on CB open.txt](https://github.com/enso-org/enso/files/11146243/20230404.-.Nodes.disappear.on.CB.open.txt)

log

**Comment by wdanilo** [comment] 2023-04-04 08:22
Greg, a few things:
1. I don't understand the video - this video starts with no nodes on stage. What happened there?
2. You did not checked "Yes, I can't use Enso because of this issue." – how can you use Enso without nodes visible?
3. You did not checked "Yes, previous version of Enso did not have this issue." – if so, what version of Enso did you notice this issue in? This is a very important information that would help debugging.

**Comment by wdanilo** [comment] 2023-04-04 08:25
Also, in [another issue](https://github.com/enso-org/enso/issues/6158#issuecomment-1495534917) you mentioned that nodes are getting visible again after zooming out and in - is this correct? If so, why this information is not provided here? It is a very important information that could save tons of time while debugging this issue.

**Comment by xvcgreg** [comment] 2023-04-04 08:45
@wdanilo yes you are right 
ad.1 I was checking the regressions on the most recent nightly build and suddenly discovered a new one while writing a reply to @farmaazon 
ad.2 I didn't mark it as preventive because there's a workaround with zooming out and back in to redraw the nodes. It's very visible in the attached video.
ad.3 Regression occurred somewhere between builds: Nightly Release https://github.com/enso-org/enso/issues/842 and one marked in this bug.

**Comment by wdanilo** [comment] 2023-04-04 10:39
1. Greg, could you fix the issue description, so when someone is reading it, they would understand what happens there?
2. This info is missing from the description of the issue.
3. -
4. Regarding the info that zooming in and out fixes this issue, this info is still missing from the issue description.

**Comment by 4e6** [comment] 2023-04-08 07:05
Probably Windows related. Can't repro on Linux.

**Comment by vitvakatu** [comment] 2023-04-13 09:05
Can't reproduce on MacOS

**Comment by farmaazon** [comment] 2023-04-24 08:53
My interpretation of what I see in the video:

1. The nodes are always there, only scrolled down. The visualization are off their positions as in #6158 
2. When you zoom out, the visualizations are getting near their original positions. That's why zooming out and in seems to fix the issue.

**Comment by farmaazon** [comment] 2023-04-24 09:29
Also, cannot reproduce it anymore on Windows. Closing for now.

**Closed as not planned** 2023-04-24 09:30 UTC
Labels: s-no-repro, p-medium, d-unknown, --bug, --regression
