### ISSUE TITLE
Autogenerated code for type error reporting in builtin methods is wrong

### ISSUE THREAD

**Issue by kustosz** [enso-org/enso#3226] opened 2022-01-14 15:05 UTC
### General Summary
Autogenerated code for type error reporting returns misleading results.

### Steps to Reproduce
Run the following code:
```
import Standard.Builtins

main = Builtins.Meta.get_unresolved_symbol_name 123
```

### Expected Result
An error saying 
```
Type error: expected `arg1` to be an Unresolved_Symbol, but got 123 (Integer)
```

### Actual Result
An error saying 
```
Type error: expected `arg1` to be Integer, but got 123 (Integer)
```

### Enso Version
```
Enso Compiler and Runtime
Version:    0.2.32-SNAPSHOT
Built with: scala-2.13.6 for GraalVM 21.1.0
Built from: compiler/wip/eak/conversions* @ 1821f21232d5314469566c5500030c35f5e8d99f
Running on: OpenJDK 64-Bit Server VM, GraalVM Community, JDK 11.0.11+8-jvmci-21.1-b05
            Mac OS X 10.16 (x86_64)
```

**Comment by radeusgd** [comment] 2022-01-19 13:14
I think this is a duplicate of https://www.pivotaltracker.com/story/show/180855429

**Comment by radeusgd** [comment] 2022-03-23 10:54
This is also a duplicate of https://github.com/enso-org/enso/issues/1539
Seems I am bumping into this error every year :D

**Closed as completed** 2024-12-05 10:15 UTC
Labels: --bug, -libs
