### ISSUE TITLE
Applying edits fails from time to time.

### ISSUE THREAD

**Issue by vitvakatu** [enso-org/enso#7978] opened 2023-10-05 10:08 UTC
### What type of issue is this?

Intermittent – Occurring irregularly

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [X] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

I was working on my branch https://github.com/enso-org/enso/pull/7779 and noticed that sometimes the engine stops responding.

Here are the logs: https://gist.github.com/vitvakatu/e44a3e410b29c38cfa520f8e80206e52

I couldn't spot any pattern. The issue seems to occur randomly. It happens both on my branch and on develop, and I was only trying engine `9.30`.

### Expected behaviour

No errors when editing nodes.

### Enso Version

0228022809cb2f5a11b9ae7e8b2db4497e2c103b

### Browser or standalone distribution

Standalone distribution (local project)

### Browser Version or standalone distribution

standalone

### Operating System

MacOS

**Comment by hubertp** [comment] 2023-10-19 07:57
I added some more info so that we have a better idea what is happening from the logs. So far I was neither able to reproduce nor come up on my own with how is that even possible just by looking at the code.

**Comment by hubertp** [comment] 2023-10-23 12:51
As discussed, closing for now since couldn't reproduce. Added more info so that next time we get a better chance of reproducing.

**Closed as completed by hubertp** 2023-10-23 12:51 UTC
Labels: --bug, -language-server
