### ISSUE TITLE
Component Browser Selection quickly reverts to previous one after pressing arrow keys

### ISSUE THREAD

**Issue by radeusgd** [enso-org/enso#7215] opened 2023-07-05 10:58 UTC
I have trouble using the component browser using the arrow keys which is best illustrated on this video (in the lower right you can see the keyboard keys that I'm pressing):

https://github.com/enso-org/enso/assets/1436948/c1c5bb72-a460-4564-aa73-590f50bf61ef

As you can see, I'm pressing the Left arrow to go to the left column. But quickly after that, I'm reverted back to the right column. I retry a few times. Usually on the second try I can 'stay' in the left column and browse it. But when I go back to the right column (using Right arrow) and then go Left again - it again reverts back to the right column.

The gist is - the component browser selection "jumps around" with no input from me and reverts my selections - that makes it harder to browse it and is really annoying.

**Comment by vitvakatu** [comment] 2023-07-05 11:21
Looks like duplicate of https://github.com/enso-org/enso/issues/6124

**Closed as not planned by vitvakatu** 2023-07-05 11:21 UTC
Labels: s-duplicate, --bug
