### ISSUE TITLE
In cloud environment, after showing nodes Enso goes to spinner and crashes

### ISSUE THREAD

**Issue by xvcgreg** [enso-org/enso#7402] opened 2023-07-26 12:04 UTC
### What type of issue is this?

Transient – Occurring only once

### Is this issue blocking you from using Enso?

- [X] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [X] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

In the cloud environment I have created new project from examples (KMeans)
After spinning the environment, Enso showed me nodes for a split second then showed me the spinner and after it disappeared it crushed.
![image](https://github.com/enso-org/enso/assets/108271897/7541d8e3-6860-4168-a535-14b6d5c6df34)

### Expected behaviour

Nodes being loaded and visualisations shown.

### Logs

[debug] [2023-07-26T11:48:54.494Z] [org.enso.jsonrpc.MessageHandlerSupervisor] started (org.enso.jsonrpc.MessageHandlerSupervisor@6cab1eff)
[debug] [2023-07-26T11:48:54.495Z] [org.enso.jsonrpc.MessageHandlerSupervisor] now supervising Actor[akka://language-server/user/message-handler-supervisor-aac11109-46cc-47d9-a0f3-533ef5e47afe/message-handler-d7dcbd45-f005-43a2-beba-808e90ccbcde#-1746552398]
[debug] [2023-07-26T11:48:54.495Z] [org.enso.jsonrpc.MessageHandler] started (org.enso.jsonrpc.MessageHandler@6cba9bbb)
[debug] [2023-07-26T11:48:54.495Z] [org.enso.languageserver.protocol.json.JsonConnectionController] started (org.enso.languageserver.protocol.json.JsonConnectionController@44bd3654)
[debug] [2023-07-26T11:48:54.496Z] [org.enso.jsonrpc.MessageHandlerSupervisor] now watched by Actor[akka://language-server/system/Materializers/StreamSupervisor-0/$$gb#-407047136]
[debug] [2023-07-26T11:48:54.496Z] [org.enso.projectmanager.infrastructure.languageserver.HeartbeatSession] Sending ping message to Socket(127.0.0.1,53244).
[trace] [2023-07-26T11:48:54.497Z] [org.enso.jsonrpc.JsonRpcServer] Received text message:
{
   "jsonrpc": "2.0",
   "method": "heartbeat/ping",
   "id": "6e24cd9d-e320-437a-b4db-9cab692853fe",
   "params": null
}
.
[debug] [2023-07-26T11:48:54.497Z] [org.enso.languageserver.protocol.json.JsonConnectionController] now supervising Actor[akka://language-server/user/json-connection-controller-d7dcbd45-f005-43a2-beba-808e90ccbcde/$a#1704318388]
[debug] [2023-07-26T11:48:54.497Z] [org.enso.languageserver.requesthandler.monitoring.PingHandler] started (org.enso.languageserver.requesthandler.monitoring.PingHandler@90cf4b2)
[trace] [2023-07-26T11:48:54.497Z] [org.enso.jsonrpc.JsonRpcServer] Sent text message {"jsonrpc":"2.0","id":"6e24cd9d-e320-437a-b4db-9cab692853fe","result":null}.
[debug] [2023-07-26T11:48:54.497Z] [org.enso.languageserver.requesthandler.monitoring.PingHandler] stopped
[debug] [2023-07-26T11:48:54.499Z] [org.enso.projectmanager.infrastructure.languageserver.HeartbeatSession] Received correct pong message from Socket(127.0.0.1,53244).
[debug] [2023-07-26T11:48:54.499Z] [org.enso.jsonrpc.MessageHandler] stopped
[debug] [2023-07-26T11:48:54.499Z] [org.enso.languageserver.protocol.json.JsonConnectionController] stopped
[debug] [2023-07-26T11:48:54.499Z] [org.enso.jsonrpc.MessageHandlerSupervisor] no longer watched by Actor[akka://language-server/system/Materializers/StreamSupervisor-0/$$gb#-407047136]
[debug] [2023-07-26T11:49:00.751Z] [org.enso.projectmanager.infrastructure.http.FanOutReceiver] no longer watched by Actor[akka://project-manager/system/Materializers/StreamSupervisor-1/$$Fb#-1023817669]
[debug] [2023-07-26T11:49:00.751Z] [org.enso.projectmanager.infrastructure.languageserver.HeartbeatSession] stopped
[info] [2023-07-26T11:49:08.12Z] [org.enso.projectmanager.protocol.ClientController] Client disconnected from the Project Manager [8c1e7ce4-abb1-4226-8c06-237e03a11dcb]
[debug] [2023-07-26T11:49:08.12Z] [org.enso.jsonrpc.MessageHandler] stopped
[debug] [2023-07-26T11:49:08.12Z] [org.enso.jsonrpc.MessageHandlerSupervisor] no longer watched by Actor[akka://project-manager/system/Materializers/StreamSupervisor-1/$$d#178258740]
[debug] [2023-07-26T11:49:08.12Z] [org.enso.projectmanager.protocol.ClientController] stopped
[trace] [2023-07-26T11:49:08.12Z] [org.enso.projectmanager.infrastructure.languageserver.LanguageServerController] received handled ClientDisconnected(8c1e7ce4-abb1-4226-8c06-237e03a11dcb) from Actor[akka://project-manager/deadLetters] in state supervising
[debug] [2023-07-26T11:49:08.12Z] [org.enso.projectmanager.infrastructure.languageserver.LanguageServerController] Delaying shutdown for project a91cb8fb-7e74-4383-b0d1-c376809237c6.
[info] [2023-07-26T11:49:08.145Z] [org.enso.projectmanager.boot.ProjectManager$] Stopping server...
[debug] [2023-07-26T11:49:08.145Z] [org.enso.projectmanager.infrastructure.languageserver.LanguageServerRegistry] now supervising Actor[akka://project-manager/user/language-server-registry/language-server-killer#640333691]
[debug] [2023-07-26T11:49:08.146Z] [org.enso.projectmanager.infrastructure.languageserver.LanguageServerKiller] started (org.enso.projectmanager.infrastructure.languageserver.LanguageServerKiller@76a67c47)
[info] [2023-07-26T11:49:08.146Z] [org.enso.projectmanager.infrastructure.languageserver.LanguageServerKiller] Killing all servers [Map(a91cb8fb-7e74-4383-b0d1-c376809237c6 -> Actor[akka://project-manager/user/language-server-registry/language-server-controller-a91cb8fb-7e74-4383-b0d1-c376809237c6#-1906897998])].
[debug] [2023-07-26T11:49:08.146Z] [org.enso.projectmanager.infrastructure.languageserver.LanguageServerController] now watched by Actor[akka://project-manager/user/language-server-registry/language-server-killer#640333691]
[trace] [2023-07-26T11:49:08.146Z] [org.enso.projectmanager.infrastructure.languageserver.LanguageServerController] received handled ShutDownServer from Actor[akka://project-manager/user/language-server-registry/language-server-killer#640333691] in state supervising
[debug] [2023-07-26T11:49:08.146Z] [org.enso.projectmanager.infrastructure.languageserver.LanguageServerController] Shutting down a language server for project a91cb8fb-7e74-4383-b0d1-c376809237c6.
[trace] [2023-07-26T11:49:08.146Z] [org.enso.projectmanager.infrastructure.languageserver.LanguageServerBootLoader] received handled GracefulStop from Actor[akka://project-manager/user/language-server-registry/language-server-controller-a91cb8fb-7e74-4383-b0d1-c376809237c6#-1906897998] in state running
[debug] [2023-07-26T11:49:08.146Z] [org.enso.projectmanager.infrastructure.languageserver.LanguageServerSupervisor] stopped
[info] [2023-07-26T11:49:08.15Z] [org.enso.languageserver.runtime.RuntimeKiller] Shutting down the runtime server [Actor[akka://language-server/user/runtime-connector#1795163173]].
[trace] [2023-07-26T11:49:08.15Z] [org.enso.languageserver.runtime.RuntimeConnector] received handled Request(Some(805ca53f-2bae-48f5-b9b5-300a8b386b1c),ShutDownRuntimeServer()) from Actor[akka://language-server/user/runtime-context#1466467305]
[trace] [2023-07-26T11:49:08.158Z] [org.enso.languageserver.runtime.RuntimeConnector] received handled MessageFromRuntime(Response(Some(805ca53f-2bae-48f5-b9b5-300a8b386b1c),RuntimeServerShutDown())) from Actor[akka://language-server/deadLetters]
[info] [2023-07-26T11:49:08.158Z] [org.enso.languageserver.runtime.RuntimeKiller] Shutting down the Truffle context [org.graalvm.polyglot.Context@7318daf8]. Attempt #1.
[debug] [2023-07-26T11:49:08.269Z] [enso.org.enso.compiler.SerializationManager] Serialization manager has been shut down.
[trace] [2023-07-26T11:49:08.27Z] [org.enso.languageserver.runtime.RuntimeConnector] received handled Destroy from Actor[akka://language-server/deadLetters]
[debug] [2023-07-26T11:49:08.27Z] [org.enso.languageserver.runtime.RuntimeConnector] stopped
[debug] [2023-07-26T11:49:08.271Z] [org.enso.languageserver.runtime.RuntimeKiller] stopped
[info] [2023-07-26T11:49:08.271Z] [org.enso.languageserver.boot.LanguageServerComponent] Terminated truffle context.
[info] [2023-07-26T11:49:08.277Z] [org.enso.languageserver.boot.LanguageServerComponent] Terminated json connections.
[info] [2023-07-26T11:49:08.277Z] [org.enso.languageserver.boot.LanguageServerComponent] Terminated binary connections.
[info] [2023-07-26T11:49:08.304Z] [akka.actor.CoordinatedShutdown] Running CoordinatedShutdown with reason [ActorSystemTerminateReason]
[debug] [2023-07-26T11:49:08.311Z] [org.enso.languageserver.monitoring.IdlenessMonitor] stopped
[debug] [2023-07-26T11:49:08.311Z] [org.enso.languageserver.capability.CapabilityRouter] stopped
[debug] [2023-07-26T11:49:08.311Z] [org.enso.languageserver.filemanager.ContentRootManagerActor] stopped
[debug] [2023-07-26T11:49:08.311Z] [org.enso.languageserver.libraries.LocalLibraryManager] stopped
[debug] [2023-07-26T11:49:08.311Z] [org.enso.languageserver.text.BufferRegistry] stopped
[debug] [2023-07-26T11:49:08.311Z] [org.enso.jsonrpc.MessageHandlerSupervisor] stopped
[debug] [2023-07-26T11:49:08.311Z] [org.enso.jsonrpc.MessageHandlerSupervisor] stopped
[debug] [2023-07-26T11:49:08.311Z] [org.enso.jsonrpc.MessageHandlerSupervisor] stopped
[debug] [2023-07-26T11:49:08.312Z] [org.enso.lockmanager.server.LockManagerService] stopped
[debug] [2023-07-26T11:49:08.312Z] [org.enso.jsonrpc.MessageHandlerSupervisor] stopped
[debug] [2023-07-26T11:49:08.312Z] [org.enso.jsonrpc.MessageHandlerSupervisor] stopped
[debug] [2023-07-26T11:49:08.312Z] [org.enso.jsonrpc.MessageHandlerSupervisor] stopped
[debug] [2023-07-26T11:49:08.312Z] [org.enso.languageserver.filemanager.FileManager] no longer watched by Actor[akka://language-server/user/file-manager#-1543886833]
[debug] [2023-07-26T11:49:08.312Z] [org.enso.languageserver.filemanager.PathWatcher] no longer watched by Actor[akka://language-server/user/file-event-registry#-745191129]
[debug] [2023-07-26T11:49:08.312Z] [org.enso.languageserver.filemanager.FileManager] no longer watched by Actor[akka://language-server/user/file-manager#-1543886833]
[debug] [2023-07-26T11:49:08.312Z] [org.enso.jsonrpc.MessageHandlerSupervisor] stopped
[debug] [2023-07-26T11:49:08.312Z] [org.enso.jsonrpc.MessageHandlerSupervisor] stopped
[debug] [2023-07-26T11:49:08.312Z] [org.enso.languageserver.runtime.ContextEventsListener] stopped
[debug] [2023-07-26T11:49:08.312Z] [org.enso.jsonrpc.MessageHandlerSupervisor] stopped
[debug] [2023-07-26T11:49:08.312Z] [org.enso.jsonrpc.MessageHandlerSupervisor] stopped
[debug] [2023-07-26T11:49:08.312Z] [org.enso.jsonrpc.MessageHandlerSupervisor] stopped
[debug] [2023-07-26T11:49:08.312Z] [org.enso.languageserver.filemanager.FileManager] no longer watched by Actor[akka://language-server/user/file-manager#-1543886833]
[debug] [2023-07-26T11:49:08.312Z] [org.enso.languageserver.filemanager.FileManager] no longer watched by Actor[akka://language-server/user/file-manager#-1543886833]
[debug] [2023-07-26T11:49:08.312Z] [org.enso.jsonrpc.MessageHandlerSupervisor] stopped
[debug] [2023-07-26T11:49:08.312Z] [org.enso.languageserver.filemanager.FileManager] no longer watched by Actor[akka://language-server/user/file-manager#-1543886833]
[debug] [2023-07-26T11:49:08.312Z] [org.enso.jsonrpc.MessageHandlerSupervisor] stopped
[debug] [2023-07-26T11:49:08.312Z] [org.enso.jsonrpc.MessageHandlerSupervisor] stopped
[debug] [2023-07-26T11:49:08.312Z] [org.enso.jsonrpc.MessageHandlerSupervisor] stopped
[debug] [2023-07-26T11:49:08.312Z] [org.enso.jsonrpc.MessageHandlerSupervisor] stopped
[debug] [2023-07-26T11:49:08.312Z] [org.enso.languageserver.filemanager.FileManager] no longer watched by Actor[akka://language-server/user/file-manager#-1543886833]
[debug] [2023-07-26T11:49:08.312Z] [org.enso.languageserver.filemanager.FileManager] no longer watched by Actor[akka://language-server/user/file-manager#-1543886833]
[debug] [2023-07-26T11:49:08.312Z] [org.enso.jsonrpc.MessageHandlerSupervisor] stopped
[debug] [2023-07-26T11:49:08.312Z] [org.enso.languageserver.filemanager.FileManager] no longer watched by Actor[akka://language-server/user/file-manager#-1543886833]
[debug] [2023-07-26T11:49:08.312Z] [org.enso.languageserver.filemanager.FileManager] no longer watched by Actor[akka://language-server/user/file-manager#-1543886833]
[debug] [2023-07-26T11:49:08.312Z] [org.enso.languageserver.filemanager.FileManager] stopped
[debug] [2023-07-26T11:49:08.312Z] [org.enso.languageserver.filemanager.FileManager] no longer watched by Actor[akka://language-server/user/file-manager#-1543886833]
[debug] [2023-07-26T11:49:08.312Z] [org.enso.languageserver.filemanager.FileManager] no longer watched by Actor[akka://language-server/user/file-manager#-1543886833]
[debug] [2023-07-26T11:49:08.312Z] [org.enso.languageserver.filemanager.FileManager] no longer watched by Actor[akka://language-server/user/file-manager#-1543886833]
[debug] [2023-07-26T11:49:08.312Z] [org.enso.languageserver.filemanager.FileManager] stopped
[debug] [2023-07-26T11:49:08.312Z] [org.enso.languageserver.filemanager.FileManager] no longer watched by Actor[akka://language-server/user/file-manager#-1543886833]
[debug] [2023-07-26T11:49:08.312Z] [org.enso.languageserver.filemanager.FileManager] no longer watched by Actor[akka://language-server/user/file-manager#-1543886833]
[debug] [2023-07-26T11:49:08.312Z] [org.enso.languageserver.filemanager.FileManager] stopped
[debug] [2023-07-26T11:49:08.312Z] [org.enso.languageserver.filemanager.FileManager] no longer watched by Actor[akka://language-server/user/file-manager#-1543886833]
[debug] [2023-07-26T11:49:08.312Z] [org.enso.languageserver.filemanager.FileManager] stopped
[debug] [2023-07-26T11:49:08.312Z] [org.enso.languageserver.filemanager.FileManager] stopped
[debug] [2023-07-26T11:49:08.312Z] [org.enso.languageserver.filemanager.FileManager] no longer watched by Actor[akka://language-server/user/file-manager#-1543886833]
[debug] [2023-07-26T11:49:08.312Z] [org.enso.languageserver.filemanager.FileManager] stopped
[debug] [2023-07-26T11:49:08.312Z] [org.enso.languageserver.filemanager.FileManager] no longer watched by Actor[akka://language-server/user/file-manager#-1543886833]
[debug] [2023-07-26T11:49:08.312Z] [org.enso.languageserver.filemanager.FileManager] stopped
[debug] [2023-07-26T11:49:08.312Z] [org.enso.languageserver.filemanager.FileManager] stopped
[debug] [2023-07-26T11:49:08.312Z] [org.enso.languageserver.filemanager.FileManager] stopped
[debug] [2023-07-26T11:49:08.312Z] [org.enso.languageserver.filemanager.FileManager] stopped
[debug] [2023-07-26T11:49:08.312Z] [org.enso.jsonrpc.MessageHandlerSupervisor] stopped
[debug] [2023-07-26T11:49:08.312Z] [org.enso.languageserver.filemanager.FileManager] no longer watched by Actor[akka://language-server/user/file-manager#-1543886833]
[debug] [2023-07-26T11:49:08.312Z] [org.enso.languageserver.filemanager.FileManager] no longer watched by Actor[akka://language-server/user/file-manager#-1543886833]
[debug] [2023-07-26T11:49:08.312Z] [org.enso.languageserver.filemanager.FileManager] stopped
[debug] [2023-07-26T11:49:08.312Z] [org.enso.jsonrpc.MessageHandlerSupervisor] stopped
[debug] [2023-07-26T11:49:08.312Z] [org.enso.languageserver.filemanager.FileManager] stopped
[debug] [2023-07-26T11:49:08.312Z] [org.enso.languageserver.filemanager.FileManager] stopped
[debug] [2023-07-26T11:49:08.312Z] [org.enso.languageserver.filemanager.FileManager] stopped
[debug] [2023-07-26T11:49:08.312Z] [org.enso.languageserver.filemanager.FileManager] stopped
[debug] [2023-07-26T11:49:08.312Z] [org.enso.languageserver.filemanager.FileManager] stopped
[debug] [2023-07-26T11:49:08.312Z] [org.enso.languageserver.filemanager.FileManager] stopped
[debug] [2023-07-26T11:49:08.312Z] [org.enso.languageserver.filemanager.FileManager] no longer watched by Actor[akka://language-server/user/file-manager#-1543886833]
[debug] [2023-07-26T11:49:08.312Z] [org.enso.languageserver.filemanager.FileManager] stopped
[debug] [2023-07-26T11:49:08.312Z] [org.enso.languageserver.filemanager.FileManager] stopped
[debug] [2023-07-26T11:49:08.312Z] [org.enso.languageserver.filemanager.FileManager] stopped
[debug] [2023-07-26T11:49:08.312Z] [org.enso.jsonrpc.MessageHandlerSupervisor] stopped
[debug] [2023-07-26T11:49:08.312Z] [org.enso.jsonrpc.MessageHandlerSupervisor] stopped
[debug] [2023-07-26T11:49:08.312Z] [org.enso.jsonrpc.MessageHandlerSupervisor] stopped
[debug] [2023-07-26T11:49:08.312Z] [org.enso.languageserver.monitoring.ReadinessMonitor] stopped
[debug] [2023-07-26T11:49:08.312Z] [org.enso.languageserver.libraries.ProjectSettingsManager] stopped
[debug] [2023-07-26T11:49:08.312Z] [org.enso.languageserver.session.SessionRouter] stopped
[debug] [2023-07-26T11:49:08.312Z] [org.enso.languageserver.io.OutputRedirectionController] stopped
[debug] [2023-07-26T11:49:08.312Z] [org.enso.languageserver.search.SuggestionsHandler] stopped
[debug] [2023-07-26T11:49:08.312Z] [org.enso.languageserver.io.InputRedirectionController] stopped
[debug] [2023-07-26T11:49:08.312Z] [org.enso.languageserver.io.OutputRedirectionController] stopped
[debug] [2023-07-26T11:49:08.312Z] [org.enso.languageserver.vcsmanager.VcsManager] stopped
[debug] [2023-07-26T11:49:08.312Z] [org.enso.languageserver.runtime.ContextRegistry] stopping
[debug] [2023-07-26T11:49:08.312Z] [akka.routing.RouterPoolActor] stopping
[debug] [2023-07-26T11:49:08.312Z] [org.enso.languageserver.filemanager.ReceivesTreeUpdatesHandler] stopping
[debug] [2023-07-26T11:49:08.312Z] [org.enso.languageserver.runtime.ContextRegistry] stopped
[debug] [2023-07-26T11:49:08.313Z] [akka.routing.RouterPoolActor] stopped
[debug] [2023-07-26T11:49:08.314Z] [org.enso.languageserver.filemanager.PathWatcher] stopped
[debug] [2023-07-26T11:49:08.314Z] [org.enso.languageserver.filemanager.ReceivesTreeUpdatesHandler] stopped
[internal-logger-error] Server has disconnected, logging is falling back to stderr.
[internal-logger-error] One of the printers failed to write a message: akka.stream.StreamDetachedException: Stage with GraphStageLogic akka.stream.impl.QueueSource$$anon$1-queueSource stopped before async invocation was processed
[internal-logger-error] The dropped message was: [info] [2023-07-26T11:49:08.374Z] [org.enso.languageserver.boot.LanguageServerComponent] Terminated actor system.
[info] [2023-07-26T11:49:08.377Z] [org.enso.languageserver.boot.MainModule] Closed Language Server main module.
[info] [2023-07-26T11:49:08.377Z] [org.enso.languageserver.boot.LanguageServerComponent] Terminated main module.

### Enso Version

2023.7.26 nightly

### Browser or standalone distribution

Standalone distribution (cloud project)

### Browser Version or standalone distribution

standalone

### Operating System

Windows

### Operating System Version

Win11pro 22H2 22621.1848

### Hardware you are using

12th Gen Intel(R) Core(TM) i9-12900HK / RTX3060 Laptop / Nvidia Drivers 531.68

**Comment by Akirathan** [comment] 2023-07-28 15:45
Can't reproduce on `enso-linux-2023.2.1-nightly.2023.7.28.AppImage`, since I cannot even create a new project from a template in the cloud environment:
![image](https://github.com/enso-org/enso/assets/14013887/e75dac4d-3f14-4afa-b57a-f1d43ac66668)

**Comment by somebody1234** [comment] 2023-07-28 15:55
@Akirathan that's a frontend issue - it should be fixed by #7414, i think?
in the meantime i guess you could either try using that branch, or using an older release

**Comment by xvcgreg** [comment] 2023-08-09 18:27
@somebody1234 was it fixed in #7414 ? If so we should close this one.

**Comment by somebody1234** [comment] 2023-08-09 18:42
@xvcgreg sorry, wasn't clear with that comment. the "new project" button was broken. not sure about the original issue unfortunately, i don't think i've ever run into that issue

**Closed as completed** 2024-04-03 08:38 UTC
Labels: s-info-needed, s-no-repro, --bug
