### ISSUE TITLE
Node reports an error when there is no error

### ISSUE THREAD

**Issue by GregoryTravis** [enso-org/enso#6114] opened 2023-03-28 13:50 UTC
### Discord username

mito

### What type of issue is this?

Permanent – Ocurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

I enter correct code in a node, and it displays the error pattern around the edge. But when I press cmd-enter, the error disappears, since there wasn't really an error.

### Expected behaviour

 I expect the node to show an error if I have entered incorrect code, or only part of the correct code; but when I have entered all of the code and it is correct, I expect it to remove the error pattern.

### How we can reproduce it?

1. Create a new cloud project
2. Add a CSV file
3. Create a child node with "select_columns"
4. Enter correct code, such as: select_columns [Column_Selector.By_Name "Maths"]
5. Observe that the error pattern is still there, and there is an error message.
6. Press cmd-enter to finish the node
7. Error pattern disappears

### Screenshots or screencasts

<img width="762" alt="bug" src="https://user-images.githubusercontent.com/24406074/228258386-4ddd76e2-242c-4095-b907-96f8d6f21e5a.png">

### Enso Version

cmd+? does not bring anything up; I reproduced this in the cloud version 3/28/2023

### Browser or standalone distribution

Chrome

### Browser Version or standalone distribution

111.0.5563.64 (Official Build) (arm64)

### Operating System

MacOS

### Operating System Version

12.6.3

### Hardware you are using

MacBook Air (M1, 2020)

**Comment by farmaazon** [comment] 2023-03-31 07:48
It's because you're displaying preview (and it is somehow outdated). See [this discussion](https://github.com/orgs/enso-org/discussions/5856) for details.

Closing as duplicate of #6049

**Closed as not planned by farmaazon** 2023-03-31 07:48 UTC
Labels: --bug
