### ISSUE TITLE
Unknown two dots in the middle of the project

### ISSUE THREAD

**Issue by hubertp** [enso-org/enso#5756] opened 2023-02-23 15:29 UTC
![Screenshot from 2023-02-23 16-27-19](https://user-images.githubusercontent.com/292128/220952857-7c707c66-0275-4efc-ba64-1b7ad25ba3d6.png)

**Comment by Akirathan** [comment] 2023-02-23 15:31
Duplicate of #5743 .

**Closed as completed by Akirathan** 2023-02-23 15:31 UTC
