### ISSUE TITLE
Stopping a project from dashboard immediately starts a new Language Server

### ISSUE THREAD

**Issue by hubertp** [enso-org/enso#10561] opened 2024-07-15 21:34 UTC
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [X] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [X] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

Stopping a project briefly shows a stop button, as if the project was possible to stop, again.
Initially thought this was some minor hiccup in GUI but it actually turns out that we really do start, at least partially, the new Language Server.

Furthermore, starting the same project again is broken. 

### Expected behaviour

Stop means stop. No Language Server, or any component of it should be running once shutdown is finished.

### How we can reproduce it?

As per video.

### Screenshots or screencasts

[Kazam_screencast_00003.webm](https://github.com/user-attachments/assets/1bfe6e6c-d916-4a98-8eac-d212b2e37f55)

### Enso Version

2024.3.1-nightly.2024.7.15

### Browser or standalone distribution

Standalone distribution (local project)

### Browser Version or standalone distribution

standalone

### Operating System

Linux

**Comment by somebody1234** [comment] 2024-07-16 07:59
i had a similar problem when fixing E2E tests for:
- #10541

specifically it seems to be that `Editor` sticks around after the tab is closed because tab updates are in a `startTransition`. 

in that case, one way to fix this would be to remove the `startTransition`. not ideal latency wise but at least it isn't buggy...

**Comment by MrFlashAccount** [comment] 2024-07-16 08:29
Even though the bug isn't in `startTransition` (it only highlights the root cause), if we can't fix the root cause, or it would take an unreasonable amount of time, then yes, let's remove the `startTransition`.

**Comment by somebody1234** [comment] 2024-07-16 08:38
@MrFlashAccount i assume this is the root cause:

https://github.com/enso-org/enso/blob/a992c8aa4f9e4d89f8259fc6caf1dcabf184b9a3/app/ide-desktop/lib/dashboard/src/layouts/Editor.tsx#L84-L86

and i guess the bug would happen like this:
1. user stops project
2. project is immediately closed, react begins transition to close the editor
3. editor sees that project is closed and spins it up again

**Comment by MrFlashAccount** [comment] 2024-07-16 08:59
@somebody1234 can we try to put this into a `useEffect`? React doesn't call `useEffect`s during a transition. Even though I strictly suggest avoiding `useEffect`, seems like it's the only option here...

**Comment by PabloBuchu** [comment] 2024-12-05 16:01
Closing as it seems fixed

**Closed as completed by PabloBuchu** 2024-12-05 16:01 UTC
Labels: --bug, --regression, g-dashboard
