### ISSUE TITLE
Ctrl + A while typing the new node name selects also documentation in Component Browser

### ISSUE THREAD

**Issue by xvcgreg** [enso-org/enso#6288] opened 2023-04-14 17:04 UTC
### What type of issue is this?

Permanent – Ocurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [X] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

While creating new node when you select all chars with the Ctrl + A shortcut it also selects content of Documentation Panel in CB. Even after canceling the node creation Documentation and Visualisation panels content is still selected when trying to create a new node. Only clicking the documentation panel deselects it's content.

### Expected behaviour

Ctrl + A selects only content of the node name creation.

### How we can reproduce it?

press tab
start typing 
press ctrl + a
observe the result

### Screenshots or screencasts

https://user-images.githubusercontent.com/108271897/232110394-943de03e-ddaf-4db5-95f3-c4294a75892b.mp4

### Enso Version

2023.04.13

### Browser or standalone distribution

Standalone distribution

### Browser Version or standalone distribution

standalone

### Operating System

Windows

### Operating System Version

11pro 22H2

### Hardware you are using

12th Gen Intel(R) Core(TM) i9-12900HK / RTX3060 Laptop

**Comment by sylwiabr** [comment] 2023-04-15 07:02
This is a duplicate of https://github.com/enso-org/enso/issues/6224

**Closed as not planned by sylwiabr** 2023-04-15 07:02 UTC
Labels: s-duplicate, --bug, --regression
