### ISSUE TITLE
Nodes of existing code stopped showing 

### ISSUE THREAD

**Issue by Procrat** [enso-org/enso#6102] opened 2023-03-28 09:03 UTC
### Discord username

Stijn#6455

### What type of issue is this?

Intermittent – Ocurring irregularly

### Is this issue blocking you from using Enso?

- [X] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

When working on one of the book club challenges, all nodes suddenly disappeared. Upon, restarting the IDE, they still weren't there. However, when I look at the code in the project directory, the code is still there.

### Expected behaviour

I expect nodes I've created to only disappear when I delete them.

### How we can reproduce it?

This has [happened before](https://github.com/orgs/enso-org/discussions/5955), but I don't have a way to reliably reproduce it. It happens at seemingly random points in time.

This time, however, I managed to collect logs (with `debug.verbose=true`). There were too many lines for my terminal to capture all of them, so it's only the last ~2k lines. If this is not enough, I'll redirect logs to file at the start to capture everything.

[logs.txt](https://github.com/enso-org/enso/files/11087439/logs.txt)

### Enso Version

develop

### Browser or standalone distribution

Standalone distribution

### Browser Version or standalone distribution

standalone

### Operating System

Linux

**Comment by hubertp** [comment] 2023-03-28 09:25
Thanks for the logs. I don't see anything suspicious in them, though. But... here is another thought:
I've experienced something similar recently but the thing is that essentially the whole scene zoom'ed out and _moved_ in some awkward direction. Have you tried moving around zooming in/out to try to find it? This also often happens to me since my scrolling wheel is super sensitive.

**Comment by farmaazon** [comment] 2023-03-28 09:58
> Have you tried moving around zooming in/out to try to find it? This also often happens to me since my scrolling wheel is super sensitive.

I also have this effect, however restarting IDE or reopening project works, and for Stijn it does not. But perhaps there was far scroll before inserting nodes.

The possible workaround is removing the entire `### METADATA` section in the source file. This will break the graph layout, but the nodes should appear.

@Procrat could you addach zipped project which is empty on star?

**Comment by Procrat** [comment] 2023-03-28 12:13
@hubertp Zooming out was indeed the first thing I tried, but I still couldn't see the graph. Thanks for thinking this through though!

@farmaazon Thanks for the workaround. I just tried it, but they still don't seem to show up. I've attached the project here: [project.zip](https://github.com/enso-org/enso/files/11089077/project.zip).

Here are also the full logs of a clean run with that project: 
[stderr.txt](https://github.com/enso-org/enso/files/11089141/stderr.txt)
[stdout.txt](https://github.com/enso-org/enso/files/11089142/stdout.txt)

**Comment by farmaazon** [comment] 2023-03-28 13:35
I can open the project and see the nodes (they are a little to the right). It may be a machine-dependent thing.

@Procrat to have a full picture: could you add also logs from web console? Add `--debug.dev-tools` option, and remember to call `showLogs()` in the console.

**Comment by hubertp** [comment] 2023-03-28 14:15
@Procrat The logs you posted are different from the ones in the description. In the latter ones the language server (part of backend) fails to startup, which would explain why you are not able to see the nodes. I would second @farmaazon's opinion that this is machine-dependent, which doesn't change the fact that it would be good to have it working.

How are you starting Enso?

**Comment by Procrat** [comment] 2023-03-28 14:39
@farmaazon I just tried reproducing it again and now I can see them as well. When comparing the logs now with the second ones I posted, I notice that last time it didn't get to
```
[info] [org.enso.languageserver.text.CollaborativeBuffer] Buffer opened for [path:Path(<snip>,Vector(src, Main.enso)), client:<snip>].
```
I thought I waited long enough (also looking at the heartbeat logs), but perhaps not?


@hubertp I ran:
```
./run ide build --wasm-profile=dev --backend-source=release --backend-release=latest
./dist/ide/enso-linux-2023.1.1-dev.AppImage -debug.verbose
```

**Comment by farmaazon** [comment] 2023-03-31 07:51
I assign @hubertp for further investigation. For me, it's hard to tell what happened on the IDE side without dev-console logs.

@Procrat if you will face this issue again, please post them.

**Comment by Procrat** [comment] 2023-03-31 07:58
@farmaazon Will do!

**Comment by hubertp** [comment] 2023-04-05 08:38
I had no luck reproducing and the logs looks mostly alright to me. Closing, feel free to reopen if it happens again.

**Closed as completed by hubertp** 2023-04-05 08:38 UTC
Labels: --bug, -language-server
