### ISSUE TITLE
Renaming a project sometimes duplicates it

### ISSUE THREAD

**Issue by farmaazon** [enso-org/enso#7705] opened 2023-08-31 08:52 UTC
A follow-up of this comment: https://github.com/enso-org/enso/issues/7679#issuecomment-1696227469

**Comment by 4e6** [comment] 2023-10-05 15:49
Waiting for #7917 to land

**Comment by 4e6** [comment] 2023-10-13 15:19
The issue might have been caused by #7589. I don't observe this behavior right now

**Comment by 4e6** [comment] 2023-10-13 17:35
Closing as fixed by #7589

**Closed as completed by 4e6** 2023-10-13 17:35 UTC
Labels: --bug, -project-manager
