### ISSUE TITLE
Conflicting Extension Methods Make Resolution Nondeterministic

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5360] opened 2023-02-05 23:00 UTC
This task is automatically imported from the old Task Issue Board and it was originally created by Radosław Waśko.
Original issue is [here](https://www.pivotaltracker.com/story/show/183509341).
<hr />

Migrated from https://github.com/enso-org/enso/issues/1243

### General Summary

When multiple modules define extension methods with the same name and for the same type and both modules are imported, resolution of that method is not deterministic.

### Steps to Reproduce

1. Create new project (here called `Multitest`) with the following files:

`File1.enso`:
```
from Base import all
Number.foo = 42
```

`File2.enso`:
```
from Base import all
Number.foo = "answer"
```

`Main.enso`:
```
from Base import all
import Multitest.File1 
import Multitest.File2

main =
  a = 23.foo
  IO.println a
```

Or download the project from here: [multitest.zip](https://github.com/enso-org/enso/files/5428888/multitest.zip)

2. Run it several times

### Expected Result

The above code should result in an ambiguity error.

Ideally, the error should be detected when importing the module that brings the ambiguous resolution. If that's not possible, executing that method in runtime should yield a runtime error indicating the ambiguity.

### Actual Result

The program sometimes prints `answer` and sometimes `42`, behaving nondeterministically.

**Comment by radeusgd** [comment] 2024-02-22 09:23
Duplicate of #1243

**Closed as completed by radeusgd** 2024-02-22 09:23 UTC
Labels: s-duplicate, p-low, --bug, -compiler
