### ISSUE TITLE
Clicking on the output port creates an edge

### ISSUE THREAD

**Issue by vitvakatu** [enso-org/enso#5887] opened 2023-03-10 09:13 UTC
I connected the first edge, then I clicked on another node's output port – and you can see what happened on the video. After that, clicking on output ports and dragging edges produces weird results without much pattern. Sometimes I even couldn't drop the connection without connecting it to anything. It happens even after reopening the project.

https://user-images.githubusercontent.com/6566674/224274656-6b5a14f1-ec9d-41a4-81ee-3e113d6ef53d.mp4

**Comment by wdanilo** [comment] 2023-03-10 11:47
This is bad. I don't recognize such error in the past. Looks like a regression to me.

**Comment by farmaazon** [comment] 2023-07-03 10:28
I cannot reproduce it anymore. Probably fixed by @Frizi changes in #7041

**Closed as completed** 2023-07-03 10:28 UTC
Labels: p-high, --bug
