### ISSUE TITLE
Visualization displayed in the wrong place while interacting with Component Browser

### ISSUE THREAD

**Issue by xvcgreg** [enso-org/enso#6158] opened 2023-03-30 21:28 UTC
### What type of issue is this?

Permanent – Ocurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [X] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

Visualization is being displayed in wrong place - depending on what component is currently active. You can observe it changing location from 13th second of the attached video (from top left corner to the correct place and back)

https://user-images.githubusercontent.com/108271897/228968369-93222197-914a-4b92-82b3-8eddbf2a2d04.mp4

### Expected behaviour

Viz being in correct place, below input area.

### Enso Version

https://github.com/enso-org/enso/actions/runs/4550435584
Nightly Release # 862 (Actions no)

### Browser or standalone distribution

Standalone distribution

### Browser Version or standalone distribution

standalone

### Operating System

Windows

### Operating System Version

11pro 22H2

### Hardware you are using

12th Gen Intel(R) Core(TM) i9-12900HK / RTX3060 Laptop

**Comment by farmaazon** [comment] 2023-03-31 07:55
@xvcgreg you marked it as "Permanent – Ocurring repeatably" Do you have a reproduction scenario? I cannot reproduce, basing only on video you posted.

As I see, the "main visualization" is always at the wrong place. When preview shows error, we display a different, "error" visualization, which is in good place.

**Comment by xvcgreg** [comment] 2023-04-04 08:11
@farmaazon 
> Do you have a reproduction scenario? I cannot reproduce, basing only on video you posted.

It's permanent for me:
- I open last created project
- hit ``Tab`` 
- CB opens and viz is in the wrong place (there's also problem with disappearing nodes, but that's solvable by zoom out and back in)

here's another recording of this issue:

https://user-images.githubusercontent.com/108271897/229729652-33c811a4-a9ad-45e9-89be-a76fd53d31de.mp4

**Comment by farmaazon** [comment] 2023-04-04 09:56
@xvcgreg Can you post your project here? I do not have this issue with my projects.

Also, the version posted seems to be invalid, it refers to a commit from 3 years ago.

**Comment by xvcgreg** [comment] 2023-04-04 12:20
> Also, the version posted seems to be invalid, it refers to a commit from 3 years ago.
@farmaazon 

Here you go: https://github.com/enso-org/enso/actions/runs/4550435584

**Comment by xvcgreg** [comment] 2023-04-04 12:34
[Unnamed_9.zip](https://github.com/enso-org/enso/files/11148504/Unnamed_9.zip)

@farmaazon here's the project

**Comment by xvcgreg** [comment] 2023-04-04 12:44
2 additional media files with issues that might be related to this bug:

1. Wrongly placed visualizations move with lateral panning of the camera

https://user-images.githubusercontent.com/108271897/229795049-ebb22ecc-41e5-485b-8701-707974c377b6.mp4



2. Selection of the visualization displayed in the wrong place

![Screenshot 2023-04-04 143252](https://user-images.githubusercontent.com/108271897/229795361-9484a918-c9ae-4252-9cb3-6f9f79cb9db7.png)

**Comment by sylwiabr** [comment] 2023-04-04 16:33
@xvcgreg can you check the Enso version and paste it here? The issue you linked is 4 years old

**Comment by xvcgreg** [comment] 2023-04-04 16:50
> @xvcgreg can you check the Enso version and paste it here? The issue you linked is 4 years old


Updated the description (today it was brought to my attention that GH is linking it to issues, not actions). Sorry for that.

**Comment by xvcgreg** [comment] 2023-04-04 18:36
@farmaazon issue with nodes moving while panning the camera was introduced in # 857 (https://github.com/enso-org/enso/actions/runs/4486593388) nightly 2023.03.22 (in previous one (# 856) it's not occurring 

<blockquote><img src="https://opengraph.githubassets.com/d3a2ccf2acfa89bb3f8dde64b890f0a5f7e27d5cc15cf6d4d495bff72516e604/enso-org/enso" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/enso-org/enso">Nightly Release · enso-org/enso@8c6fd60</a></strong></div><div>Hybrid visual and textual functional programming. Contribute to enso-org/enso development by creating an account on GitHub.</div></blockquote>

**Comment by sylwiabr** [comment] 2023-04-07 12:46
It happened to me today 
<img width="1386" alt="image" src="https://user-images.githubusercontent.com/12892578/230611072-71f2413c-ce1b-4995-9f8e-4dc0865fdccd.png">
The visualization glued to the node when I panned the screen. Unfortunately we are blocking shortcut to open developer tools so I couldn't see if there are any logs in the IDE.

**Comment by sylwiabr** [comment] 2023-04-07 12:55
It looks like it happens when I am building quickly the workflow with the scene panned. There is lots of ensogl warnings in the logs console so hard to see if there is anything relevant. 

https://user-images.githubusercontent.com/12892578/230612325-c9e18199-873d-4acb-a4e0-7a8408e94ecf.mov

**Comment by vitvakatu** [comment] 2023-04-19 18:20
Copied from discord, for history:

I can reproduce the issue easily, but I still don't understand what causes it. Take a look at the attached video. When opening the CB with the Tab key, the DomLayer div suddenly jumps up, and all visualizations move with it. Then I can pan the screen down, and visualizations comfortably slide to their correct position.
1. front and back DomLayers move together; other DomLayers are not moving.
2. DomLayer::update_view_projection is never triggered when you press Tab, which is expected.
3. There are no changes in the attributes of any DOM element. However, devtools show that div of the back back layer is changed somehow (it is highlighted with purple right when I press Tab, you can see it on the video)
4. I don't see any css styles etc., that is changed, and nothing seemingly causes this position change for the div.
5. This is not triggered on the non-default zoom level (see the second video)
6. This is only triggered by the Tab key, Enter does not have this effect

The last point made me think it is somehow related to the changes in our events handling, with similar issues like https://github.com/enso-org/enso/issues/6290. So my idea is that the Tab key is not captured, and we somehow trigger some default browser behavior. It's not clear why the div is moving, though.


https://user-images.githubusercontent.com/6566674/233165214-c77e05a4-bb5f-4144-83f9-5894947ba10e.mp4

**Comment by farmaazon** [comment] 2023-04-20 09:04
@vitvakatu but have you tested, that preventing default on every event make this bug disappear?

**Comment by vitvakatu** [comment] 2023-04-20 09:28
> but have you tested, that preventing default on every event make this bug disappear?

Yes, the message above was written before I tested that. It fixes the issue and seemingly has no negative effects on the IDE. I'm testing the fix at the moment.

**Closed as completed** 2023-04-20 13:58 UTC
Labels: p-high, --bug, --regression, -viz
