### ISSUE TITLE
Component browser does not react to symbol input

### ISSUE THREAD

**Issue by Akirathan** [enso-org/enso#7105] opened 2023-06-22 10:42 UTC
[Screencast from 2023-06-22 12-38-09.webm](https://github.com/enso-org/enso/assets/14013887/20ae5504-bffc-4101-9540-ff8cb9a5e4ae)

I would expect CB starts filtering out suggestions, the same way as it does for other inputs.

On `enso-linux-2023.2.1-nightly.2023.6.21.AppImage`.

**Comment by kazcw** [comment] 2023-06-22 13:49
I believe this is by design--see part 1 here: #6854. `>` and `=` are complete operators, so we are showing suggestions for a following operand.

**Comment by farmaazon** [comment] 2023-06-22 14:06
Marking as duplicate of #6854

**Comment by wdanilo** [comment] 2023-06-26 13:29
If the user types `<`, the Component Browser should indeed hint something starting or containing `<`. No reaction from Component Browser is indeed a bad behavior. Just a small explanation.

**Closed as not planned** 2023-06-26 14:14 UTC
Labels: s-duplicate
