### ISSUE TITLE
Scrolling in the visualization preview also selects the text inside

### ISSUE THREAD

**Issue by Akirathan** [enso-org/enso#6503] opened 2023-05-02 11:05 UTC
I noticed a weird behavior when scrolling the visualization preview:
- When I click only on the scrollbar and drag it down/up, the text inside the visualization is also selected.
- Doubly click on a word selects only the word - that is expected.
- Clicking on a text and moving the mouse up/down, I would expect the text selection to behave like in a standard text editor, but it behaves in a very weird way, making it impossible to select multiple line of text inside the viz preview.

Tried with version 7e333000130ea539fe82d5f5942f23047c92fe3a
[Screencast from 2023-05-02 12-52-29.webm](https://user-images.githubusercontent.com/14013887/235648398-d0e5bedc-0bfb-4782-8efd-94be71ad00d7.webm)

**Comment by farmaazon** [comment] 2023-05-02 11:47
Duplicate of #5217

**Closed as not planned** 2023-05-02 11:47 UTC
Labels: s-duplicate
