### ISSUE TITLE
DataflowAnalysis fails on "Blanks should not be present"

### ISSUE THREAD

**Issue by Akirathan** [enso-org/enso#9063] opened 2024-02-14 16:03 UTC
This code:
```
from Standard.Base import all

foo -> Vector =
    names = ["Pavel", "Jaroslav"]
    names.map (_.length)

main = foo
```
fails to compile with stacktrace:
```
Execution finished with an error: org.enso.compiler.core.CompilerError: Compiler Internal Error: Blanks should not be present during dataflow analysis.
        at <java> org.enso.runtime/org.enso.compiler.pass.analyse.DataflowAnalysis$.analyseName(DataflowAnalysis.scala:556)
        at <java> org.enso.runtime/org.enso.compiler.pass.analyse.DataflowAnalysis$.analyseExpression(DataflowAnalysis.scala:244)
        at <java> org.enso.runtime/org.enso.compiler.pass.analyse.DataflowAnalysis$.analyseCallArgument(DataflowAnalysis.scala:759)
        at <java> org.enso.runtime/org.enso.compiler.pass.analyse.DataflowAnalysis$.$anonfun$analyseApplication$2(DataflowAnalysis.scala:347)
        at <java> org.enso.runtime/scala.collection.immutable.List.map(List.scala:246)
        at <java> org.enso.runtime/org.enso.compiler.pass.analyse.DataflowAnalysis$.analyseApplication(DataflowAnalysis.scala:347)
        at <java> org.enso.runtime/org.enso.compiler.pass.analyse.DataflowAnalysis$.analyseExpression(DataflowAnalysis.scala:242)
        at <java> org.enso.runtime/org.enso.compiler.pass.analyse.DataflowAnalysis$.analyseCallArgument(DataflowAnalysis.scala:759)
        at <java> org.enso.runtime/org.enso.compiler.pass.analyse.DataflowAnalysis$.$anonfun$analyseApplication$2(DataflowAnalysis.scala:347)
        at <java> org.enso.runtime/scala.collection.immutable.List.map(List.scala:250)
        at <java> org.enso.runtime/org.enso.compiler.pass.analyse.DataflowAnalysis$.analyseApplication(DataflowAnalysis.scala:347)
        at <java> org.enso.runtime/org.enso.compiler.pass.analyse.DataflowAnalysis$.analyseExpression(DataflowAnalysis.scala:242)
        at <java> org.enso.runtime/org.enso.compiler.pass.analyse.DataflowAnalysis$.analyseExpression(DataflowAnalysis.scala:260)
        at <java> org.enso.runtime/org.enso.compiler.pass.analyse.DataflowAnalysis$.analyseFunction(DataflowAnalysis.scala:309)
        at <java> org.enso.runtime/org.enso.compiler.pass.analyse.DataflowAnalysis$.analyseExpression(DataflowAnalysis.scala:241)
        at <java> org.enso.runtime/org.enso.compiler.pass.analyse.DataflowAnalysis$.analyseModuleDefinition(DataflowAnalysis.scala:166)
        at <java> org.enso.runtime/org.enso.compiler.pass.analyse.DataflowAnalysis$.$anonfun$runModule$1(DataflowAnalysis.scala:77)
        at <java> org.enso.runtime/scala.collection.immutable.List.map(List.scala:246)
        at <java> org.enso.runtime/org.enso.compiler.pass.analyse.DataflowAnalysis$.runModule(DataflowAnalysis.scala:77)
        at <java> org.enso.runtime/org.enso.compiler.pass.PassManager.$anonfun$runPassesOnModule$2(PassManager.scala:101)
        at <java> org.enso.runtime/scala.collection.LinearSeqOps.foldLeft(LinearSeq.scala:183)
        at <java> org.enso.runtime/scala.collection.LinearSeqOps.foldLeft$(LinearSeq.scala:179)
        at <java> org.enso.runtime/scala.collection.immutable.List.foldLeft(List.scala:79)
        at <java> org.enso.runtime/org.enso.compiler.pass.PassManager.runPassesOnModule(PassManager.scala:92)
        at <java> org.enso.runtime/org.enso.compiler.Compiler.runMethodBodyPasses(Compiler.scala:821)
        at <java> org.enso.runtime/org.enso.compiler.Compiler.$anonfun$runCompilerPipeline$10(Compiler.scala:350)
        at <java> org.enso.runtime/org.enso.compiler.Compiler.$anonfun$runCompilerPipeline$10$adapted(Compiler.scala:334)
        at <java> org.enso.runtime/scala.collection.immutable.List.foreach(List.scala:333)
        at <java> org.enso.runtime/org.enso.compiler.Compiler.runCompilerPipeline(Compiler.scala:334)
        at <java> org.enso.runtime/org.enso.compiler.Compiler.go$1(Compiler.scala:229)
        at <java> org.enso.runtime/org.enso.compiler.Compiler.runInternal(Compiler.scala:236)
        at <java> org.enso.runtime/org.enso.compiler.Compiler.run(Compiler.scala:131)
        at <java> org.enso.runtime/org.enso.interpreter.runtime.Module.compile(Module.java:391)
        at <java> org.enso.runtime/org.enso.interpreter.runtime.Module.compileScope(Module.java:318)
        at <java> org.enso.runtime/org.enso.interpreter.runtime.Module$InvokeMember.doInvoke(Module.java:680)
        at <java> org.enso.runtime/org.enso.interpreter.runtime.ModuleGen$InteropLibraryExports$Cached.executeAndSpecialize(ModuleGen.java:115)
        at <java> org.enso.runtime/org.enso.interpreter.runtime.ModuleGen$InteropLibraryExports$Cached.invokeMember(ModuleGen.java:104)
        at <java> org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotValueDispatch$InteropValue$SharedInvokeNode.doDefault(PolyglotValueDispatch.java:4713)
        at <java> org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotValueDispatchFactory$InteropValueFactory$SharedInvokeNodeGen$Inlined.executeAndSpecialize(PolyglotValueDispatchFactory.java:10293)
        at <java> org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotValueDispatchFactory$InteropValueFactory$SharedInvokeNodeGen$Inlined.executeShared(PolyglotValueDispatchFactory.java:10245)
        at <java> org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotValueDispatch$InteropValue$InvokeNoArgsNode.doDefault(PolyglotValueDispatch.java:4778)
        at <java> org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotValueDispatchFactory$InteropValueFactory$InvokeNoArgsNodeGen.executeImpl(PolyglotValueDispatchFactory.java:10529)
        at <java> org.graalvm.truffle/com.oracle.truffle.polyglot.HostToGuestRootNode.execute(HostToGuestRootNode.java:124)
        at <java> org.graalvm.polyglot/org.graalvm.polyglot.Value.invokeMember(Value.java:972)
        at <java> org.enso.IsolatedClassLoader//org.enso.polyglot.Module.getAssociatedType(Module.scala:19)
        at <java> org.enso.IsolatedClassLoader//org.enso.runner.Main$.runMain(Main.scala:845)
        at <java> org.enso.IsolatedClassLoader//org.enso.runner.Main$.runSingleFile(Main.scala:775)
        at <java> org.enso.IsolatedClassLoader//org.enso.runner.Main$.run(Main.scala:656)
        at <java> org.enso.IsolatedClassLoader//org.enso.runner.Main$.runMain(Main.scala:1213)
        at <java> org.enso.IsolatedClassLoader//org.enso.runner.Main$.$anonfun$main$8(Main.scala:1094)
        at <java> org.enso.IsolatedClassLoader//scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
        at <java> org.enso.IsolatedClassLoader//org.enso.runner.Main$.withProfiling(Main.scala:1290)
        at <java> org.enso.IsolatedClassLoader//org.enso.runner.Main$.$anonfun$main$7(Main.scala:1094)
        at <java> org.enso.IsolatedClassLoader//org.enso.runner.Main$.$anonfun$main$7$adapted(Main.scala:1094)
        at <java> org.enso.IsolatedClassLoader//scala.util.Either.fold(Either.scala:189)
        at <java> org.enso.IsolatedClassLoader//org.enso.runner.Main$.main(Main.scala:1094)
        at <java> org.enso.IsolatedClassLoader//org.enso.runner.Main.main(Main.scala)
        at <java> java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at <java> java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at <java> org.enso.runtime/org.enso.EngineRunnerBootLoader.main(EngineRunnerBootLoader.java:46)
```

When I attached a debugger, I found out that the error is reported in the `(_.length)` expression. Replacing the method header from `foo -> Vector = ` by just `foo = `, everything works as expected. The error is only reported when the return type is in the inline ascription.

**Comment by JaroslavTulach** [comment] 2024-09-25 09:33
- duplicate of #11090

**Closed as not planned by JaroslavTulach** 2024-09-25 09:33 UTC
Labels: --bug, -compiler
