### ISSUE TITLE
Enso failed to install on Windows without any warning

### ISSUE THREAD

**Issue by xvcgreg** [enso-org/enso#6391] opened 2023-04-24 12:09 UTC
### What type of issue is this?

Intermittent – Occurring irregularly

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

I have started installing Enso nightly 2023.03.25. I presumed it has finished correctly as it launched itself just after install - but it failed and instead I got presented with 2023.03.28 that I have had installed. 

I dont know if that's anyhow related but after this failed install the Component Browser started to be laggy. Could this failed installation break something? (I have reinstalled 2023.3.28 and CB is snappy again.)

### Expected behaviour

On failed/successful installation, as a user I'd like to see the notification about that. Also I'd preferer to be asked if I want to launch the program after the installation or not.

### Enso Version

2023.03.25

### Browser or standalone distribution

Standalone distribution

### Browser Version or standalone distribution

standalone

### Operating System

Windows

### Operating System Version

Win11pro 22H2 22621.1555

### Hardware you are using

12th Gen Intel(R) Core(TM) i9-12900HK / RTX3060 Laptop / Nvidia Drivers 531.68

**Comment by wdanilo** [comment] 2023-04-24 12:27
This is interesting. Could you repro that? Unfortunately, system installers are not made by us, they are delivered as part of Electron Builder, so we don't control it.

**Comment by xvcgreg** [comment] 2023-04-24 12:30
@wdanilo I believe @sylwiabr had similar issue on Mac. Then we have not caught that it was failed install - but her case had some similar Enso behavior/performance problems that were resolved on reinstalling.

Reproduce - it's very hard. As soon as it occurs again I can report it. But I do not have repro steps for that - it's random.

**Comment by wdanilo** [comment] 2023-04-24 12:33
@xvcgreg hmm, did you have old instance of Enso running during installation? I think that unfortunately we need to close this issue until more occurrences of it happen / we have repro, as we are really not controlling this process. If this happened on Mac as well, this would be even more interesting, as the Mac package is a completely different beast (also controlled by Electron Builder) and if it had similar issue, this would be strange. Are you OK with closing it for now and re-opening the next time it happens?

**Comment by xvcgreg** [comment] 2023-04-24 13:19
No I had not Enso process open in the BG - I have monitor for that:

this is how it looks during installation:
![image](https://user-images.githubusercontent.com/108271897/234008053-21ff1f1f-290b-4cd2-8d96-06385aae7710.png)

this is how it shows when one instance of Enso is running:
![image](https://user-images.githubusercontent.com/108271897/234008242-30147d96-05de-4750-99b8-b7193c2235a5.png)

**Comment by wdanilo** [comment] 2023-04-24 13:22
Ok, let's close it and re-open when it happens again, hopefully with more info / repro.

**Comment by hubertp** [comment] 2023-04-24 14:36
I will try to reproduce tomorrow on a clean laptop and close if unable to reproduce.

**Comment by xvcgreg** [comment] 2023-04-24 17:18
One additional thing: when Enso is running in the background and we want to install a different version, the installer asks to close the running instance in a popup.

**Comment by vitvakatu** [comment] 2023-05-03 11:05
Closing for now, @hubertp please reopen if you can repro.

**Closed as completed by vitvakatu** 2023-05-03 11:05 UTC
Labels: s-no-repro, --bug
