### ISSUE TITLE
Package on Windows sometimes leave zombie processes

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#4987] opened 2023-02-05 22:41 UTC
This task is automatically imported from the old Task Issue Board and it was originally created by Michał Urbańczyk.
Original issue is [here](https://www.pivotaltracker.com/story/show/182691027).
<hr />

This leads to failures when starting IDE package later.

## Comments:
**Michał Urbańczyk** reports a new **STANDUP** for the last Friday (2022-08-12):

**Progress:** Identified a case where zombie processes are left. Errors were not properly handled in the IDE's JS main function. Provided a fix and created a PR. Failed to find other scenarios where the issue happens. It should be finished by 2022-08-17.

**Next Day:** Next day I will be working on the [##182691027 task](https://www.pivotaltracker.com/story/show/182691027). Apply any CR feedback and land changes. If there's nothing more to do, start further tasks. (Enso Bot - Aug 15, 2022)
<hr />
**Michał Urbańczyk** reports a new **STANDUP** for yesterday (2022-08-15):

**Progress:** Landed PR. Started work on the next task: Windows signing certificates. Generated a new certificate with password. Stored the relevant information in the Bitwarden. Started redesign of the runner deployment so the certificate can be exposed from host to the runner. Along the way started preparations for the runner cleaning job. It should be finished by 2022-08-17.

**Next Day:** Next day I will be working on the [##182683110 task](https://www.pivotaltracker.com/story/show/182683110). Weekly updates, updates to runners to enable signing. (Enso Bot - Aug 17, 2022)
<hr />
Zombie process remain after IDE fails to start.
Broken packages that Greg tested displayed this. (Michał Urbańczyk - Sep 23, 2022)
<hr />

**Comment by farmaazon** [comment] 2024-05-24 13:49
@wdanilo do you know the reproduction scenario for this task?

**Comment by jdunkerley** [comment] 2024-08-28 17:00
Closing as Windows packaging seems to be fine at moment.

**Closed as not planned by jdunkerley** 2024-08-28 17:00 UTC
Labels: -ci, p-low, --bug
