### ISSUE TITLE
Migrating `Column.map` and `Column.zip` to Java-to-Enso callbacks

### ISSUE THREAD

**Issue by radeusgd** [enso-org/enso#7371] opened 2023-07-22 18:12 UTC
[The benchmarks are showing](https://github.com/enso-org/enso/pull/7270#issuecomment-1639916001) that the current approach used for `Column.map` and `Column.zip` is not that efficient - the old approach relying on passing an Enso callback to the Java code is 2-6x faster than the current one.

So we wanted to migrate that, but in #7368 I realised we do not have tests for propagating panics/errors/warnings through these callbacks.

With some work, dataflow errors are propagated just like panics. However, currently, the polyglot helpers in Java have no way to tell if a returned value has warnings attached.

Thus, if we just switched without some additional logic, any warnings reported inside of the function passed to `Column.map/zip` would be lost. That does not seem right and it would be a regression from the current state (currently the warnings are attached to the created resulting column).

So to be able to migrate this, we need to figure out a way to detect and gather the warnings returned from Enso functions called from within Java.

This will make the logic a bit more complicated, so we may need to actually revise the benchmarks and see if the added complexity of handling warnings does not thwart the expected gains from switching to this different approach.

**Comment by jdunkerley** [comment] 2023-07-25 09:34
Duplicate of #7317

**Closed as not planned by jdunkerley** 2023-07-25 09:34 UTC
Labels: -libs

**Comment by radeusgd** [comment] 2023-07-25 10:02
Ah right! Sorry, I forgot about the other one. But I will then reproduce the text from this issue as it introduces some important comments we need to keep in mind.
