### ISSUE TITLE
Failed to execute 'open' on 'CacheStorage': Unexpected internal error - while turning on the node preview

### ISSUE THREAD

**Issue by xvcgreg** [enso-org/enso#6720] opened 2023-05-17 10:05 UTC
### What type of issue is this?

Intermittent – Occurring irregularly

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

I have accidently broken connection between two nodes then undo this missclick and when I have pressed space on the node to view the node preview this error occurred.

https://github.com/enso-org/enso/assets/108271897/caedd6e8-8b17-4424-9350-361e6eca3049

I was working on a project in the cloud.

### Expected behaviour

No errors on node preview action

### Enso Version

2023.5.17 nightly

### Browser or standalone distribution

Standalone distribution

### Browser Version or standalone distribution

standalone

### Operating System

Windows

### Operating System Version

Win11pro 22H2 22621.1555

### Hardware you are using

12th Gen Intel(R) Core(TM) i9-12900HK / RTX3060 Laptop / Nvidia Drivers 531.68

**Comment by Frizi** [comment] 2023-05-19 20:28
I have seen this error message previously once and was very puzzled by it, but I wasn't able to reproduce it since. At least it didn't seem to have any negative effect on the application itself.

I don't think that we are using `CacheStorage` anywhare in the IDE by ourselves, so it looks like an error from within some dependency. The devtools application tab shows one cache storage is used by mapbox:
![image](https://github.com/enso-org/enso/assets/919491/6ad10fc7-e469-4ff5-86d5-192d43d756b6)

The error is also a little wierd, as it is an undocumented exception from within the browser implementation. The reason it is thrown is also not exactly clear to me, but looks like a mismatch between number of expected bytes to receive vs actual data size somewhere deep within the storage implementation: https://source.chromium.org/chromium/chromium/src/+/main:content/browser/cache_storage/cache_storage_cache.cc;l=1691-1696?q=kErrorStorage&ss=chromium%2Fchromium%2Fsrc

I even found a comment expressing confusion about it within the chromium source tree (in this case it's in perfetto - one of the devtools):
https://source.chromium.org/chromiumos/chromiumos/codesearch/+/main:src/aosp/external/perfetto/ui/src/common/errors.ts;l=53-63
```
// Occasionally operations using the cache API throw:
// 'UnknownError: Unexpected internal error. {}'
// It's not clear under which circumstances this can occur. A dive of
// the Chromium code didn't shed much light
...
// Given the error is not actionable at present and caching is 'best
// effort' in any case ignore this error.
```

A stackoverflow answer related to this exact error message suggests that it might be caused by a serviceworker being terminated too quicky, before the cache had a chance to finish opening: https://stackoverflow.com/a/64359684

I suspect that in some scenarios we might be incorrectly activating mapbox visualization for a very brief moment when the node preview is opened, or something like that. I don't think though that this error has any effect on the application as a whole, nor it is in any way actionable by us.

I'm going to consider it as wontfix. If any actual detremental effect of this error is found, we will then need to investigate it further.

**Closed as not planned by Frizi** 2023-05-19 20:28 UTC
Labels: s-wontfix, --bug
