### ISSUE TITLE
Tabbing out of a text(any?) widget should commit the text not discard it

### ISSUE THREAD

**Issue by AdRiley** [enso-org/enso#9889] opened 2024-05-08 13:59 UTC
Tabbing out of a text(any?) widget should commit the text not discard it.

Tab is a natural way to move to next widget.

Try this in the set component

**Comment by kazcw** [comment] 2024-05-08 14:00
See also: #9711

**Comment by farmaazon** [comment] 2024-05-09 07:37
Closing as duplicate of #9711

**Closed as not planned by farmaazon** 2024-05-09 07:37 UTC
Labels: s-duplicate, p-highest, --bug, -gui
