### ISSUE TITLE
Errors in the workflow are making IDE sluggish

### ISSUE THREAD

**Issue by sylwiabr** [enso-org/enso#6674] opened 2023-05-12 16:28 UTC
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

When I am working with bigger project and break it at the beginning first IDE is freezing for the time when errors are getting populated. Having many errors is also slowing down IDE when trying to work with it on weaker hardware (editing nodes, zooming, panning are having delays). Breaking first node on Restaurants example available in our templates is already freezing my IDE on M2 MacOS. 

### Expected behaviour

Errors on nodes should not affect IDE performance.

### Enso Version

nightly 12.05.2023

### Browser or standalone distribution

Standalone distribution

### Browser Version or standalone distribution

standalone

### Operating System

Windows

**Comment by hubertp** [comment] 2023-05-15 08:29
That seems very much like a duplicate of https://github.com/enso-org/enso/issues/6639

**Comment by Akirathan** [comment] 2023-05-15 12:00
This is a twofold issue:

- The first one is that IDE does have an unnecessarily long rendering of erroneous state.
- The second one is that the protocol between the IDE and Language server is not really ideal for these kinds of things - for rebuilding of a huge count of nodes.

**Closed as completed** 2023-06-14 18:16 UTC
Labels: p-low, --low-performance
