### ISSUE TITLE
`AssertionError` with `payload Error Error.type UnresolvedSymbol<==>` when executing Base_Tests

### ISSUE THREAD

**Issue by hubertp** [enso-org/enso#11127] opened 2024-09-18 21:01 UTC
More info has been added to the reported missing polyglot context assertion (#11113) which resulted in
```
 INFO ide_ci::program::command: cmd ⚠️ Caused by: java.lang.AssertionError: Failed to log failed conversion of null to string and payload Error Error.type UnresolvedSymbol<==>
 INFO ide_ci::program::command: cmd ⚠️ 	at org.enso.runtime/org.enso.interpreter.runtime.error.PanicException.computeMessage(PanicException.java:95)
 INFO ide_ci::program::command: cmd ⚠️ 	at org.enso.runtime/org.enso.interpreter.runtime.error.PanicException.getMessage(PanicException.java:76)
 INFO ide_ci::program::command: cmd ⚠️ 	at org.enso.runtime/org.enso.interpreter.runtime.error.PanicException.toString(PanicException.java:106)
 INFO ide_ci::program::command: cmd ⚠️ 	at java.base/java.lang.Throwable.<init>(Throwable.java:319)
 INFO ide_ci::program::command: cmd ⚠️ 	at java.base/java.lang.Exception.<init>(Exception.java:103)
 INFO ide_ci::program::command: cmd ⚠️ 	at java.base/java.io.IOException.<init>(IOException.java:98)
 INFO ide_ci::program::command: cmd ⚠️ 	at org.enso.IsolatedClassLoader//org.enso.runner.Main.withProfiling(Main.java:1205)
 INFO ide_ci::program::command: cmd ⚠️ 	at org.enso.IsolatedClassLoader//org.enso.runner.Main.launch(Main.java:1450)
 INFO ide_ci::program::command: cmd ⚠️ 	at org.enso.IsolatedClassLoader//org.enso.runner.Main.launch(Main.java:1402)
 INFO ide_ci::program::command: cmd ⚠️ 	at org.enso.IsolatedClassLoader//org.enso.runner.Main.main(Main.java:1019)
 INFO ide_ci::program::command: cmd ⚠️ 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
 INFO ide_ci::program::command: cmd ⚠️ 	... 2 more
 INFO ide_ci::program::command: cmd ⚠️ Caused by: java.lang.AssertionError: No polyglot context is entered. A language or context reference must not be used if there is no polyglot context entered.
 INFO ide_ci::program::command: cmd ⚠️ 	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotFastThreadLocals.assertValidGet(PolyglotFastThreadLocals.java:481)
 ```
- at https://github.com/enso-org/enso/actions/runs/10926101745/job/30329191172#step:7:1251
- at https://github.com/enso-org/enso/actions/runs/11036714355/job/30655819392?pr=10823#step:7:2605

**Comment by radeusgd** [comment] 2024-10-02 13:11
Not sure if that's useful but I encountered such error on CI:
```
INFO ide_ci::program::command: bash ⚠️ Exception in thread "main" java.lang.AssertionError: Failed to log failed conversion of null to string and payload Error Error.type UnresolvedSymbol<==>
 INFO ide_ci::program::command: bash ⚠️ 	at org.enso.runtime/org.enso.interpreter.runtime.error.PanicException.computeMessage(PanicException.java:95)
 INFO ide_ci::program::command: bash ⚠️ 	at org.enso.runtime/org.enso.interpreter.runtime.error.PanicException.getMessage(PanicException.java:76)
 INFO ide_ci::program::command: bash ⚠️ 	at org.enso.runtime/org.enso.interpreter.runtime.error.PanicException.toString(PanicException.java:106)
 INFO ide_ci::program::command: bash ⚠️ 	at java.base/java.lang.Throwable.<init>(Throwable.java:319)
 INFO ide_ci::program::command: bash ⚠️ 	at java.base/java.lang.Exception.<init>(Exception.java:103)
 INFO ide_ci::program::command: bash ⚠️ 	at java.base/java.io.IOException.<init>(IOException.java:98)
 INFO ide_ci::program::command: bash ⚠️ 	at org.enso.runner/org.enso.runner.Main.withProfiling(Main.java:1221)
 INFO ide_ci::program::command: bash ⚠️ 	at org.enso.runner/org.enso.runner.Main.launch(Main.java:1466)
 INFO ide_ci::program::command: bash ⚠️ 	at org.enso.runner/org.enso.runner.Main.launch(Main.java:1418)
 INFO ide_ci::program::command: bash ⚠️ 	at org.enso.runner/org.enso.runner.Main.main(Main.java:1033)
 INFO ide_ci::program::command: bash ⚠️ Caused by: java.lang.AssertionError: No polyglot context is entered. A language or context reference must not be used if there is no polyglot context entered.
 INFO ide_ci::program::command: bash ⚠️ 	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotFastThreadLocals.assertValidGet(PolyglotFastThreadLocals.java:481)
 INFO ide_ci::program::command: bash ⚠️ 	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotFastThreadLocals$ContextReferenceImpl.get(PolyglotFastThreadLocals.java:513)
 INFO ide_ci::program::command: bash ⚠️ 	at org.enso.runtime/org.enso.interpreter.runtime.EnsoContext.get(EnsoContext.java:248)
 INFO ide_ci::program::command: bash ⚠️ 	at org.enso.runtime/org.enso.interpreter.runtime.error.PanicException.computeMessage(PanicException.java:91)
 INFO ide_ci::program::command: bash ⚠️ 	... 9 more
```

**Comment by JaroslavTulach** [comment] 2024-10-03 05:07
Found a way to reproduce the problem:
```ruby
from Standard.Base import all

type LM
    V txt

    to_display_text self =
        res = self.txt + " from exception"
        Panic.throw res

main = Panic.throw (LM.V "Hi")
```
which seems to be fixed by https://github.com/enso-org/enso/pull/11241/commits/a6a858ffa25408c10743aee81c5119cb21b126b6 - reasonable stack is being printed:
```
Execution finished with an error: Hi from exception
        at <enso> Panic.throw(Internal)
        at <enso> LM.to_display_text(p.enso:8:9-23)
        at <enso> Panic.throw(Internal)
        at <enso> p.main(p.enso:10:8-30)
```

**Comment by radeusgd** [comment] 2024-10-15 16:09
I think I still managed to get a similar failure: https://github.com/enso-org/enso/actions/runs/11343381383/job/31545811101?pr=11320#step:7:2162

or is that a different case?

<blockquote><img src="https://opengraph.githubassets.com/0f7437b04babedcdec9e791ca2f0822ab296caa6109c5d55667d9475ee8ce4df/enso-org/enso" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/enso-org/enso">Add `Meta.engine_version` · enso-org/enso@cbf12d8</a></strong></div><div>Hybrid visual and textual functional programming. Contribute to enso-org/enso development by creating an account on GitHub.</div></blockquote>

**Comment by JaroslavTulach** [comment] 2024-10-16 08:00
> I think I still managed to get a similar failure: https://github.com/enso-org/enso/actions/runs/11343381383/job/31545811101?pr=11320#step:7:2162
> or is that a different case?

- yet another failure with the same cause - let's try again: #11334

**Comment by hubertp** [comment] 2024-10-21 08:10
Still happening: 
```
Error: de_ci::program::command: enso ℹ️ [ERROR] [2024-10-21T09:44:52.382] [org.enso.interpreter.runtime.error.PanicException] Cannot compute message for Error Error.type UnresolvedSymbol<==>
 INFO ide_ci::program::command: enso ℹ️ java.lang.AssertionError: No polyglot context is entered. A language or context reference must not be used if there is no polyglot context entered.
 INFO ide_ci::program::command: enso ℹ️ 	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotFastThreadLocals.assertValidGet(PolyglotFastThreadLocals.java:481)
 INFO ide_ci::program::command: enso ℹ️ 	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotFastThreadLocals$ContextReferenceImpl.get(PolyglotFastThreadLocals.java:513)
 INFO ide_ci::program::command: enso ℹ️ 	at org.enso.interpreter.runtime.EnsoContext.get(EnsoContext.java:248)
 INFO ide_ci::program::command: enso ℹ️ 	at org.enso.interpreter.runtime.error.PanicException.toDisplayText(PanicException.java:122)
 INFO ide_ci::program::command: enso ℹ️ 	at org.enso.interpreter.runtime.error.PanicExceptionGen$InteropLibraryExports$Uncached.getExceptionMessage(PanicExceptionGen.java:354)
 INFO ide_ci::program::command: enso ℹ️ 	at org.graalvm.truffle/com.oracle.truffle.api.interop.InteropLibraryGen$Delegate.getExceptionMessage(InteropLibraryGen.java:5000)
 INFO ide_ci::program::command: enso ℹ️ 	at org.graalvm.truffle/com.oracle.truffle.api.interop.InteropLibrary$Asserts.getExceptionMessage(InteropLibrary.java:4755)
 INFO ide_ci::program::command: enso ℹ️ 	at org.graalvm.truffle/com.oracle.truffle.api.interop.InteropLibraryGen$UncachedDispatch.getExceptionMessage(InteropLibraryGen.java:7642)
 INFO ide_ci::program::command: enso ℹ️ 	at org.enso.interpreter.runtime.error.PanicException.computeMessage(PanicException.java:87)
 INFO ide_ci::program::command: enso ℹ️ 	at org.enso.interpreter.runtime.error.PanicException.getMessage(PanicException.java:77)
 INFO ide_ci::program::command: enso ℹ️ 	at org.enso.runner.Main.handleRun(Main.java:764)
 INFO ide_ci::program::command: enso ℹ️ 	at org.enso.runner.Main.mainEntry(Main.java:1135)
 INFO ide_ci::program::command: enso ℹ️ 	at org.enso.runner.Main.lambda$launch$22(Main.java:1479)
 INFO ide_ci::program::command: enso ℹ️ 	at org.enso.runner.Main.withProfiling(Main.java:1225)
 INFO ide_ci::program::command: enso ℹ️ 	at org.enso.runner.Main.launch(Main.java:1475)
 INFO ide_ci::program::command: enso ℹ️ 	at org.enso.runner.Main.launch(Main.java:1426)
 INFO ide_ci::program::command: enso ℹ️ 	at org.enso.runner.Main.main(Main.java:1041)
 INFO ide_ci::program::command: enso ⚠️ Exception in thread "main" java.lang.IllegalArgumentException: Cause exception must extend AbstractTruffleException but was class java.lang.AssertionError.
 INFO ide_ci::program::command: enso ⚠️ 	at org.enso.interpreter.runtime.error.PanicExceptionGen$InteropLibraryExports$Uncached.getExceptionMessage(PanicExceptionGen.java:354)
 INFO ide_ci::program::command: enso ⚠️ 	at org.graalvm.truffle/com.oracle.truffle.api.interop.InteropLibraryGen$Delegate.getExceptionMessage(InteropLibraryGen.java:5000)
 INFO ide_ci::program::command: enso ⚠️ 	at org.graalvm.truffle/com.oracle.truffle.api.interop.InteropLibrary$Asserts.getExceptionMessage(InteropLibrary.java:4755)
 INFO ide_ci::program::command: enso ⚠️ 	at org.graalvm.truffle/com.oracle.truffle.api.interop.InteropLibraryGen$UncachedDispatch.getExceptionMessage(InteropLibraryGen.java:7642)
 INFO ide_ci::program::command: enso ⚠️ 	at org.enso.interpreter.runtime.error.PanicException.computeMessage(PanicException.java:87)
 INFO ide_ci::program::command: enso ⚠️ 	at org.enso.interpreter.runtime.error.PanicException.getMessage(PanicException.java:77)
 INFO ide_ci::program::command: enso ⚠️ 	at org.enso.runner.Main.handleRun(Main.java:764)
 INFO ide_ci::program::command: enso ⚠️ 	at org.enso.runner.Main.mainEntry(Main.java:1135)
 INFO ide_ci::program::command: enso ⚠️ 	at org.enso.runner.Main.lambda$launch$22(Main.java:1479)
 INFO ide_ci::program::command: enso ⚠️ 	at org.enso.runner.Main.withProfiling(Main.java:1225)
 INFO ide_ci::program::command: enso ⚠️ 	at org.enso.runner.Main.launch(Main.java:1475)
 INFO ide_ci::program::command: enso ⚠️ 	at org.enso.runner.Main.launch(Main.java:1426)
 INFO ide_ci::program::command: enso ⚠️ 	at org.enso.runner.Main.main(Main.java:1041)
TRACE ide_ci::program::command: enso ⚠️ <ENDUT>
```
https://github.com/enso-org/enso/actions/runs/11435268254/job/31810327386

<blockquote><img src="https://opengraph.githubassets.com/f6f14309ddacb23b57e9c8f99fbc585186ef8b7229e4d4fdf279b4ac3b6e4e45/enso-org/enso" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/enso-org/enso">Copying and pasting in Grid fixes. (#11332) · enso-org/enso@fa87a18</a></strong></div><div>Hybrid visual and textual functional programming. Contribute to enso-org/enso development by creating an account on GitHub.</div></blockquote>

**Comment by JaroslavTulach** [comment] 2024-10-24 04:57
The latest change #11393 is trying to extract as much information from

> [org.enso.interpreter.runtime.error.PanicException] Cannot compute message for Error Error.type UnresolvedSymbol<==>

as possible. E.g. print out the `location` of the error including type of the node. That's certainly not a fix, but may get us further in the investigation.

**Closed as completed** 2024-10-29 14:47 UTC
Labels: -compiler
