### ISSUE TITLE
Changing `first` to `last` by editing a node and accepting with `Enter` is not possible

### ISSUE THREAD

**Issue by sylwiabr** [enso-org/enso#6491] opened 2023-05-01 13:17 UTC
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

https://user-images.githubusercontent.com/12892578/235456361-b0d5905a-15bf-4824-ad94-60b49e2d3bf1.mov

1. add a vector
2. add another node and choose `.first`
3. edit the second node and type `last` instead of `first`
4. try to accept with `Enter`

### Expected behaviour

Since this is a valid enso function that should be visible and choosable in CB `Enter` should be enough

### Enso Version

develop @ 6b0c682b08b7745368cec3474cc774c51a5b48f5

### Browser or standalone distribution

Standalone distribution

### Browser Version or standalone distribution

Standalone

### Operating System

MacOS

**Comment by farmaazon** [comment] 2023-05-02 08:03
This will be fixed by having support for `this` argument in CB: https://github.com/enso-org/enso/issues/5232

**Comment by farmaazon** [comment] 2023-05-02 08:05
Closing as sort of duplicate of https://github.com/enso-org/enso/issues/5232

**Closed as not planned** 2023-05-02 08:05 UTC
Labels: s-duplicate, --bug
