### ISSUE TITLE
Double clicking while editing a node text is triggering the "Entering node" which then causes "File not found" error

### ISSUE THREAD

**Issue by sylwiabr** [enso-org/enso#6829] opened 2023-05-24 12:06 UTC
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

When editing a node double-clicking to select the text on the node is triggering "Entering node"which then causes "File not found error".

### Expected behaviour

Double-clicking to select text should not trigger entering the node.

### Enso Version

Nightly 24.05

### Browser or standalone distribution

Standalone distribution (local project)

### Browser Version or standalone distribution

Standalone

### Operating System

MacOS

**Comment by farmaazon** [comment] 2023-05-24 12:13
PRobably just a one-liner:
```diff
diff --git a/app/gui/view/graph-editor/src/shortcuts.rs b/app/gui/view/graph-editor/src/shortcuts.rs
index 951499cd6..1f9d58eca 100644
--- a/app/gui/view/graph-editor/src/shortcuts.rs
+++ b/app/gui/view/graph-editor/src/shortcuts.rs
@@ -51,7 +51,7 @@ pub const SHORTCUTS: &[(ensogl::application::shortcut::ActionType, &str, &str, &
         "ctrl space",
         "cycle_visualization_for_selected_node",
     ),
-    (DoublePress, "!read_only", "left-mouse-button", "enter_hovered_node"),
+    (DoublePress, "!read_only", "!node_editing", "left-mouse-button", "enter_hovered_node"),
     (DoublePress, "!read_only", "left-mouse-button", "start_node_creation_from_port"),
     (Press, "!read_only", "right-mouse-button", "start_node_creation_from_port"),
     (Press, "!node_editing & !read_only", "cmd enter", "enter_selected_node"),
```

**Comment by hubertp** [comment] 2023-05-25 08:43
But it's kind of a duplicate of https://github.com/enso-org/enso/issues/6763, isn't it? And even if we go with this patch, I hope we can still fix the other one or it can manifest itself under some obscure scenario.

**Comment by farmaazon** [comment] 2023-05-25 09:23
They are a bit different, though.

This task is about: "Double-clicking to select text should not trigger entering the node." (as Sylwia wrote). 

The task you mentioned is more about "If we try to enter the node and it will fail, we should pop the frame back". It should be working regardless if the node was edited or not.

**Closed as completed** 2023-05-31 08:23 UTC
Labels: d-easy, --bug
