### ISSUE TITLE
Node preview unexpected behavior of disappearing correct data preview followed by error on the node 

### ISSUE THREAD

**Issue by xvcgreg** [enso-org/enso#6623] opened 2023-05-10 07:03 UTC
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

When writing a function (in this case lambda), after the final syntax is done (and no further changes in the code are made), for a split second I'm getting correct preview under the node but then it disappears with an error on the node. Then when I confirm node creation (still with no changes in the code) it recomputes and shows again proper results in the preview and error disappears.

https://github.com/enso-org/enso/assets/108271897/e1f7d910-3641-4aa8-af9d-0bb2b25b09c3

### Expected behaviour

After the lambda is done, preview of the data is shown - and it stays that way (if the code is correctly written), without errors.

### How we can reproduce it?

follow the movie

### Screenshots or screencasts

https://github.com/enso-org/enso/assets/108271897/2b53e352-4681-49b3-8b1d-d0db7608eda6

### Enso Version

2023.5.9 nightly

### Browser or standalone distribution

Standalone distribution

### Browser Version or standalone distribution

standalone

### Operating System

Windows

### Operating System Version

Win11pro 22H2 22621.1555

### Hardware you are using

12th Gen Intel(R) Core(TM) i9-12900HK / RTX3060 Laptop / Nvidia Drivers 531.68

**Comment by vitvakatu** [comment] 2023-05-10 07:13
After you close the bracket, the CB selects the `from_vector` entry, so the code is probably modified to preview this suggestion. That's why the node fails to show any visualization - AST becomes incorrect.

**Comment by xvcgreg** [comment] 2023-05-10 07:51
@vitvakatu yes, it happens many times. In some scenarios, it's a desired behavior - but mostly it renders the preview useless. How can we fix that? So the user will know that adding what he/she has (not) selected in the CB is the new output of the node computation result. Making the selection of component a conscious decision (requiring user action (mouse movement, arrow key press)) to reevaluate the previously correct code into an error state with new results served to the preview window.

**Comment by farmaazon** [comment] 2023-05-10 08:09
The possible solutions are described in https://github.com/enso-org/enso/issues/6486 Actually, this task is actually a duplicate of that.

**Closed as not planned** 2023-05-10 08:12 UTC
Labels: s-duplicate, --bug
