### ISSUE TITLE
It is not possible to type Polish characters in an Enso node

### ISSUE THREAD

**Issue by radeusgd** [enso-org/enso#7155] opened 2023-06-28 23:03 UTC
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

I was trying to analyse my bank transaction data, and wanted to filter out transactions made to my other account by my name - `Radosław`. It contains `ł` character. I was unable to type my name into an Enso node - clicking `alt+l` as usually does nothing (not even just `l` is inserted).

### Expected behaviour

I should be able to enter all characters my current keyboard layout allows, including special diacritic characters.

### How we can reproduce it?

1. Set your keyboard settings to "Polish (programmers)".
2. Create a new Enso node.
3. Try typing `"aąęłś`.
4. Notice how only `"a` show up on the node.

### Enso Version

built from develop yesterday

### Browser or standalone distribution

Standalone distribution (local project)

### Browser Version or standalone distribution

standalone

### Operating System

Windows

### Operating System Version

Windows 11

**Comment by Akirathan** [comment] 2023-06-29 06:42
Closing as duplicate of #7139

**Comment by farmaazon** [comment] 2023-06-29 07:50
I think they are a bit different. The #7139 says about inserting special characters with Alt+NumPad (which is windows-specific), while here we have not working modifier for letter `l` on Polish keyboard.

**Comment by farmaazon** [comment] 2023-06-29 07:58
I cannot reproduce it on Linux.

**Comment by farmaazon** [comment] 2023-06-29 08:10
But indeed, on Windows 11 it's reproducible.

Workaround: Use `~ + l`

**Comment by wdanilo** [comment] 2023-07-03 22:16
It works on my Mac. I can type Polish characters on nodes here.

**Comment by farmaazon** [comment] 2024-03-04 11:19
No longer an issue in GUI2

**Closed as not planned by farmaazon** 2024-03-04 11:19 UTC
Labels: d-easy, p-lowest, --bug
