### ISSUE TITLE
Preview no longer displayed in Component Browser

### ISSUE THREAD

**Issue by radeusgd** [enso-org/enso#7280] opened 2023-07-13 09:39 UTC
I'm not sure if this is intended or not, but I seem to observe that I no longer see the preview that used to show up when selecting components in the component browser.

See the video below:

https://github.com/enso-org/enso/assets/1436948/f4aebd5b-af5d-4fdf-bd93-5a0b40f66f0e

When I type/select components, I see a white visualization box (but sometimes it disappears afterwards), but it stays empty.

Is that an intended change?

**Comment by farmaazon** [comment] 2023-07-13 11:06
Duplicate of #7006

**Closed as not planned** 2023-07-13 11:07 UTC
Labels: s-duplicate
