### ISSUE TITLE
Missing node connection

### ISSUE THREAD

**Issue by xvcgreg** [enso-org/enso#6615] opened 2023-05-09 12:40 UTC
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

I don't see the connection between nodes while I create ``at`` with some lambda.

### Expected behaviour

Connection between nodes is present.

### How we can reproduce it?

create ``at`` from table
with ``column`` -> ``column``*``column``

ie: ``at 2 -> 2*8``

### Screenshots or screencasts

https://github.com/enso-org/enso/assets/108271897/e33064c6-375b-4c5a-b868-7dccad42f41f

### Enso Version

2023.5.9 nightly

### Browser or standalone distribution

Standalone distribution

### Browser Version or standalone distribution

standalone

### Operating System

Windows

### Operating System Version

Win11pro 22H2 22621.1555

### Hardware you are using

12th Gen Intel(R) Core(TM) i9-12900HK / RTX3060 Laptop / Nvidia Drivers 531.68

**Comment by farmaazon** [comment] 2023-05-10 08:00
It seems to be connected with treating node as a single port. See https://github.com/enso-org/enso/issues/6608#issuecomment-1541528332

**Comment by Akirathan** [comment] 2023-05-15 10:16
Closing as duplicate of #6608

**Closed as completed** 2023-05-15 10:16 UTC
Labels: --bug
