### ISSUE TITLE
New project may temporarily disappear from the dashboard

### ISSUE THREAD

**Issue by hubertp** [enso-org/enso#11784] opened 2024-12-05 15:22 UTC
As per video:
[Kazam_screencast_00021.webm](https://github.com/user-attachments/assets/0e7695ed-dd16-42fa-83e0-c17f23549e76)

I suspect this interferes with the request that fetches the list of projects where the *just initialized* one is still missing in the response.
Eventually it will re-appear but this behavior leaves a bitter taste. It happens occasionally.

**Comment by PabloBuchu** [comment] 2024-12-05 16:06
Weird can't reproduce this. I assume its Linux with todays `develop`?

**Comment by hubertp** [comment] 2024-12-08 23:03
> Weird can't reproduce this. I assume its Linux with todays `develop`?

Nightly from 12/03. Also related, when I rename a project and almost immediately close it the old name persists for some (short) time. It seems clearly that this is dependent on the refresh rate of the dashboard. I don't believe it should. Whenever someone goes back to the dashboard from the project they want to see the latest list _immediately_.

**Comment by PabloBuchu** [comment] 2024-12-11 13:36
I will close this one as it is part of bigger problem with request <-> response flow. It is more visible when you try to remove couple of directories or clear trash with lots of assets. Progress can be followed here: https://github.com/enso-org/cloud-v2/issues/1627

**Closed as not planned by PabloBuchu** 2024-12-11 13:36 UTC
Labels: triage, g-dashboard, -gui
