### ISSUE TITLE
Node connection not drawn

### ISSUE THREAD

**Issue by xvcgreg** [enso-org/enso#6608] opened 2023-05-08 17:48 UTC
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

I have created ``at`` with some experimental lambda on columns and when I tried to connect a node to the input port in the ``at`` node it started treating entire node as a port.

### Expected behaviour

Ability to connect another node to the input port of ``at``

### How we can reproduce it?

folow the movie

### Screenshots or screencasts

https://user-images.githubusercontent.com/108271897/236894370-357885fe-a2f2-4588-91dc-20ebc29f0450.mp4

### Enso Version

2023.5.6 nightly

### Browser or standalone distribution

Standalone distribution

### Browser Version or standalone distribution

standalone

### Operating System

Windows

### Operating System Version

Win11pro 22H2 22621.1555

### Hardware you are using

12th Gen Intel(R) Core(TM) i9-12900HK / RTX3060 Laptop / Nvidia Drivers 531.68

**Comment by wdanilo** [comment] 2023-05-09 09:23
1. Greg, the things that you describe are 2 separate issues. The thing that the whole node is treated as an input is a known issue.
2. The second issue needs logs. Could you please divide this issue into 2 reports and always in such cases show on your video logs from console, please? You can open the console with a shortcut. Without logs, it's impossible to triage such reports.

**Comment by xvcgreg** [comment] 2023-05-09 12:05
1. Sure, it seemed connected. I'll create a separate issue for the connection not being drawn.
2. Here's the updated video with the logs, and a panic catch:


https://github.com/enso-org/enso/assets/108271897/862cfe98-44ad-410f-b0f3-5f8816067048

re-recorded with 2023.5.9 Nightly build

**Comment by farmaazon** [comment] 2023-05-10 07:59
Isn't the parser taking the entire left side of `->` as a part of the lambda definition? Lambdas are not yet supported in span tree, thence the entire node turns into port. This is also the cause of missing connection (#6615)

Thence also goes the panics: as `operator.at a` is not a valid lambda argument definition.

I always considered it "by design", and put the lambda in parentheses or without spaces, like 
```operator.at column->column*column```

If it is not by design, then the thing must be fixed in the parser @kazcw also cc @wdanilo

**Comment by Akirathan** [comment] 2023-05-15 10:17
There is another screencast in #6615, which is a duplicate of this issue.

**Comment by wdanilo** [comment] 2023-05-16 11:30
@farmaazon you are 100% right. the left side of `->` is the lambda header and the node in this issue is not valid. We are not supporting displaying connections ot inside of lambda body right now, and there is a ticket for that, so I'm closing this issue as not valid.

**Closed as completed by wdanilo** 2023-05-16 11:30 UTC
Labels: s-invalid, --bug

**Comment by xvcgreg** [comment] 2023-05-16 11:39
> @farmaazon you are 100% right. the left side of `->` is the lambda header and the node in this issue is not valid. We are not supporting displaying connections ot inside of lambda body right now, and there is a ticket for that, so I'm closing this issue as not valid.

@wdanilo  is ``operatro57`` (you can observe it in my original post in the video) treated as lambda header?

**Comment by wdanilo** [comment] 2023-05-16 11:52
Yes
