### ISSUE TITLE
Input ports wrongly displayed on higher order functions

### ISSUE THREAD

**Issue by radeusgd** [enso-org/enso#6961] opened 2023-06-06 08:19 UTC
The IDE should not display input ports for functions passed as argument to another function.

-------

When I pass a function to a higher-order function like `map`, the input ports for the arguments of that passed function are displayed on the node. That is invalid.

<img width="561" alt="image" src="https://github.com/enso-org/enso/assets/1436948/d592f8b7-94cd-4cfe-b148-7951b7c2afbf">

All the grey input ports displayed here are wrong - these are arguments to the functions that are passed as argument to `map`, they cannot be applied here.

They can confuse the user suggesting that they can create connections to these ports. But if the user tries to create the connection, they'll get:
<img width="308" alt="image" src="https://github.com/enso-org/enso/assets/1436948/488fe0ca-a6bb-4de4-90da-1f50190b18fa">
<img width="268" alt="image" src="https://github.com/enso-org/enso/assets/1436948/f476e07d-2c74-4f03-a025-d2bd52968203">

That is because connecting to these nodes creates code like:
```
var3.map Aggregate_Column.Group_By "X"
var2.map var4.get 0
```
which is NOT
```
var3.map (Aggregate_Column.Group_By "X")
var2.map (var4.get 0)
```
BUT
```
(var3.map Aggregate_Column.Group_By) "X"
(var2.map var4.get) 0
```

**Comment by farmaazon** [comment] 2023-06-06 09:43
At some part, this is a duplicate of [#6776](https://github.com/enso-org/enso/issues/6776)

I'd say that with the above task, we should keep the gray ports. Sometimes you want to pass a partially applied function to `map` (I did it multiple times in the bookclub, like `operator11.map (Main.func1 var1 var2)` where func1 takes 3 arguments). Also, with the new design, the user should clearly see that the given placeholder is for `get`, not for `map`.

**Comment by Akirathan** [comment] 2023-06-07 07:15
Closing as duplicate of #6776

**Closed as not planned by Akirathan** 2023-06-07 07:15 UTC
Labels: --bug
