### ISSUE TITLE
CB is sending a wrong text to the backend 

### ISSUE THREAD

**Issue by sylwiabr** [enso-org/enso#7357] opened 2023-07-20 12:03 UTC
### What type of issue is this?

Intermittent – Occurring irregularly

### Is this issue blocking you from using Enso?

- [X] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

Pretty often when I am typing in the CB and pressing `enter` I'm getting error in the console. I.e. I was searching for `year` and added a node with `year` but in the console got error:
```
Execution failed in context 7645b41a-e40c-410d-896c-dcddbc9f6e25. Error: Method `yearr9` of type Date could not be found..
```
I have tried to edit a node, reconnect nodes, remove an
<img width="1374" alt="Zrzut ekranu 2023-07-20 o 13 55 02" src="https://github.com/enso-org/enso/assets/12892578/62705bd2-a3ce-47b1-b2f8-97dfec33474e">
I tried add nodes but nothing was evaluated anymore. 
(```[ERROR] app/gui/src/model/project/synchronized.rs:585 Execution failed in context 7645b41a-e40c-410d-896c-dcddbc9f6e25. Error: org.enso.interpreter.runtime.control.ThreadInterruptedException.```)

### Expected behaviour

IDE should sent the text visible on the node to the backend and backend should keep evaluating.

### Enso Version

nightly 20.07

### Browser or standalone distribution

Standalone distribution (local project)

### Browser Version or standalone distribution

standalone

### Operating System

MacOS

**Comment by sylwiabr** [comment] 2023-07-21 13:15
it looks like LS is being terminated 
```[error] [2023-07-21T13:10:52.634Z] [org.enso.languageserver.search.SuggestionsHandler] Cannot Add [Local(externalId=Some(fa6696ed-9e4c-4f79-b2db-feb979ab9fd6),module=local.Bookclub_11_07.Main,name=operato
r12,returnType=Standard.Base.Any.Any,scope=Scope(Position(7,7),Position(19,31)),documentation=None)].
[error] [2023-07-21T13:10:52.65Z] [org.enso.languageserver.search.SuggestionsHandler] Cannot Add [Local(externalId=Some(fa6696ed-9e4c-4f79-b2db-feb979ab9fd6),module=local.Bookclub_11_07.Main,name=operator
12,returnType=Standard.Base.Any.Any,scope=Scope(Position(7,7),Position(19,31)),documentation=None)].
[warn] [2023-07-21T13:11:11.625Z] [enso] Visualization evaluation failed: Method `fi
` of type Column could not be found..
[warn] [2023-07-21T13:11:21.227Z] [enso] Visualization evaluation failed: Compile error: The name `No` could not be found..
[warn] [2023-07-21T13:11:21.79Z] [enso] Visualization evaluation failed: Compile error: The name `Not` could not be found..
[warn] [2023-07-21T13:11:22.648Z] [enso] Attempt to serialize the module [{}] at stage [{}].
[warn] [2023-07-21T13:11:24.592Z] [org.enso.projectmanager.infrastructure.languageserver.LanguageServerController] Received unknown message: class org.enso.projectmanager.infrastructure.languageserver.LanguageServerProcess$ServerTerminated
[error] [2023-07-21T13:11:26.449Z] [org.enso.projectmanager.infrastructure.languageserver.HeartbeatSession] An error occurred during connecting to websocket Socket(127.0.0.1,53156). Connection failed.
[error] [2023-07-21T13:11:26.449Z] [org.enso.projectmanager.infrastructure.languageserver.HeartbeatSession] An error occurred during closing web socket.
akka.stream.StreamTcpException: Some(Tcp command [Connect(127.0.0.1/<unresolved>:53156,None,List(),Some(10 seconds),true)] failed because of java.net.ConnectException: Connection refused)
Caused by: java.net.ConnectException: Some(Connection refused)
  at java.base@17.0.6/sun.nio.ch.Net.pollConnect(Net.java)
  at java.base@17.0.6/sun.nio.ch.Net.pollConnectNow(Net.java:672)
  at java.base@17.0.6/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:946)
  at akka.io.TcpOutgoingConnection$$anonfun$connecting$1.$anonfun$applyOrElse$4(TcpOutgoingConnection.scala:111)
  at akka.io.TcpOutgoingConnection.akka$io$TcpOutgoingConnection$$reportConnectFailure(TcpOutgoingConnection.scala:53)
  at akka.io.TcpOutgoingConnection$$anonfun$connecting$1.applyOrElse(TcpOutgoingConnection.scala:111)
  at akka.actor.Actor.aroundReceive(Actor.scala:537)
  at akka.actor.Actor.aroundReceive$(Actor.scala:535)
  at akka.io.TcpConnection.aroundReceive(TcpConnection.scala:33)
  at akka.actor.ActorCell.receiveMessage(ActorCell.scala:579)
  at akka.actor.ActorCell.invoke(ActorCell.scala:547)
  at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:270)
  at akka.dispatch.Mailbox.run(Mailbox.scala:231)
  at akka.dispatch.Mailbox.exec(Mailbox.scala:243)
  at java.base@17.0.6/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
  at java.base@17.0.6/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
  at java.base@17.0.6/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
  at java.base@17.0.6/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
  at java.base@17.0.6/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
  at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:775)
  at org.graalvm.nativeimage.builder/com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:203)
[info] [2023-07-21T13:11:26.449Z] [org.enso.projectmanager.infrastructure.languageserver.LanguageServerSupervisor] Server is unresponsive. Restarting [LanguageServerConnectionInfo(127.0.0.1,53156,58959)].
[info] [2023-07-21T13:11:26.45Z] [akka.actor.LocalActorRef] Message [org.enso.projectmanager.infrastructure.languageserver.package$Restart$] from Actor[akka://project-manager/user/language-server-registry/language-server-controller-ca15a064-7122-4bdb-96d7-93a5f26ace2b/supervisor-language-server-ca15a064-7122-4bdb-96d7-93a5f26ace2b#1608146849] to Actor[akka://project-manager/user/language-server-registry/language-server-controller-ca15a064-7122-4bdb-96d7-93a5f26ace2b/bootloader-language-server-ca15a064-7122-4bdb-96d7-93a5f26ace2b#-254813189] was not delivered. [1] dead letters encountered, no more dead letters will be logged in next [5.000 min]. If this is not an expected behavior then Actor[akka://project-manager/user/language-server-registry/language-server-controller-ca15a064-7122-4bdb-96d7-93a5f26ace2b/bootloader-language-server-ca15a064-7122-4bdb-96d7-93a5f26ace2b#-254813189] may have terminated unexpectedly. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
```
cc @4e6

**Comment by farmaazon** [comment] 2023-07-24 07:17
@4e6 Do you know what happens there? From the description, I see rather a GUI problem, but I see you and Hubert are assigned.

**Comment by 4e6** [comment] 2023-07-25 21:26
@farmaazon You're right, looks like the error is happening because of the wrong updates sent. I'll transfer it to the GUI

**Comment by farmaazon** [comment] 2023-07-27 09:42
When trying to reproduce it, I found that there _is_ some issue in the engine: each time I type non-existing method, I get a Panic (what is expected), but also execution failure:

```[ERROR] app/gui/src/model/project/synchronized.rs:585 Execution failed in context e216ea42-f9e5-4562-b93c-9e8396a0a4b2. Error: Execution of function main failed (Null receiver values are not supported by libraries.)..```

This display "Execution failed..." message in the engine.

Shall I report it as a separate issue @4e6 ?

**Comment by farmaazon** [comment] 2023-07-27 10:29
@sylwiabr I cannot reproduce it. Do you still? Do you have any project where it may happen more frequently?

**Comment by sylwiabr** [comment] 2023-08-04 09:37
I don't have repro but here is a console log as it just happened again (was choosing order_by by pressing enter in the CB and it sent order_byr15 to the backend)

[20230804-080206-882-enso-project-manager.log](https://github.com/enso-org/enso/files/12259422/20230804-080206-882-enso-project-manager.log)
[localhost-1691141689884.log](https://github.com/enso-org/enso/files/12259349/localhost-1691141689884.log)

[New_Project_12.zip](https://github.com/enso-org/enso/files/12259357/New_Project_12.zip)

**Comment by hubertp** [comment] 2023-08-08 09:28
@farmaazon `error: Execution of function main failed (Null receiver values are not supported by libraries.)` Those are now fixed in the latest nightly and confirmed by @sylwiabr. Let me know if there are any further problems on the engine side.

**Comment by farmaazon** [comment] 2024-03-06 09:53
Haven't seen any problem of such kind in new GUI2 (except unnecessary error logs about preview expression).

**Closed as not planned by farmaazon** 2024-03-06 09:53 UTC
Labels: p-medium, --bug, --regression
