### ISSUE TITLE
Two cursors visible at once & Table visualization does not interact with Enso cursor

### ISSUE THREAD

**Issue by radeusgd** [enso-org/enso#7518] opened 2023-08-08 12:04 UTC
This is kind of two issues but they seem very interconnected, so I'm reporting as one, may be split if needed.

https://github.com/enso-org/enso/assets/1436948/cc9a3d15-22cd-4333-bdc9-348270565b44

As can be seen on the video, I have two problems:
1. From time to time, especially when manipulating the Table visualization I get into a state where both the Enso-circle-cursor and the native Windows cursor are visible at once. This is not an usability itself but looks bad.
2. It seems that the Table visualization does not react to the Enso-circle-cursor. I tried changing column widths - a common thing to do, especially as some columns in the example were very narrow. I could not do that _at all_ with the Enso cursor. 

If I open the full-screen visualization, I for a moment see both cursors - then I can change column widths. But after one click (first width change), the cursor disappears and I cannot interact anymore - I have to close the full-screen vis and reopen it again to gain the Windows cursor that allows me to manipulate.

Similarly, in the non-fullscreen 'embedded' mode, the visualization does not react to Enso cursor. There I can 'just' click outside of the vis and then again inside of it to 'gain' the Windows native cursor and be able to interact.

Due to these issues it is hard to resize columns in the table.

**Comment by radeusgd** [comment] 2023-08-08 12:07
> Note: the awful flickering has started to happen since a few weeks, I did not have it before. Fortunately, it is only visible on the recording - when I was using the app, even during recording, on the live screen no flickering like this was _fortunately_ happening - so it's only an artifact of the recording. Still a weird thing, especially, as it did not happen in the past (+- I remember it started happening in the same time as the IDE colors changed from white-ish to yellow-ish - probably not an issue of colors, but maybe some related changes around that time)

**Comment by vitvakatu** [comment] 2023-08-09 08:22
I'll check this one in about one hour and bisect if necessary.

**Comment by vitvakatu** [comment] 2023-08-09 14:11
Further discussion of the issue with fullscreen vis goes to #7524. Two issues described here are much older, I continue bisecting.

1. System cursor and the Enso cursor intermixed - visual issue indeed. 
2. You can resize visualization columns only when the visualization is focused. That's why you need to click it to be able to resize columns (and to see the system cursor). Initially, I thought it was not an issue. __However__, after opening a project, it is possible to resize columns, even when the visualization is unfocused (there is no blue border around it).

**Comment by vitvakatu** [comment] 2023-08-09 14:25
I checked commit from 5th of July, and both these issues are present there as well. Did it work otherwise at all?
I find further bisecting pointless.

@jdunkerley and @farmaazon, 
1. What is the intended behavior here? 
1. Should we focus visualizations on hover? 
2. What cursor should we show in visualizations, system's or Enso's?

**Comment by jdunkerley** [comment] 2023-09-01 10:23
We should just be using the system cursor - if fixable easily then we should do as part of Beta otherwise will be part of the JS IDE rewrite.

**Comment by farmaazon** [comment] 2024-02-23 14:36
In new GUI, only system cursor is displayed.

**Closed as not planned by farmaazon** 2024-02-23 14:36 UTC
Labels: s-invalid, p-lowest, --bug
