### ISSUE TITLE
Visualization gets stuck after invalid input

### ISSUE THREAD

**Issue by kazcw** [enso-org/enso#5812] opened 2023-03-04 15:08 UTC
### What type of issue is this?

Permanent – Ocurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

- Create a new node with the (+). [By default, a visualization is shown.]
- Type something that isn't a prefix of any valid function name, e.g. `loaa`.
- [The visualization shows the output of a near-match from the component browser:]
![image](https://user-images.githubusercontent.com/1047859/222913470-1806f859-e19f-45e1-ba05-52bad221bca4.png)
- Commit the node.
- If you edit the node again, the visualization doesn't change anymore.

### Expected behaviour

~~When a node yields an error, we normally hide the visualization. However, when a node is still being created, the visualization is always shown until node creation is completed, and it can contain nonsense. We could treat an invalid expression in a newly-created still-edited node as an error the same way as we would in a committed node, or we could change the text displayed to an error message, but we shouldn't show the user the current value.~~

Visualization should not get stuck.

### Enso Version

f64edd806d4de7e71e6b1fea41a13ac189ebfadd

### Browser or standalone distribution

Standalone distribution

### Browser Version or standalone distribution

standalone

### Operating System

Linux

**Comment by kazcw** [comment] 2023-03-04 15:12
After this happens, the visualization gets stuck. Changing the node to a valid expression doesn't change the visualization.

**Comment by farmaazon** [comment] 2023-03-06 08:43
The behavior described in "What issue are you facing" is actually expected. The visualization preview is previewing the _selected component_, not the _input_. As writing `loaa` selects `multipart_form_data`, the preview is actually sensible.

Regarding "the visualization gets stuck" - Seems to be an issue,

**Comment by hubertp** [comment] 2023-03-08 15:31
Feel free to distribute in your team, @farmaazon

**Comment by farmaazon** [comment] 2023-05-02 11:14
The previews should work better with new cursor-aware CB, and the stuck visualization wasn't reproduced for a long time. Closing.

**Closed as not planned by farmaazon** 2023-05-02 11:14 UTC
Labels: s-no-repro, p-medium, --bug, -viz
