### ISSUE TITLE
Default dropdown for `join_kind` did not work and killed the backend

### ISSUE THREAD

**Issue by radeusgd** [enso-org/enso#5565] opened 2023-02-06 12:55 UTC
### Steps to Reproduce

1. Load the 2 tables from week 5 of bookclub.
2. Select the one with grades, type `join` and then connect the other one to `right`.
3. Open the dropdown for `join_kind` and select `Standard.Table.Data.Join_Kind.Full`.

### Expected Result

I should get a full join.

### Actual Result

I got the following error:

<img width="882" alt="image" src="https://user-images.githubusercontent.com/1436948/216976120-8f715987-8890-414f-8703-e53b8a92103b.png">

It's confusing because I remember that @hubertp already implemented fully-qualified-name resolution. What is suspicious however is that knowing the stdlib, I think the correct FQN for this should be `Standard.Table.Data.Join_Kind.Join_Kind.Full` (note the double `Join_Kind` in the path - the first is filename and the second one is the type itself). For some reason the path detected automatically by the dropdown (I assume through the `tagValues` system) had only one `Join_Kind` in it, making it wrong. However the error is even more confusing as it talks about `Data` being missing...

I tried to then edit the node manually with Ctrl+LMB, removing the `Standard.Table.Data` prefix and confirming with Ctrl+Enter.

<img width="404" alt="image" src="https://user-images.githubusercontent.com/1436948/216976324-b4160828-43f2-419a-a7c3-8b870c8b7624.png">

This edit however seems to not have been applied as the error persisted.

<img width="422" alt="image" src="https://user-images.githubusercontent.com/1436948/216976433-5ec6a9ec-51cc-4b96-baa2-e4e102cf67a6.png">

And it seems that this has managed to successfully kill the backend (or at least render it unusable) as no further nodes managed to compute the result.

Logs:
```
                      .\Enso.exe
PS C:\NBO\ide-builds>
Starting the backend process with the following options: []
Project Manager has been spawned, pid = 24496.
Starting the IDE service.
f [AsyncFunction: createServers]
Starting the IDE client.
[info] [2023-02-06T12:50:14.18Z] [org.enso.projectmanager.boot.ProjectManager$] Starting Project Manager...
Loading the window address http://localhost:8080?platform=win32&frame=true&theme=light&darkTheme=true&dataGathering=true&preferredEngineVersion=2023.1.1-dev&enableNewComponentBrowser=true&emitUserTimingMeasurements=undefined&nodeLabels=true&debug=false
Server started on port 8080.
Serving files from 'C:\NBO\ide-builds/C:\NBO\ide-builds\resources\app.asar'.
[info] [2023-02-06T12:50:14.431Z] [org.enso.projectmanager.boot.ProjectManager$] Started server at 127.0.0.1:30535, press enter to kill server
[info] [2023-02-06T12:50:15.229Z] [org.enso.projectmanager.protocol.ClientController] Client connected to Project Manager [fb368b56-292c-427a-be7c-4c6a913dc6c5]
[info] [2023-02-06T12:50:17.601Z] [org.enso.runtimeversionmanager.components.RuntimeVersionManager] The engine [2023.1.1-dev] found.
[info] [2023-02-06T12:50:17.697Z] [org.enso.runtimeversionmanager.components.RuntimeVersionManager] Found GraalVM runtime [GraalVM 22.3.0-java11].
[info] [2023-02-06T12:50:17.701Z] [org.enso.projectmanager.infrastructure.languageserver.LanguageServerBootLoader] Booting a language server [LanguageServerDescriptor(language-server-8046f46c-21b9-4b9f-aa07-a08f04d58789,733273a3-4994-49d3-8c83-79d87c3505b5,C:\Users\progr\enso\projects\Unnamed_2,NetworkConfig(127.0.0.1,49152,65535),org.enso.projectmanager.versionmanagement.DefaultDistributionConfiguration$@c312732,2023.1.1-dev,JVMSettings(None,List()),false,None,None,None,Future(Success(Some(ws://localhost:51957/))))].
[info] [2023-02-06T12:50:17.701Z] [org.enso.projectmanager.infrastructure.languageserver.LanguageServerBootLoader] Found sockets for the language server [json:127.0.0.1:63534, binary:127.0.0.1:53278].
[info] [2023-02-06T12:50:17.702Z] [org.enso.runtimeversionmanager.components.RuntimeVersionManager] The engine [2023.1.1-dev] found.
[info] [2023-02-06T12:50:17.769Z] [org.enso.runtimeversionmanager.components.RuntimeVersionManager] Found GraalVM runtime [GraalVM 22.3.0-java11].
[info] [2023-02-06T12:50:18.994Z] [org.enso.languageserver.boot.LanguageServerComponent] Starting Language Server...
[info] [2023-02-06T12:50:19.006Z] [org.enso.languageserver.boot.MainModule] Initializing main module of the Language Server from [LanguageServerConfig(127.0.0.1,63534,53278,733273a3-4994-49d3-8c83-79d87c3505b5,C:\Users\progr\enso\projects\Unnamed_2,ProfilingConfig(None,None,None),language-server,scala.concurrent.impl.ExecutionContextImpl$$anon$3@6aa3a905[Running, parallelism = 20, size = 2, active = 0, running = 1, steals = 0, tasks = 0, submissions = 0]), info]
[info] [2023-02-06T12:50:20.73Z] [org.enso.languageserver.runtime.RuntimeConnector] Starting the runtime connector.
[info] [2023-02-06T12:50:20.73Z] [org.enso.languageserver.runtime.RuntimeConnector] Runtime connector established connection with the message endpoint [com.oracle.truffle.api.instrumentation.TruffleInstrument$Env$MessageTransportProxy$MessageEndpointProxy@2e491329].
[info] [2023-02-06T12:50:20.861Z] [org.enso.languageserver.text.BufferRegistry] Starting initialization.
[info] [2023-02-06T12:50:20.87Z] [org.enso.languageserver.search.SuggestionsHandler] Starting suggestions handler from [Config(projectContentRoot=***\Unnamed_2, fileManager=FileManagerConfig(3 seconds,20), vcsManager=VcsManagerConfig(5 seconds,3 seconds), pathWatcher=PathWatcherConfig(5 seconds,5 seconds,10), executionContext=ExecutionContextConfig(5 seconds), directories=DirectoriesConfig(***\Unnamed_2)), org.enso.searcher.sql.SqlSuggestionsRepo@504fb797, org.enso.searcher.sql.SqlVersionsRepo@69804dd3].
[info] [2023-02-06T12:50:21.455Z] [org.enso.languageserver.boot.MainModule] Main module of the Language Server initialized with config [Config(projectContentRoot=***\Unnamed_2, fileManager=FileManagerConfig(3 seconds,20), vcsManager=VcsManagerConfig(5 seconds,3 seconds), pathWatcher=PathWatcherConfig(5 seconds,5 seconds,10), executionContext=ExecutionContextConfig(5 seconds), directories=DirectoriesConfig(***\Unnamed_2))].
[info] [2023-02-06T12:50:21.542Z] [org.enso.languageserver.boot.LanguageServerComponent] Started server at json:127.0.0.1:63534, binary:127.0.0.1:53278
[info] [2023-02-06T12:50:21.711Z] [org.enso.projectmanager.infrastructure.languageserver.LanguageServerBootLoader] Language server booted [LanguageServerConnectionInfo(127.0.0.1,63534,53278)].
[info] [2023-02-06T12:50:21.801Z] [org.enso.languageserver.boot.resource.DirectoriesInitialization] Initializing directories...
[info] [2023-02-06T12:50:21.799Z] [org.enso.languageserver.protocol.json.JsonConnectionController] Initializing resources.
[info] [2023-02-06T12:50:21.802Z] [org.enso.languageserver.boot.resource.DirectoriesInitialization] Initialized directories.
[info] [2023-02-06T12:50:21.806Z] [org.enso.languageserver.boot.resource.RepoInitialization] Initializing suggestions repo [***\suggestions.db]...
[info] [2023-02-06T12:50:22.158Z] [org.enso.languageserver.boot.resource.RepoInitialization] Initialized Suggestions repo [***\suggestions.db].
[info] [2023-02-06T12:50:22.159Z] [org.enso.languageserver.boot.resource.RepoInitialization] Initializing versions repo [***\suggestions.db]...
[info] [2023-02-06T12:50:22.16Z] [org.enso.languageserver.search.SuggestionsHandler] Initializing: suggestions repo initialized.
[info] [2023-02-06T12:50:22.174Z] [org.enso.languageserver.boot.resource.RepoInitialization] Initialized Versions repo [***\suggestions.db].
[info] [2023-02-06T12:50:22.175Z] [org.enso.languageserver.text.BufferRegistry] Initiaized.
[info] [2023-02-06T12:50:22.176Z] [org.enso.languageserver.boot.resource.TruffleContextInitialization] Initializing Runtime context...
[info] [2023-02-06T12:50:23.823Z] [org.enso.languageserver.boot.resource.TruffleContextInitialization] Initialized Runtime context.
[info] [2023-02-06T12:50:23.823Z] [org.enso.languageserver.search.SuggestionsHandler] Initializing: Truffle context initialized.
[info] [2023-02-06T12:50:23.823Z] [org.enso.languageserver.protocol.json.JsonConnectionController] RPC session initialized for client [7e5e5e90-062d-4fb3-9068-1fd5a15b21f3].
[info] [2023-02-06T12:50:23.847Z] [org.enso.languageserver.search.SuggestionsHandler] Initializing: project name is updated to [Unnamed_2].
[info] [2023-02-06T12:50:23.968Z] [org.enso.languageserver.search.SuggestionsHandler] Initializing: got type graph response.
[info] [2023-02-06T12:50:24.012Z] [org.enso.languageserver.search.SuggestionsHandler] Verifying: got verification response.
[info] [2023-02-06T12:50:24.035Z] [org.enso.languageserver.search.SuggestionsHandler] Verified.
[info] [2023-02-06T12:50:28.319Z] [akka.actor.LocalActorRef] Message [akka.actor.ReceiveTimeout$] to Actor[akka://project-manager/system/IO-TCP/selectors/$a/2#-1808346782] was not delivered. [1] dead letters encountered. If this is not an expected behavior then Actor[akka://project-manager/system/IO-TCP/selectors/$a/2#-1808346782] may have terminated unexpectedly. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
[info] [2023-02-06T12:50:28.935Z] [akka.actor.LocalActorRef] Message [akka.actor.ReceiveTimeout$] to Actor[akka://project-manager/system/IO-TCP/selectors/$a/3#889945634] was not delivered. [2] dead letters encountered. If this is not an expected behavior then Actor[akka://project-manager/system/IO-TCP/selectors/$a/3#889945634] may have terminated unexpectedly. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
[info] [2023-02-06T12:50:29.567Z] [akka.actor.LocalActorRef] Message [akka.actor.ReceiveTimeout$] to Actor[akka://project-manager/system/IO-TCP/selectors/$a/4#-223418179] was not delivered. [3] dead letters encountered. If this is not an expected behavior then Actor[akka://project-manager/system/IO-TCP/selectors/$a/4#-223418179] may have terminated unexpectedly. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
[info] [2023-02-06T12:50:30.183Z] [akka.actor.LocalActorRef] Message [akka.actor.ReceiveTimeout$] to Actor[akka://project-manager/system/IO-TCP/selectors/$a/5#1887879833] was not delivered. [4] dead letters encountered. If this is not an expected behavior then Actor[akka://project-manager/system/IO-TCP/selectors/$a/5#1887879833] may have terminated unexpectedly. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
[info] [2023-02-06T12:50:30.836Z] [akka.actor.LocalActorRef] Message [akka.actor.ReceiveTimeout$] to Actor[akka://project-manager/system/IO-TCP/selectors/$a/6#-762319875] was not delivered. [5] dead letters encountered. If this is not an expected behavior then Actor[akka://project-manager/system/IO-TCP/selectors/$a/6#-762319875] may have terminated unexpectedly. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
[info] [2023-02-06T12:50:31.445Z] [akka.actor.LocalActorRef] Message [akka.actor.ReceiveTimeout$] to Actor[akka://project-manager/system/IO-TCP/selectors/$a/7#5364416] was not delivered. [6] dead letters encountered. If this is not an expected behavior then Actor[akka://project-manager/system/IO-TCP/selectors/$a/7#5364416] may have terminated unexpectedly. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
[info] [2023-02-06T12:50:46.578Z] [org.enso.languageserver.protocol.binary.BinaryConnectionController] Data session initialized for client: 7e5e5e90-062d-4fb3-9068-1fd5a15b21f3 [127.0.0.1:51979].
[info] [2023-02-06T12:50:47.37Z] [org.enso.languageserver.text.CollaborativeBuffer] Buffer opened for [path:Path(733273a3-4994-49d3-8c83-79d87c3505b5,Vector(src, Main.enso)), client:7e5e5e90-062d-4fb3-9068-1fd5a15b21f3].
[info] [2023-02-06T12:50:48.272Z] [enso.org.enso.compiler.PackageRepository$Default] Found library Standard.Base @ 2023.1.1-dev at [***\2023.1.1-dev].
[info] [2023-02-06T12:50:48.362Z] [enso.org.enso.compiler.PackageRepository$Default] Found library Standard.Table @ 2023.1.1-dev at [***\2023.1.1-dev].
[info] [2023-02-06T12:50:48.38Z] [enso.org.enso.compiler.PackageRepository$Default] Found library Standard.Database @ 2023.1.1-dev at [***\2023.1.1-dev].
[info] [2023-02-06T12:50:48.4Z] [enso.org.enso.compiler.PackageRepository$Default] Found library Standard.Visualization @ 2023.1.1-dev at [***\2023.1.1-dev].
[error] [2023-02-06T12:50:54.983Z] [org.enso.languageserver.runtime.ContextEventsListener] Unable to find suggestion for [(Standard.Base.Data.Range.Extensions,Standard.Base.Data.Numbers.Integer,up_to)].
[error] [2023-02-06T12:50:54.984Z] [org.enso.languageserver.runtime.ContextEventsListener] Unable to find suggestion for [(Standard.Base.Data.Range,Standard.Base.Data.Range.Range,to_vector)].
[error] [2023-02-06T12:50:54.984Z] [org.enso.languageserver.runtime.ContextEventsListener] Unable to find suggestion for [(Standard.Base.Data.Vector,Standard.Base.Data.Vector.Vector,map)].
[error] [2023-02-06T12:50:54.984Z] [org.enso.languageserver.runtime.ContextEventsListener] Unable to find suggestion for [(Standard.Base.Data.Vector,Standard.Base.Data.Vector.Vector,sort)].
[error] [2023-02-06T12:50:54.984Z] [org.enso.languageserver.runtime.ContextEventsListener] Unable to find suggestion for [(Standard.Base.Meta.Enso_Project,Standard.Base.Meta.Enso_Project.Project_Description,data)].
[error] [2023-02-06T12:50:54.984Z] [org.enso.languageserver.runtime.ContextEventsListener] Unable to find suggestion for [(Standard.Base.System.File,Standard.Base.System.File.File,/)].
[error] [2023-02-06T12:50:55.993Z] [org.enso.languageserver.runtime.ContextEventsListener] Unable to find suggestion for [(Standard.Table.Data.Table,Standard.Table.Data.Table.Table,transpose)].
[error] [2023-02-06T12:50:55.993Z] [org.enso.languageserver.runtime.ContextEventsListener] Unable to find suggestion for [(Standard.Base.System.File,Standard.Base.System.File.File,/)].
[error] [2023-02-06T12:50:55.993Z] [org.enso.languageserver.runtime.ContextEventsListener] Unable to find suggestion for [(Standard.Base.System.File,Standard.Base.System.File.File,read)].
[error] [2023-02-06T12:50:55.993Z] [org.enso.languageserver.runtime.ContextEventsListener] Unable to find suggestion for [(Standard.Base.Meta.Enso_Project,Standard.Base.Meta.Enso_Project.Project_Description,data)].
[error] [2023-02-06T12:50:55.993Z] [org.enso.languageserver.runtime.ContextEventsListener] Unable to find suggestion for [(Standard.Base.System.File,Standard.Base.System.File.File,read)].
[error] [2023-02-06T12:50:55.993Z] [org.enso.languageserver.runtime.ContextEventsListener] Unable to find suggestion for [(Standard.Table.Data.Table,Standard.Table.Data.Table.Table,aggregate)].
[error] [2023-02-06T12:50:55.994Z] [org.enso.languageserver.runtime.ContextEventsListener] Unable to find suggestion for [(Standard.Table.Data.Table,Standard.Table.Data.Table.Table,join)].
[error] [2023-02-06T12:51:03.359Z] [org.enso.languageserver.requesthandler.vcs.StatusVcsHandler] Status project request [Number(25)] for [7e5e5e90-062d-4fb3-9068-1fd5a15b21f3] failed with: null.
Exception in thread "Thread-9" java.lang.IllegalStateException: There is no current context available.
        at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotEngineException.illegalState(PolyglotEngineException.java:135)
        at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotContextImpl.requireContext(PolyglotContextImpl.java:720)
        at org.graalvm.truffle/com.oracle.truffle.polyglot.EngineAccessor$EngineImpl.createLanguageSystemThread(EngineAccessor.java:1940)
        at org.graalvm.truffle/com.oracle.truffle.api.TruffleLanguage$Env.createSystemThread(TruffleLanguage.java:1847)
        at org.graalvm.truffle/com.oracle.truffle.api.TruffleLanguage$Env.createSystemThread(TruffleLanguage.java:1813)
        at org.enso.compiler.SerializationManager.$anonfun$pool$1(SerializationManager.scala:54)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.<init>(ThreadPoolExecutor.java:623)
        at java.base/java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:912)
        at java.base/java.util.concurrent.ThreadPoolExecutor.processWorkerExit(ThreadPoolExecutor.java:1005)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
        at org.graalvm.truffle/com.oracle.truffle.polyglot.SystemThread.run(SystemThread.java:65)
[23336:0206/135214.223:ERROR:gpu_init.cc(521)] Passthrough is not supported, GL is disabled, ANGLE is
[error] [2023-02-06T12:53:18.71Z] [org.enso.languageserver.requesthandler.visualisation.AttachVisualisationHandler] Request [Number(75)] timed out.
[info] [2023-02-06T12:53:23.716Z] [akka.actor.LocalActorRef] Message [org.enso.languageserver.requesthandler.RequestTimeout$] from Actor[akka://language-server/user/json-connection-controller-bd040e44-7ea0-40c7-a5f9-da7baa1ae456/request-handler-AttachVisualisation-ca5ac731-4d40-4baf-bb90-39b532bcdf1b#-302522125] to Actor[akka://language-server/user/json-connection-controller-bd040e44-7ea0-40c7-a5f9-da7baa1ae456/request-handler-AttachVisualisation-ca5ac731-4d40-4baf-bb90-39b532bcdf1b#-302522125] was not delivered. [1] dead letters encountered. If this is not an expected behavior then Actor[akka://language-server/user/json-connection-controller-bd040e44-7ea0-40c7-a5f9-da7baa1ae456/request-handler-AttachVisualisation-ca5ac731-4d40-4baf-bb90-39b532bcdf1b#-302522125] may have terminated unexpectedly. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
[error] [2023-02-06T12:53:23.937Z] [org.enso.languageserver.requesthandler.visualisation.AttachVisualisationHandler] Request [Number(87)] timed out.
[info] [2023-02-06T12:53:28.937Z] [akka.actor.LocalActorRef] Message [org.enso.languageserver.requesthandler.RequestTimeout$] from Actor[akka://language-server/user/json-connection-controller-bd040e44-7ea0-40c7-a5f9-da7baa1ae456/request-handler-AttachVisualisation-3295fc7a-9ba7-4e53-ab33-2570b5908fba#1695488651] to Actor[akka://language-server/user/json-connection-controller-bd040e44-7ea0-40c7-a5f9-da7baa1ae456/request-handler-AttachVisualisation-3295fc7a-9ba7-4e53-ab33-2570b5908fba#1695488651] was not delivered. [2] dead letters encountered. If this is not an expected behavior then Actor[akka://language-server/user/json-connection-controller-bd040e44-7ea0-40c7-a5f9-da7baa1ae456/request-handler-AttachVisualisation-3295fc7a-9ba7-4e53-ab33-2570b5908fba#1695488651] may have terminated unexpectedly. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
[error] [2023-02-06T12:53:29.58Z] [org.enso.languageserver.requesthandler.visualisation.AttachVisualisationHandler] Request [Number(99)] timed out.
[info] [2023-02-06T12:53:34.577Z] [akka.actor.LocalActorRef] Message [org.enso.languageserver.requesthandler.RequestTimeout$] from Actor[akka://language-server/user/json-connection-controller-bd040e44-7ea0-40c7-a5f9-da7baa1ae456/request-handler-AttachVisualisation-33793704-265b-4a87-b67e-677f31fcaa7c#1734328338] to Actor[akka://language-server/user/json-connection-controller-bd040e44-7ea0-40c7-a5f9-da7baa1ae456/request-handler-AttachVisualisation-33793704-265b-4a87-b67e-677f31fcaa7c#1734328338] was not delivered. [3] dead letters encountered. If this is not an expected behavior then Actor[akka://language-server/user/json-connection-controller-bd040e44-7ea0-40c7-a5f9-da7baa1ae456/request-handler-AttachVisualisation-33793704-265b-4a87-b67e-677f31fcaa7c#1734328338] may have terminated unexpectedly. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
```

### Enso Version

[The build suggested for bookclub week 5](https://discord.com/channels/401396655599124480/1071026796709023764/1071042817247432833)

**Comment by hubertp** [comment] 2023-02-07 14:56
Duplicate of https://github.com/enso-org/enso/issues/5037

**Closed as completed by hubertp** 2023-02-07 14:56 UTC
