### ISSUE TITLE
Cursor issues in documentation panel on Windows

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5287] opened 2023-02-05 22:56 UTC
This task is automatically imported from the old Task Issue Board and it was originally created by Ilya Bogdanov.
Original issue is [here](https://www.pivotaltracker.com/story/show/184012727).
<hr />

Described here: https://www.pivotaltracker.com/story/show/183970777/comments/234661381

>  1. Unable to interact with documentation panel - when I move cursor away of hovering over a component content of the documentation changes,
    2. When I want to select text in the documentation panel, selection cursor disappears when close to left border rendering it impossible to select text without double clicking the first word,
    3. Windows default cursor behavior is not consistant - from time to time selection doesn't work, cursor disappears close to edges.

**Comment by farmaazon** [comment] 2023-02-21 13:20
@vitvakatu I remember you fixed something in mouse interactions with the documentation panel. Is this task still valid?

**Comment by vitvakatu** [comment] 2023-02-21 13:44
Yes, I think it should be fixed.
1. Works by design, you need to lock the selected entry with RMB
2. Was definitely fixed
3. Needs to be checked, but might be fixed as well.

**Comment by farmaazon** [comment] 2023-02-21 15:00
@galin-enso could you check the point 3?

**Comment by galin-enso** [comment] 2023-02-21 15:28
@farmaazon The only inconsistency I can spot is when the mouse is over the scrollbar area. It seems the mouse position is then inferred to be at the top of the document and dragging starts from there:

https://user-images.githubusercontent.com/117099775/220385759-8ba97058-0303-40d0-a7dc-1789ac2c4c3d.mp4

Other than this I can't reproduce a disappearing cursor or inconsistencies in selection.

**Comment by farmaazon** [comment] 2023-02-22 09:23
Hmm, I think the main problem is that clicking over the scroll bar should scroll, and it does not. Actually, I'm not able to scroll with mouse drag at all, only by mouse wheel.

Closing this task, will create a new one for the above issue.

**Closed as completed by farmaazon** 2023-02-22 09:23 UTC
Labels: p-low, --bug
