### ISSUE TITLE
Scrollbar in (JSON) Visualization steals focus from the visualization chooser

### ISSUE THREAD

**Issue by radeusgd** [enso-org/enso#5563] opened 2023-02-06 12:16 UTC
### General Summary

As in the title.

### Steps to Reproduce

1. Create a new table with lots of contents, for example load a bookclub example.
2. Open the visualization.
3. Try changing to one of the ones at the bottom.
4. Notice how the scrollbar will appear (even though it lies below) and if you click on its area, instead of selecting the visualization, the scrollbar will move and the visualization chooser will close without changing anything.

### Expected Result

The scrollbar should be below the visualization chooser and not influence its workings when the chooser is on top.

### Actual Result

The scrollbar takes over the focus and makes it hard to click on the selected visualization.
<img width="378" alt="image" src="https://user-images.githubusercontent.com/1436948/216968933-442c9fa9-b117-4bdf-acab-f93abbc45809.png">

### Enso Version

The build from https://discord.com/channels/401396655599124480/1071026796709023764/1071042817247432833

**Comment by sylwiabr** [comment] 2023-02-06 15:23
duplicate of: https://github.com/enso-org/enso/issues/5089

**Closed as completed by sylwiabr** 2023-02-06 15:23 UTC
Labels: s-duplicate
