### ISSUE TITLE
Drop down should preserve the value of its argument if it match the name

### ISSUE THREAD

**Issue by sylwiabr** [enso-org/enso#6051] opened 2023-03-22 16:38 UTC
### How important is this feature to you?

2 – Somewhat important, but I can live without it

### Describe the idea you'd like to see implemented.

1. User is choosing to take last 3 elements of the vector.
2. He change it to the first 3 elements with a drop down.
3. The `count` value should be preserved between changes.

### Would you be willing to help us implement this feature?

No

**Comment by jdunkerley** [comment] 2023-09-01 09:42
Duplicate of #5135

**Closed as not planned by jdunkerley** 2023-09-01 09:42 UTC
Labels: d-unknown, x-new-feature, p-low
