### ISSUE TITLE
The app starts super slow and does not work until nodes are reconnected.

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#6446] opened 2023-04-27 00:11 UTC
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [X] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [X] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

1. Open app
2. Create new project
3. You can wait for 10 minutes, and the "compiling stdlib" caption is still there.
4. You need to reconnect nodes for the engine to catch up.

### Expected behaviour

It should work.

### Screenshots or screencasts

https://user-images.githubusercontent.com/1623053/234728242-470fea04-bba8-4766-bdd2-b4fc1042c057.mov

### Enso Version

newest develop

### Browser or standalone distribution

Standalone distribution

### Browser Version or standalone distribution

standalone

### Operating System

MacOS

**Comment by sylwiabr** [comment] 2023-04-27 07:07
I can not reproduce this issue with build from ae94a9f40d3e98b9068da716b8b6416bba517a19 - what engine version is used for this project @wdanilo?

**Comment by vitvakatu** [comment] 2023-04-27 07:46
The IDE logs an error that the `setExecutionEnvironment` method is not found, so I assume it is a very old engine. Btw, it reminded me that perhaps we will need some kind of regression testing for older engine versions in the future, after the release.

**Comment by hubertp** [comment] 2023-04-27 10:36
Can't reproduce or analyze this without logs.

**Comment by MichaelMauderer** [comment] 2023-04-27 12:37
@wdanilo Can you post how you started the IDE?

**Comment by vitvakatu** [comment] 2023-05-03 11:10
Closing as not reproducible. @wdanilo please reopen and provide additional information if necessary

**Closed as not planned by vitvakatu** 2023-05-03 11:10 UTC
Labels: s-no-repro, --bug

**Comment by wdanilo** [comment] 2023-05-03 13:42
This might have been caused by improper engine version. I will re-test it.
