### ISSUE TITLE
In some sessions, no suggestion database entries are provided for local methods

### ISSUE THREAD

**Issue by kazcw** [enso-org/enso#10021] opened 2024-05-21 14:36 UTC
To reproduce:
1. Create a project with at least one local method, e.g. by grouping some components.
2. Open the component browser by pressing Enter.
3. Type `collapse` to narrow the suggestions to only methods created by grouping components.
4. Repeat steps 2-3: Sometimes the local methods are suggested, and sometimes they are not.

**Comment by kazcw** [comment] 2024-05-21 14:44
Note: I have only tested this with a project-manager build from 2 May (142e11d).

**Comment by farmaazon** [comment] 2024-05-21 14:59
Please test it on newest nightly. Probably it's a duplicate of https://github.com/enso-org/enso/issues/9962

**Comment by kazcw** [comment] 2024-05-24 23:02
Seems to be fixed

**Closed as not planned** 2024-05-24 23:02 UTC
Labels: s-duplicate
