### ISSUE TITLE
DetachVisualisationHandler request timeout

### ISSUE THREAD

**Issue by xvcgreg** [enso-org/enso#5745] opened 2023-02-23 07:34 UTC
Entering grouped nodes seems slow and renders errors. See the attached video and log.

**Comment by xvcgreg** [comment] 2023-02-23 07:36
https://user-images.githubusercontent.com/108271897/220844536-2290f5aa-2731-412f-8abb-718fc3746603.mp4

[2302230824_DetachVisualisationHandler request timeout.txt](https://github.com/enso-org/enso/files/10811163/2302230824_DetachVisualisationHandler.request.timeout.txt)

**Comment by farmaazon** [comment] 2023-02-23 10:55
@xvcgreg What do you mean by "renders errors."? Despite the errors in the log, I see on the screencast that nodes are displayed properly, and connections are properly colored.

**Comment by farmaazon** [comment] 2023-02-23 13:06
I reproduced the detach visualization error. It's not easy, as it seemingly needs a big project to show.

The one reproduction scenario I find quite reliably is opening this project
[Bookclub_Week_5.zip](https://github.com/enso-org/enso/files/10813736/Bookclub_Week_5.zip)

And getting out of func1 (double-click on the background).

At this point, IDE is bombarding the engine with attach/detach visualization requests, as we see many new nodes now and each node want's to ask about its widgets.

**Comment by farmaazon** [comment] 2023-02-23 13:11
The timeout seems to be a some internal engine timeout, not the IDE one:
```
{"jsonrpc":"2.0","id":28,"error":{"code":11,"message":"Request timeout"}}
```
We receive this message before the IDE timeout is reached.

**Comment by JaroslavTulach** [comment] 2023-03-01 07:41
I am trying to reproduce the problem with [Bookclub_Week_5.zip](https://github.com/enso-org/enso/files/10813736/Bookclub_Week_5.zip), but so far no luck. Can you reproduce it again and collect profiling data? 

When I follow the [engine profiling instructions](https://github.com/enso-org/enso/blob/develop/docs/profiler/engine-startup.md) and launch the `project-manager` as:
```bash
project-manager -vv --no-log-masking \
  --profiling-path collapse.npss \
  --profiling-events-log-path collapse.log \
  --profiling-time 60
```
I get following two files packaged into a single [collapse.zip](https://github.com/enso-org/enso/files/10858174/collapse.zip). Opening them in `graalvm/bin/jvisualvm` I can see that `sendVisualizationUpdate` is invoking Enso interpreter in "uncached" (e.g. slow) mode:

![sendVisualizationUpdate takes 700ms](https://user-images.githubusercontent.com/26887752/222074496-93070e9e-4c52-40cf-92db-aadc9d8f6bde.png)

That is a problem. Also the `findModuleByExpressionId` seems to be slow. Reporting as:
- #5781 
- #5782 

Whether or not that is causing the _"Request timeout"_ needs to be verified. Please generate your profiling data with _"Request timeout"_ message included.

**Comment by farmaazon** [comment] 2023-03-01 10:02
I tried to reproduce it on newest nightly (2023-03-01), and I failed. Something was speeded up in the meanwhile. Good job!

I have found a new scenario, however: I opened the COVID project and there was many timeouts on startup (but this may be another issue), causing initial visualizations to close. Also, I got one request timeout when stepping in and out of a collapsed node.

Here are profiler logs, project manager console logs (stdout and stderr combined) and the project where I reproduced the issue.

[Colorado_COVID_and_pm_profiling.zip](https://github.com/enso-org/enso/files/10859608/Colorado_COVID_and_pm_profiling.zip)

**Comment by wdanilo** [comment] 2023-03-08 13:27
@xvcgreg can you please upload videos in such a way that they are playable on GitHub please in future?

**Comment by xvcgreg** [comment] 2023-03-08 15:10
@wdanilo what's wrong with this video? 
I can play it w/o a problem.

**Comment by sylwiabr** [comment] 2023-03-08 15:23
<img width="951" alt="image" src="https://user-images.githubusercontent.com/12892578/223754035-e96b36fc-1320-4b8a-92e5-bc43f6751e8e.png">
cc @xvcgreg

**Comment by xvcgreg** [comment] 2023-03-08 16:57
https://user-images.githubusercontent.com/108271897/223778516-8d3495ae-299c-4101-b8a5-ae8dd76eace1.mp4

[2302230824_DetachVisualisationHandler request timeout.txt](https://github.com/enso-org/enso/files/10922952/2302230824_DetachVisualisationHandler.request.timeout.txt)

**Comment by xvcgreg** [comment] 2023-03-08 16:59
@sylwiabr @wdanilo I do not know what went wrong - I have tested it now and now it works. I did it the same way I did it earlier. Will take a closer look at that next time. Sorry for the inconvenience.

**Comment by wdanilo** [comment] 2023-03-08 22:05
> @sylwiabr @wdanilo I do not know what went wrong - I have tested it now and now it works. I did it the same way I did it earlier. Will take a closer look at that next time. Sorry for the inconvenience.

No, it doesn't work still. I see the same as Sylwia - just link, not an embedded video.

**Comment by xvcgreg** [comment] 2023-03-10 07:50
> 

I see the video in the comments feed.
And I literally did nothing except cut and paste back the link. Is there any other method of making sure those links are viewed as embedded video players inside the body of the message?

**Comment by farmaazon** [comment] 2023-03-10 11:21
Those messages are cluttering issue comment history. Could you fix such technical details on DM? @wdanilo @xvcgreg @sylwiabr

**Comment by hubertp** [comment] 2023-03-16 16:16
> I tried to reproduce it on newest nightly (2023-03-01), and I failed. Something was speeded up in the meanwhile. Good job!
> 
> I have found a new scenario, however: I opened the COVID project and there was many timeouts on startup (but this may be another issue), causing initial visualizations to close. Also, I got one request timeout when stepping in and out of a collapsed node.
> 
> Here are profiler logs, project manager console logs (stdout and stderr combined) and the project where I reproduced the issue.

I had a look at the logs and the logs on startup are actually fine. The connection exceptions listed there are part of a normal workflow where we wait for Language Server to standup.

Ditto about timeouts to `AttachVisualization`. I would suggest to file a separate ticket and I will investigate more.
Apologies for not looking into it earlier. It somehow not landed on my radar.

We've made a ton of improvements since, so I wouldn't be surprised if the original issue is resolved.

**Comment by hubertp** [comment] 2023-03-16 16:45
I think it's possible the AttachVisualization jobs that did timeout are possible duplicates. When we receive requests for such jobs that are supposed to be unique, the previous ones get cancelled. And I think I'm seeing that in the logs.
We could probably improve the logs to avoid unnecessary reports.

**Comment by JaroslavTulach** [comment] 2023-03-17 05:49
> We've made a ton of improvements since, so I wouldn't be surprised if the original issue is resolved.

Yes, that's my expectation as well. Now when #5781 and #5782 are integrated, we can close this issue.

**Closed as completed by JaroslavTulach** 2023-03-17 05:49 UTC
Labels: p-low, --bug, -libs, -language-server

**Comment by hubertp** [comment] 2023-03-17 09:52
Confirmed with @4e6 regarding spurious `Request Timeout` errors. Filed https://github.com/enso-org/enso/issues/5985
