### ISSUE TITLE
Rendering issues following merger of "reduce draw calls"

### ISSUE THREAD

**Issue by jdunkerley** [enso-org/enso#6975] opened 2023-06-07 09:43 UTC
While QAing this morning to do the book clubs a few issues appeared.

1. When editing text and hovering over a node with a connection the bottom half of the node gets coloured.
![image](https://github.com/enso-org/enso/assets/4699705/0fb40829-5350-4f6f-a5a9-a44b2b728c64)

2. The error border is hidden behind the selected node highlight and makes it very subtle.
![image](https://github.com/enso-org/enso/assets/4699705/736b6773-f106-4178-b034-42602ad04a87)

3. The error vis box no longer has rounded corners (other viz boxes do).
![image](https://github.com/enso-org/enso/assets/4699705/52aea5e8-ac44-4c5e-8f2c-c3546e4695a7)

4. Two text nodes over the top of each  other merge the content into a single mix.
![image](https://github.com/enso-org/enso/assets/4699705/bd30efce-9740-46d5-99b8-6bac2dbc6405)

5. Docking appears to have become significantly more difficult and only reliable way was to go in from the bottom which seems to make it find it (not sure if related but feels much worse on this build).

**Comment by wdanilo** [comment] 2023-06-07 10:05
1,2,3 - these are to be fixed. @kazcw Sylwia mentioned it is introduced by your PR, could you look at it please?
4 - it was always like that, this is not a regression and it is not fixable, unfortunately. However, if a node is selected, if I remember correctly, then it should be rendered on a separate layer, so selected not should not be prone to this error.
5. Could you describe it better please, or share some video showing it? It would be so much easier to understand.

**Comment by jdunkerley** [comment] 2023-06-07 10:21
Fair enough on 4. Noticed it particularly today but indeed my snapshot version has it as well.

5. When I dragged directly to the placeholder it didn't dock. I then moved down to the exit port and then was able to dock. 
Tried to reproduce now and couldn't - not sure if @sylwiabr was recording when we were trying it out.

**Comment by farmaazon** [comment] 2023-06-07 12:04
5 might be a duplicate of #6850

**Comment by kazcw** [comment] 2023-06-09 16:15
1. Not a regression--the state where a node is being edited and also the mouse is controlling a detached edge should not occur. Fixed in #6991.
2. Regression. Fixed in #6991.
3. Not a regression, I think it's always been like that. ~~Will fix in #6991.~~ Opened a separate bug #7008.

**Closed as completed** 2023-06-14 17:58 UTC
Labels: --regression
