### ISSUE TITLE
Pressing return while editing in the text code editor open Component Browser 

### ISSUE THREAD

**Issue by jdunkerley** [enso-org/enso#6103] opened 2023-03-28 09:59 UTC
When entering some code in the code editor pane if you press return a new node is added, the Component Browser opens and the focus moves to the new node.

We thought had been previously fixed.

**Comment by farmaazon** [comment] 2023-03-28 11:19
`6b14ec5a630ee566d034895b5b57df01d942fbcd` seems to be the offender.

**Comment by wdanilo** [comment] 2023-03-29 09:51
> `6b14ec5a630ee566d034895b5b57df01d942fbcd` seems to be the offender.

Pasting link in order to make it more obvious to other readers: https://github.com/enso-org/enso/pull/4072
 CC @Frizi

**Comment by xvcgreg** [comment] 2023-07-04 16:04
Closing - can't reproduce in Nightly 2023.7.4

**Closed as completed by xvcgreg** 2023-07-04 16:04 UTC
Labels: d-intermediate, s-no-repro, p-medium, --regression
