### ISSUE TITLE
Bugs in GUI2

### ISSUE THREAD

**Issue by farmaazon** [enso-org/enso#8744] opened 2024-01-11 16:44 UTC
```[tasklist]
### Tasks
- [ ] When clicking at nested selector, two are opened at once (Picture 1)
- [ ] Sometimes when dropping connection, it's connected to last used selection. Still working on reproduction scenario.
```

![image](https://github.com/enso-org/enso/assets/3919101/50a4fe9b-11b2-4f58-9249-bea6e5454acd)

**Comment by somebody1234** [comment] 2024-01-11 21:41
Duplicate of #8745

**Closed as not planned by somebody1234** 2024-01-11 21:41 UTC
Labels: p-high, d-unknown, --bug, -gui
