### ISSUE TITLE
Deep links do not work on Linux

### ISSUE THREAD

**Issue by somebody1234** [enso-org/enso#6147] opened 2023-03-30 12:43 UTC
### What type of issue is this?

Permanent – Ocurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

Deep links (`enso://` links) are not registered on Linux, and hence the links open in a regular browser (the default fallback on my setup, at least)

### Expected behaviour

Deep links open in the electron app

### How we can reproduce it?

1. Open the electron app
2. Try logging in with Google

### Enso Version

latest

### Browser or standalone distribution

Standalone distribution

### Browser Version or standalone distribution

standalone

### Operating System

Linux

**Comment by farmaazon** [comment] 2023-03-30 13:45
I haven't made extensive research yet, but I'm afraid every desktop environment (GNOME vs KDE vs whatever else) is doing it in a bit different way, similarly to the file bindings. I would not recommend our application to do it on Linux by itself. As a Linux user myself, I really don't like if an application meddles with those settings on _startup_.

Except there is some standard for AppImages, but as I heard from @mwu-tow there is hardly a unified standard for installing app images on various distros.

**Comment by somebody1234** [comment] 2023-03-30 13:58
supposedly `app.setAsDefaultProtocolClient` should Just Do It on Linux - at least, [the docs](https://www.electronjs.org/docs/latest/api/app#appsetasdefaultprotocolclientprotocol-path-args) mention limitations for macos and windows but not linux.
that said, i'm not sure whether just that call would be sufficient

**Comment by somebody1234** [comment] 2023-03-30 14:09
oh, apparently that function doesn't work/isn't required on linux? ([link](https://github.com/electron-userland/electron-builder/issues/4035#issuecomment-621131126))

**Comment by somebody1234** [comment] 2023-03-30 14:14
re: lack of a unified standard, that does make sense
however i do think there needs to be *some* way to make deep linking work on linux, since it's pretty much vital for making `-authentication` for the cloud dashboard work

**Comment by somebody1234** [comment] 2023-03-30 14:17
currently i'm manually extracting the `.desktop` and installing it in `~/.local/share/applications/`, and chaning the `Exec` command to `/path/to/binary %U`, however that's not working very well as the binary does not accept the url as a command-line argument. not sure how deep links are normally sent to linux electron apps though...

**Comment by farmaazon** [comment] 2023-03-31 07:21
> however i do think there needs to be _some_ way to make deep linking work on linux, since it's pretty much vital for making `-authentication` for the cloud dashboard work

That's actually important information. Have you a task for it, so we can put this as a blocker of that? And do you need it for Design Partners/Beta release?

**Comment by wdanilo** [comment] 2023-03-31 07:22
Ugh, this is bad that it's breaking user-logging. Hmm, @mwu-tow is working on very related thing right now - registering on different systems file associations. @mwu-tow what do you think of this issue?

And yes, @farmaazon, being able to run the app and log-in on linux is unfortunately needed for Design Partners :(

**Comment by mwu-tow** [comment] 2023-03-31 09:51
IIRC, we mentioned this issue on Wednesday when talking with @PabloBuchu, and the thought was to have authentication disabled on Linux at first. Yes, it's likely pretty much a similar issue as file associations.

See #5239

**Comment by wdanilo** [comment] 2023-03-31 09:53
@mwu-tow @farmaazon @PabloBuchu  I was talking with Sylwia about it. @PabloBuchu can we do it this way that on linux users would need to copy-paste some code instead for now instead of using deep links?

**Comment by somebody1234** [comment] 2023-03-31 09:57
oh, i guess this is pretty much a duplicate of #5239

**Comment by 4e6** [comment] 2023-04-04 10:05
Duplicate of #5239

**Closed as completed by 4e6** 2023-04-04 10:05 UTC
Labels: --bug
