### ISSUE TITLE
Node text formatting changes on execution context change

### ISSUE THREAD

**Issue by xvcgreg** [enso-org/enso#6479] opened 2023-05-01 09:28 UTC
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

When I toggle from design to live file name in the node text changes to bold, when I switch back it doesn't go back to normal font anymore on any subsequent mode change.

https://user-images.githubusercontent.com/108271897/235434786-46612429-a005-4667-b5c9-7dd47c3a1b04.mp4

### Expected behaviour

Consistent node styling or going back and forth between those two states of text styling (normal and bold font)

### How we can reproduce it?

as described above

### Enso Version

2023.5.1

### Browser or standalone distribution

Standalone distribution

### Browser Version or standalone distribution

Version 112.0.5615.138 (Official Build) (64-bit)

### Operating System

Windows

### Operating System Version

Win11pro 22H2 22621.1555

### Hardware you are using

12th Gen Intel(R) Core(TM) i9-12900HK / RTX3060 Laptop / Nvidia Drivers 531.68

**Comment by farmaazon** [comment] 2023-05-01 10:16
It's look a bit like we should always have those text bold, as it's a drop down widget. We don't have the widget before switching context, but this seems like duplicate of https://github.com/enso-org/enso/issues/6324

@Frizi could you confirm?

**Comment by farmaazon** [comment] 2023-05-02 07:59
Closing as duplicate: #6324 See my comment above.

**Closed as not planned** 2023-05-02 10:31 UTC
Labels: s-duplicate, --bug
