### ISSUE TITLE
Unexpected block created if an indented comment is added after an expression

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5257] opened 2023-02-05 22:55 UTC
This task is automatically imported from the old Task Issue Board and it was originally created by Radosław Waśko.
Original issue is [here](https://www.pivotaltracker.com/story/show/184076134).
<hr />

Run the following program:
```
from Standard.Base import all

foo =
    42
    # bar
        # baz

main =
    IO.println foo
```

I'd expect to see `42`.
Instead, I see:
```
<anonymous>[block.enso:1-12]
```

Removing the two comments makes the program work correctly - printing `42`.

So adding these two comments currently changes the semantics of the program (:

**Comment by kazcw** [comment] 2023-02-10 18:06
Duplicate of #5443

**Closed as completed by kazcw** 2023-02-10 18:06 UTC
Labels: p-low, --bug, -parser
