### ISSUE TITLE
Orphaned edges keep floating around during redraws

### ISSUE THREAD

**Issue by hubertp** [enso-org/enso#6013] opened 2023-03-20 14:34 UTC
### What type of issue is this?

Permanent – Ocurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [X] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

Best to explain with a video

https://user-images.githubusercontent.com/292128/226371697-392180e3-9f1d-48d5-ae5d-705cc6670a99.mp4

### Expected behaviour

This has degraded quite significantly recently. We shouldn't leave such orphaned edges floating around.

### How we can reproduce it?

As per video

### Enso Version

develop

### Browser or standalone distribution

Chrome

### Browser Version or standalone distribution

110.0.5481.10

### Operating System

Linux

**Comment by vitvakatu** [comment] 2023-03-20 14:41
Duplicate of #5095

**Closed as not planned by vitvakatu** 2023-03-20 14:41 UTC
Labels: --bug, --regression

**Comment by hubertp** [comment] 2023-03-20 14:44
@vitvakatu It used to be way much harder to get this bug. Now any edge mis-behaves. So I would say that something degraded even more recently.

**Comment by vitvakatu** [comment] 2023-03-20 14:51
@hubertp ok, I will try to reproduce it myself later today and report the results. I suggest continuing to discuss this issue in #5095 anyway, as I don't see why we should create a separate issue.
