### ISSUE TITLE
Wrong entry selected in Component Browser if Enter is pressed too fast

### ISSUE THREAD

**Issue by radeusgd** [enso-org/enso#6913] opened 2023-05-31 22:13 UTC
See the following video:

https://github.com/enso-org/enso/assets/1436948/20560589-28a5-47a8-b1f2-79560eb5f81c

On the first try I typed `first` and pressed Enter so fast that the keystrokes of `first` did not even get a chance to render... So it inserted the default node: `to_table` - totally ignoring what I typed.

On second try I was slow and the CB actually did manage to select the `first` and then it inserted correctly the node `first`. Yay.

On third try I was just right - you can see that my keystrokes did make `first` appear in the new-node-creation-field - so they were registered. But the searched _did not yet switch_ to the correct entry before the Enter event was processed. And so even though the Node displayed `first`, after clicking Enter, `to_table` was inserted again.

It seems that the "Enter" action is processed too soon. Some sort of event queueing should happen to ensure that all necessary processing of keystrokes that have been inputted is finished, before processing of Enter, dependant on these, starts.

Otherwise, maybe the "Enter" keystroke should simply not register if other events are being processed (giving the user a chance to wait until all 'settles', the CB displays the correct entry etc. and to try pressing Enter again afterwards).

Regardless of the solution, I think the current behaviour is problematic. As a fast-typing user I'm punished - I have to explicitly wait until the CB loads and switches to the right option (which takes 2s+ after warmup and even worse on first try - that is **ages** for text editing usecases where one can do 80 words per minute - i.e. typing one full word (= method name) usually takes around 1s).

**Comment by radeusgd** [comment] 2023-05-31 22:15
I thought this was meant to be fixed by #6812 but I'm running a build containing this commit and the behaviour is as shown on the video.

**Comment by farmaazon** [comment] 2023-06-01 07:41
This should be actually fixed by https://github.com/enso-org/enso/pull/6875 which is not merged yet, so probably you haven't had this fix.

It's a duplicate of #6733 or #6908 or both.

**Closed as not planned** 2023-06-01 07:42 UTC
Labels: s-duplicate, --bug
