### ISSUE TITLE
Enso dying on me while I'm trying to Panic.catch with Invalid Version error

### ISSUE THREAD

**Issue by xvcgreg** [enso-org/enso#6701] opened 2023-05-15 14:13 UTC
### What type of issue is this?

Intermittent – Occurring irregularly

### Is this issue blocking you from using Enso?

- [X] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

I was testing ``select_columns`` that gave me unexpected behavior (grey dot hard to click, adding new items to the list laggy, dropdowns (with column names) unresponsive) I have tried to use Panic.catch and resulted in Invalid Version error. 

![image](https://github.com/enso-org/enso/assets/108271897/1feda617-7d27-4654-8f2b-ad109317e6c6)

There's also no information in the log about it:
```[info] [2023-05-15T13:52:27.221Z] [akka.actor.LocalActorRef] Message [akka.actor.ReceiveTimeout$] to Actor[akka://project-manager/system/IO-TCP/selectors/$a/2#-86147170] was not delivered. [1] dead letters encountered, no more dead letters will be logged in next [5.000 min]. If this is not an expected behavior then Actor[akka://project-manager/system/IO-TCP/selectors/$a/2#-86147170] may have terminated unexpectedly. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
[info] [2023-05-15T13:53:11.268Z] [enso] Background jobs started.
[31420:0515/155401.566:ERROR:gpu_init.cc(523)] Passthrough is not supported, GL is disabled, ANGLE is
[info] [2023-05-15T13:56:34.343Z] [org.enso.projectmanager.protocol.ClientController] Client disconnected from the Project Manager [0d1d0c6e-dc68-48a3-a32c-fea928bc6591]
[info] [2023-05-15T13:56:34.343Z] [org.enso.languageserver.protocol.binary.BinaryConnectionController] Connection closed [127.0.0.1:63634].
[info] [2023-05-15T13:56:34.35Z] [org.enso.languageserver.runtime.RuntimeKiller] Shutting down the runtime server [Actor[akka://language-server/user/runtime-connector#-1358680590]].
[info] [2023-05-15T13:56:34.359Z] [org.enso.languageserver.runtime.RuntimeKiller] Shutting down the Truffle context [org.graalvm.polyglot.Context@46cb57ff]. Attempt #1.
[warn] [2023-05-15T13:56:34.36Z] [org.enso.projectmanager.boot.ProjectManager$] Failed to read line.
[info] [2023-05-15T13:56:34.36Z] [org.enso.projectmanager.boot.ProjectManager$] Stopping server...
[info] [2023-05-15T13:56:34.36Z] [org.enso.projectmanager.infrastructure.languageserver.LanguageServerKiller] Killing all servers [List(Actor[akka://project-manager/user/language-server-registry/language-server-controller-562fc4ba-4cce-4ec0-8e3a-fd99d34fe430#-1895869150])].
[warn] [2023-05-15T13:56:34.36Z] [org.enso.projectmanager.infrastructure.languageserver.LanguageServerController] Received unknown message: class org.enso.projectmanager.infrastructure.languageserver.LanguageServerController$ShutDownServer$
[info] [2023-05-15T13:56:34.471Z] [org.enso.languageserver.boot.LanguageServerComponent] Terminated truffle context.
[info] [2023-05-15T13:56:34.477Z] [org.enso.languageserver.boot.LanguageServerComponent] Terminated json connections.
[info] [2023-05-15T13:56:34.478Z] [org.enso.languageserver.boot.LanguageServerComponent] Terminated binary connections.
[info] [2023-05-15T13:56:34.505Z] [akka.actor.CoordinatedShutdown] Running CoordinatedShutdown with reason [ActorSystemTerminateReason]
[internal-logger-error] Server has disconnected, logging is falling back to stderr.
[info] [2023-05-15T13:56:34.586Z] [org.enso.languageserver.boot.LanguageServerComponent] Terminated actor system.
[info] [2023-05-15T13:56:34.589Z] [org.enso.languageserver.boot.MainModule] Closed Language Server main module.
[info] [2023-05-15T13:56:34.589Z] [org.enso.languageserver.boot.LanguageServerComponent] Terminated main module.```


### Expected behaviour

Panic.catch serving me the meaningful error description to know what went wrong.

### How we can reproduce it?

_No response_

### Screenshots or screencasts

_No response_

### Enso Version

2023.5.12 nightly

### Browser or standalone distribution

Standalone distribution

### Browser Version or standalone distribution

standalone

### Operating System

Windows

### Operating System Version

Win11pro 22H2 22621.1555

### Hardware you are using

12th Gen Intel(R) Core(TM) i9-12900HK / RTX3060 Laptop / Nvidia Drivers 531.68

**Comment by hubertp** [comment] 2023-05-17 12:33
Do you have full logs from engine? So far it looks like a yet another instance of IDE desynchronizing source from what LS expects. There might be many reasons why this happens, both on the IDE and LS-side.

**Comment by xvcgreg** [comment] 2023-05-17 13:05
@hubertp that's it I have pasted above. Before ``[info] [2023-05-15T13:53:11.268Z] [enso] Background jobs started.`` is the normal starting stuff logged in the CLI.

[2023-05-15T13-52-01.289Z-ide-2023.2.1-nightly.2023.5.12.log](https://github.com/enso-org/enso/files/11498392/2023-05-15T13-52-01.289Z-ide-2023.2.1-nightly.2023.5.12.log)

**Comment by Akirathan** [comment] 2023-05-18 12:26
@xvcgreg Could you please try to reproduce it with **verbose** logs from the backend pls? The description how to turn that on is here: https://github.com/enso-org/enso/blob/develop/docs/CONTRIBUTING.md#turning-on-verbose-logs. Without verbose logs from LS, we cannot see what exactly went wrong on the LS side.

So far, it seems like an issue with LS.

<blockquote><img src="https://opengraph.githubassets.com/141c99b116b7db7a2d65ecb4e781273ab208e408f1fa13be809fc9a92a36d986/enso-org/enso" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/enso-org/enso">enso/CONTRIBUTING.md at develop · enso-org/enso</a></strong></div><div>Hybrid visual and textual functional programming. Contribute to enso-org/enso development by creating an account on GitHub.</div></blockquote>

**Comment by xvcgreg** [comment] 2023-05-18 16:18
@Akirathan I couldn't reproduce the "invalid version 3003" error, but here's the log - maybe you will catch something.

[20230518-160234-723-enso-project-manager.zip](https://github.com/enso-org/enso/files/11509546/20230518-160234-723-enso-project-manager.zip)

**Comment by hubertp** [comment] 2023-05-18 18:42
```
> grep "Invalid version" 20230518-160234-723-enso-project-manager.log
<nothing> :(
```

**Comment by hubertp** [comment] 2023-05-19 15:08
Found an interesting way to force those errors - throttle network on your browser to `Fast 3G` on chrome.

**Comment by Akirathan** [comment] 2023-05-19 15:26
> @Akirathan I couldn't reproduce the "invalid version 3003" error, but here's the log - maybe you will catch something.
> 
> [20230518-160234-723-enso-project-manager.zip](https://github.com/enso-org/enso/files/11509546/20230518-160234-723-enso-project-manager.zip)

I can't see anything suspicious in these logs either. But thanks for sending them anyway.

**Comment by hubertp** [comment] 2023-05-19 15:51
Here is a screenshot of messages leading to Invalid Version
![Screenshot from 2023-05-19 17-43-22](https://github.com/enso-org/enso/assets/292128/33bda836-a05b-423c-9e54-8af9de3c47bc)

At `17:04:22.105` it sends `text/ApplyEdit`
```
"newVersion":"c343c2217d6d919b62254b12dc5f01d0e0cbc901661d42105e96328c","oldVersion":"7a9e149f7d554ed74bc2d3475a78920904e224d526710ebac957f7cd"
```
Then it sends another `text/applyEdit` at `17:04:32.130`:
```
newVersion: "157b6e3bbe31e8a8ad217b6994f977187def01424cb68abc53d16b81"
oldVersion: "7a9e149f7d554ed74bc2d3475a78920904e224d526710ebac957f7cd"
```
It receives at `17:04:39.312` an ACK for the **first** edit.
It receives at `17:04:39.321` the first of many error messages (this one related to the second `applyEdit` requests):
```
code:3003
message:"Invalid version [client version: 7a9e149f7d554ed74bc2d3475a78920904e224d526710ebac957f7cd, server version: c343c2217d6d919b62254b12dc5f01d0e0cbc901661d42105e96328c]"
id:15
```

This is not related to `Panic.catch` mentioned in this ticket. But I think this is the problem that has been hunting us for so long under very random circumstances. It appears that IDE does not wait for acks, when sending successive edit requests and that can quickly lead to out-of-sync between IDE and LS. In that case LS will move on with the edits and have, rightfully so, a new version, while IDE appears to be still insisting on using the old version.

EDIT:
Maybe an important detail. It appears that the first `text/applyEdit` has `execute: false` while the second one `execute: true` parameter. Without knowing the details of the implementation, maybe that is important?

**Comment by hubertp** [comment] 2023-05-19 15:55
@farmaazon maybe ^ rings a bell?

**Comment by farmaazon** [comment] 2023-05-22 07:52
>  It appears that IDE does not wait for acks, when sending successive edit requests and that can quickly lead to out-of-sync between IDE and LS.

Not quite. IDE _does_ wait for previous edit. However, we have our internal timeout of 10 seconds for every json-rpc method, after which we assume it failed.

And this is what happened here: right before getting the first ACK, we gave up and proceed to the next update. Before #6752 (not merged yet as I write this comment) we always assumed the failed `text/applyEdit` is not applied. But here the LS actually had applied, thence the version mismatch.

Once #6752 lands, IDE will not assume anything about failed edits, and we will reopen the text file in Language Server.

@hubertp So, while IDE soon will handle such situations, still I think the long delay of applying text changes should be investigated. Sole `text/applyEdit` should not be something taking 10 seconds! TBH when we were setting this timeout, I was sure it's so big we should even shorten it some day.

**Comment by hubertp** [comment] 2023-05-22 09:05
@farmaazon But there is nothing to investigate on LS-side. I'm using network and CPU throttling which simulates real life scenario of someone having a (really) bad day with their network or/and machine. Everything else is out-of-the-box.

I can understand the frustration that things shouldn't take 10 seconds on engine side, and I'm certainly with you on that part. Most of the time we don't exceed that, except sometimes we do and IDE should be fault tolerant enough to deal with such situations or inform the user about performance degradation. At least that's what I would expect. 
Alternatively, code editors would essentially freeze when waiting for some answer. Neither of those approaches is ideal but it is also not a common scenario. Continuing with another update after the internal 10 second timeout was not ideal because it was potentially forcing the system into an invalid state, as demonstrated.

> Once https://github.com/enso-org/enso/pull/6752 lands, IDE will not assume anything about failed edits, and we will reopen the text file in Language Server.

That seems better. I will try to test it.

**Comment by farmaazon** [comment] 2023-05-22 09:24
>  I'm using network and CPU throttling which simulates real life scenario of someone having a (really) bad day with their network or/and machine. Everything else is out-of-the-box.

It seems I misunderstood the ticket then - I had the impression it's a regularly appearing issue on local project (out ruling all connectivity issues). In that case, I'd say 10 seconds it a lot of time for "update code, launch triggers and return", even on a slow machine.

If it's not so, then I guess we can close it once https://github.com/enso-org/enso/pull/6752 lands.

**Comment by hubertp** [comment] 2023-05-22 10:02
![Screenshot from 2023-05-22 11-55-52](https://github.com/enso-org/enso/assets/292128/4b55792b-feee-4bf3-a789-f5483268a494)
I don't know, tried your patch. If things are really slow then it can still get confused (see third and last message). But I was no longer able to get `Invalid Version`.
Also, console logs:
![Screenshot from 2023-05-22 12-00-52](https://github.com/enso-org/enso/assets/292128/3b699398-eaa7-4999-91d2-2727095a4d6a)

**Comment by farmaazon** [comment] 2023-05-22 10:33
Well, the PR does not make IDE resilient to _all_ possible timeouts. 

The first is worrying. The last is just timeout for reloading - but then IDE will try to reload again when the next change arrives.

**Comment by hubertp** [comment] 2023-05-30 14:53
I think the underlying problem has been remedied by IDE essentially reloading the file rather than attempting to apply further changes.

**Closed as completed by hubertp** 2023-05-30 14:53 UTC
Labels: --bug, --regression, -language-server
