### ISSUE TITLE
Component Browser closes when opened by dragging the output too quickly

### ISSUE THREAD

**Issue by 4e6** [enso-org/enso#6579] opened 2023-05-05 12:59 UTC
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

The component browser opens and closes instantly when you pull the output node and release it very quickly. When you wait a second after pulling the output (the last attempt on the video), it works properly.

### Expected behaviour

The component browser remains open.

### Screenshots or screencasts

https://user-images.githubusercontent.com/357683/236462850-1a816b0b-dfc3-4281-ad71-747305b50704.mp4

### Enso Version

a842130ff3162595f093e554a7d943c967146e63

### Browser or standalone distribution

Chromium

### Browser Version or standalone distribution

113.0.5672.63

### Operating System

Linux

**Comment by vitvakatu** [comment] 2023-05-07 22:10
I can't reproduce the closing thing, but it indeed opens when you start to drag the edge and quickly release the mouse button.

**Comment by wdanilo** [comment] 2023-05-08 01:03
@vitvakatu it should open when you `press - drag - release`. This is intentional.

**Comment by farmaazon** [comment] 2023-05-10 09:45
@xvcgreg as Ilya hasn't reproduced it, could you put a screencast with console logs?

**Comment by xvcgreg** [comment] 2023-05-10 09:54
@farmaazon sure, here you go:


https://github.com/enso-org/enso/assets/108271897/7c9b31d6-aabc-4467-809e-dc7425d0d7bd

also at the end please observe that CB is opened and I can still drag the connection

**Comment by xvcgreg** [comment] 2023-05-12 09:33
tested on https://github.com/enso-org/enso/actions/runs/4947660213?pr=6648 @farmaazon 

[2305121129 CLI log.txt](https://github.com/enso-org/enso/files/11461622/2305121129.CLI.log.txt)
[2305121129_shareX localhost-1683883871663.log](https://github.com/enso-org/enso/files/11461624/2305121129_shareX.localhost-1683883871663.log)

https://github.com/enso-org/enso/assets/108271897/10127f6a-bda9-47bf-8c6f-398d67586147



<blockquote><img src="https://opengraph.githubassets.com/4ae196528fbf65a16374a34c4dee2606420fca8d28d9e741f6ab7514ca1bf012/enso-org/enso" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/enso-org/enso">Add some logs for Component Browser destruction · enso-org/enso@10d8ceb</a></strong></div><div>Hybrid visual and textual functional programming. Contribute to enso-org/enso development by creating an account on GitHub.</div></blockquote>

**Comment by farmaazon** [comment] 2023-05-12 09:49
Ok, there was some misunderstanding here between me and @xvcgreg, so let's clarify some things:
1. Dragging out an edge and dropping it opens CB by design, as Wojciech wrote above.
2. Dragging out an edge and dropping it with two clicks too quickly is interpreted as double click, so we try to leave the current node. Perhaps it should be blocked when dragging and edge
3. I still cannot reproduce Component Browser being closed immediately after opening.

**Comment by 4e6** [comment] 2023-05-12 11:28
@farmaazon I cannot reproduce it anymore on the current develop

**Closed as not planned** 2023-05-15 10:50 UTC
Labels: d-intermediate, s-no-repro, p-high, --bug
