### ISSUE TITLE
Following renaming a project within the IDE, get an "Execution Failed" message and errors on the backend.

### ISSUE THREAD

**Issue by jdunkerley** [enso-org/enso#7062] opened 2023-06-19 10:02 UTC
Starting with a new empty project. 
I renamed it using the name in the title bar.

When I then added a file to the project and worked with it I got an "Execution failed." message. 
(no way to dismiss this but that is being dealt with).

https://github.com/enso-org/enso/assets/4699705/2e88421a-470c-4f82-aa5e-30550aa5045c

Backend had error:
`Resolution failed with [The package could not be resolved: The library `local.New_Project_9` is not defined within the edition.]`

**Comment by wdanilo** [comment] 2023-06-19 13:00
This is slightly related to one thing that we need to remember – the possibility to rename projects there should be removed. Instead, renaming projects should be performed only from the dashboard, which would allow us to rename folders immediately, not after closing the application.

**Comment by farmaazon** [comment] 2023-06-20 06:39
> This is slightly related to one thing that we need to remember – the possibility to rename projects there should be removed. Instead, renaming projects should be performed only from the dashboard, which would allow us to rename folders immediately, not after closing the application.

@wdanilo please create an issue for GUI.

**Comment by xvcgreg** [comment] 2023-06-28 06:59
Here's log with "execution failed" reproduced. It took some time to reproduce it this time. Usually it happens on first open of CB - this time I had to open and close it several times.

[20230628-065645-734-enso-project-manager.log](https://github.com/enso-org/enso/files/11891162/20230628-065645-734-enso-project-manager.log)

**Comment by xvcgreg** [comment] 2023-06-28 07:01
@MichaelMauderer what's the reason you have not assigned ``bug`` and ``regression`` labels here?

**Comment by MichaelMauderer** [comment] 2023-06-28 09:47
> @MichaelMauderer what's the reason you have not assigned `bug` and `regression` labels here?

I had removed the issue from triage, as someone was already assigned to the issue.

**Comment by hubertp** [comment] 2023-06-28 11:05
> Here's log with "execution failed" reproduced. It took some time to reproduce it this time. Usually it happens on first open of CB - this time I had to open and close it several times.
> 
> [20230628-065645-734-enso-project-manager.log](https://github.com/enso-org/enso/files/11891162/20230628-065645-734-enso-project-manager.log)

`ExecutionFailed` is a _normal_ response from language server that can happen on regular usage due to ongoing edits triggered by IDE.
Also, the original message message mentioned renaming being the trigger for the failure while I think you are trying to only use CB, right?

**Comment by xvcgreg** [comment] 2023-06-29 11:08
@hubertp I haven't renamed the project as @jdunkerley did - I can invoke this error message with just CB.

**Comment by hubertp** [comment] 2023-06-30 09:26
> @hubertp I haven't renamed the project as @jdunkerley did - I can invoke this error message with just CB.

I can see a number of `ExecutionFailed` messages with`Execution of function main interrupted.`. As I mentioned above, these are part of a regular flow and this is not what the original description talks about. As a matter of fact, that "interrupt" message has been so confusing to users (and IDE devs) that we decided not to report it anymore (https://github.com/enso-org/enso/pull/7143).

**Comment by hubertp** [comment] 2023-06-30 10:12
So following the change in #7143, the number of `ExecutionFailed` messages should be dramatically reduced, including in this case. 

Note that
> Backend had error:
> Resolution failed with [The package could not be resolved: The library local.New_Project_9 is not defined within the edition.]

Is not an error. It is being reported as a warning. 
Ideally we would like to get rid of that as well but there is a bit of a problem into how [package information](https://github.com/enso-org/enso/blob/develop/engine/runtime/src/main/java/org/enso/interpreter/runtime/Module.java#L93) is defined for the (runtime) Module and later [referenced](https://github.com/enso-org/enso/blob/develop/engine/runtime/src/main/scala/org/enso/compiler/Compiler.scala#L573) - it is all FS-based, rather than reading that data from `package.yaml`. Since FS changes happen on close, this is all working as expected.

I think [this](https://github.com/enso-org/enso/blob/develop/lib/scala/pkg/src/main/scala/org/enso/pkg/Package.scala#L169) should be changed anyway by reading from the package config file, if available, because we can have a valid scenario of a directory being named differently from `package.yaml` entry.

**Comment by hubertp** [comment] 2023-06-30 10:13
Also, not a regression.

**Closed as completed** 2023-07-03 09:36 UTC
Labels: --bug, -compiler, -language-server
