### ISSUE TITLE
Component Browser search does not like underscores

### ISSUE THREAD

**Issue by radeusgd** [enso-org/enso#5562] opened 2023-02-06 12:06 UTC
I was looking for the `to_text` method and once I typed `to_text` I did not get any results in the CB. This was confusing.

Apparently, I had to type `to text` (with _space_ instead of underscore), and only then did the documentation show up.

I think the CB should support both `_` and ` `. Moreover, if I typed the _exact_ method name - it should definitely be displayed instead of empty results.

**Comment by farmaazon** [comment] 2023-02-08 14:00
duplicate of #5102

**Closed as not planned** 2023-02-08 14:13 UTC
Labels: s-duplicate, --bug
