### ISSUE TITLE
When editing initial "sort" node I see all possible suggestions, not only suitable for first "sort" argument.

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5498] opened 2023-02-05 23:07 UTC
This task is automatically imported from the old Task Issue Board and it was originally created by Adam Obuchowicz.
Original issue is [here](https://www.pivotaltracker.com/story/show/181752141).
<hr />

### Steps to reproduce
1. Create a new project in Enso IDE
2. Start editing "sort" node

### Expected

The suggestion list contains values for the first argument of `sort`

### Actual

All suggestions (including examples) are displayed

### Notes

This was investigated a bit during work on https://github.com/enso-org/enso/pull/3338
(please read the _Issue 2_ section). There are two things looking wrong:
1. When editing starts, the first `search/complete` request (which filled `retrun_value` with proper type) does not receive any entries to show.
2. Accidentally, currently we ask the engine second time, because right after editing is started, the node emits an event with expression update, which in turn is caused by removing grayed-out arguments. This time searcher does not ask for specific return type, because it thinks that the user just came back to the method name. However it still seems inconsistent, as the searcher controller should filter by the already present method part.

We should not ask engine twice, so we should restore old behaviour (before the PR with workaround): the Searcher Pesenter should be created on `node_editing_started` event, not `node_being_edited`.

## Comments:
Is this referring to the old searcher? In which case it can be closed. (James Dunkerley - Feb 3, 2023)
<hr />

**Comment by vitvakatu** [comment] 2023-02-13 13:44
@farmaazon do you think we should close it? The issue is about the old searcher, and a lot of things changed since then. Though we still send a lot `search/complete` requests to the engine – I see 4 of them:
<img width="571" alt="image" src="https://user-images.githubusercontent.com/6566674/218474038-5e6b2ed9-458f-42f4-9bc8-1f9835131bf2.png">

Each request has a different return type.

**Comment by farmaazon** [comment] 2023-02-13 15:47
Yes, it outdated, as, according to the design, we want to actually have the behavior described in "Actual" section.

**Closed as not planned by farmaazon** 2023-02-13 15:47 UTC
Labels: s-wontfix, p-low, --bug
