### ISSUE TITLE
Can not click on a dropdown to change execution mode if the mouse pointer is above the text

### ISSUE THREAD

**Issue by sylwiabr** [enso-org/enso#6371] opened 2023-04-20 15:26 UTC
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

When I am trying to change the execution mode and click on a text with the name the dropdown is not working. I have to click on the green space next to the name.

### Expected behaviour

The whole button should be clickable.

### Enso Version

nightly 20.04.2023

### Browser or standalone distribution

Standalone distribution

### Browser Version or standalone distribution

standalone

### Operating System

MacOS

**Comment by jdunkerley** [comment] 2023-04-21 09:45
I cannot see the dropdown at all within Windows version regardless of where I click.

**Comment by Procrat** [comment] 2023-04-26 08:00
This was indeed an issue Michael and I had discovered a couple of weeks ago. As far as I know, Michael fixed it in #6341. That was only merged yesterday and I can't seem to reproduce this bug on the latest `develop` now.

Unless the problem persists on either of your ends, we can probably close this issue.

**Comment by vitvakatu** [comment] 2023-04-26 09:36
Just got confirmation from @jdunkerley that this does not work on Windows.

https://user-images.githubusercontent.com/6566674/234535314-6cddb97a-e085-4b22-82de-f3296b07d7bd.mp4

We need somebody with a Windows machine to debug it. cc @MichaelMauderer @farmaazon

**Comment by MichaelMauderer** [comment] 2023-04-26 10:07
I can try to repro this on Windows later today.

**Comment by MichaelMauderer** [comment] 2023-04-26 12:27
I cannot seem to build the IDE on Windows due to an npm issue. @farmaazon @mwu-tow, do you have a working windows build?

**Comment by wdanilo** [comment] 2023-04-27 03:04
Could anyone with on Windows show me screenshot of the app in the `ctlr+alt+4` and `ctrl+alt+5` modes, please?

**Comment by mwu-tow** [comment] 2023-04-27 04:13
> Could anyone with on Windows show me screenshot of the app in the `ctlr+alt+4` and `ctrl+alt+5` modes, please?

I got stuck on https://github.com/enso-org/enso/issues/6447 unfortunately :(

**Comment by MichaelMauderer** [comment] 2023-04-28 11:31
I can reproduce this now. Investigating.

**Closed as completed** 2023-05-02 16:32 UTC
Labels: d-easy, p-highest, --bug
