### ISSUE TITLE
Cannot rename project

### ISSUE THREAD

**Issue by xvcgreg** [enso-org/enso#6756] opened 2023-05-18 10:40 UTC
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

Inside Enso I cannot rename the project to any name - by entering text in the project name field
![image](https://github.com/enso-org/enso/assets/108271897/e5b615b1-d996-42ab-a129-1343ff29accd)

I can rename it in the dashboard and it carries to the folder name in the projects folder.

### Expected behaviour

I'd like to be able to rename projects.

### Enso Version

2023.5.18 nightly

### Browser or standalone distribution

Standalone distribution (local project)

### Browser Version or standalone distribution

standalone

### Operating System

Windows

### Operating System Version

Win11pro 22H2 22621.1555

### Hardware you are using

12th Gen Intel(R) Core(TM) i9-12900HK / RTX3060 Laptop / Nvidia Drivers 531.68

**Comment by hubertp** [comment] 2023-05-18 15:36
Logs?

**Comment by hubertp** [comment] 2023-05-18 15:38
Appears to be a duplicate of https://github.com/enso-org/enso/issues/6356 which is not a regression but a new feature request?

**Comment by xvcgreg** [comment] 2023-05-18 16:00
@hubertp Unfortunately I have met all the requirements of the naming conditions but I couldn't name my project. What is a regression - previously I was able to do it. Now renaming only works in the dashboard with the right mouse button context menu.

**Comment by hubertp** [comment] 2023-05-18 16:02
@xvcgreg And the name to which you tried to rename to was? I tried `New_Project_1` and that works for me.

**Comment by hubertp** [comment] 2023-05-18 16:13
Also, totally believe that you are getting the problem but with just a screnshot there is little I can do to fix it.

**Comment by xvcgreg** [comment] 2023-05-18 16:20
@hubertp 

https://github.com/enso-org/enso/assets/108271897/88af86fe-2203-4bf8-9f83-4af4b36cba4a

**Comment by hubertp** [comment] 2023-05-18 18:25
Good. This is your problem:
![Screenshot from 2023-05-18 20-25-11](https://github.com/enso-org/enso/assets/292128/24848c54-e02f-4d45-848b-b555b76751cb)
Someone familiar with that codebase can come up with a reasonable solution. I don't know why a ref to project manager is not available. Maybe asking too early?

**Comment by somebody1234** [comment] 2023-05-18 18:59
seems like the way dashboard opens the IDE, the IDE is never connected to the project manager - it seems it can either have only the Project Manager, or only the language server endpoints:
https://github.com/enso-org/enso/blob/a32a2eafbadc75c8ad5d350f4932977c2f9bb127/app/gui/src/ide/initializer.rs#L131-L137

the implication of this is that under the new dashboard, the IDE *never* has access to the project manager anymore... not sure what's the best solution, as the dashboard does need access to the project manager to, well, manage projects

assuming the end goal is for the dashboard to replace the current project list, i *think* that means the IDE shouldn't be accessing the Project Manager anyway - in which case it could just, say, send a JS event to the dashboard requesting a rename, or maybe execute a callback provided by JS, if it needs to read the result

**Comment by xvcgreg** [comment] 2023-05-19 07:01
@farmaazon Is the solution that @somebody1234 proposed valid for you? If so please create a task for that JS event.

**Comment by farmaazon** [comment] 2023-05-19 11:03
The solution is ok, but I would keep this issue as a ticket for JS event implementation.

**Comment by somebody1234** [comment] 2023-05-23 09:36
not sure whether it's possible for both the dashboard and the IDE to open the Project Manager at the same time.
if it is, alternative solutions are:
- expose a function from wasm, which when called, will change the currently opened project
- allow passing `project_name` (`Option<String>`) to `BackendService::ProjectManager`

(of course, the currently suggested solution is fine - these are just options in case removing the current project switcher is actually *not* the plan)

just investigated whether `startup.project` can be passed with `projectManagerUrl`, but it looks like it's only supported when opening with `LanguageServer`:

https://github.com/enso-org/enso/blob/e35bc177947d9e5a2b4d6533981616d647337b3a/app/gui/src/config.rs#L85-L98

**Comment by farmaazon** [comment] 2023-05-23 12:44
> just investigated whether startup.project can be passed with projectManagerUrl, but it looks like it's only supported when opening with LanguageServer:

Actually, it is supported, but in a different way: having Project Manager endpoints, we try to open the project with name specified by `startup.project` option.

**Closed as completed** 2023-05-30 12:42 UTC
Labels: p-high, --bug, --regression
