### ISSUE TITLE
Weird squiggles above text

### ISSUE THREAD

**Issue by hubertp** [enso-org/enso#6906] opened 2023-05-31 09:42 UTC
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

![Screenshot from 2023-05-31 11-40-06](https://github.com/enso-org/enso/assets/292128/6361912b-9f14-47e2-b884-543c91401f35)

Notice the two lines above `2023`

More examples (`Issuing`):
![Screenshot from 2023-05-31 12-00-10](https://github.com/enso-org/enso/assets/292128/2013c7f7-4156-47cc-bdbb-6382d8e40fad)

### Expected behaviour

No additional lines.

### Enso Version

95df61af50f6b3524058fe17976f5056d43383b2

### Browser or standalone distribution

Chrome

### Browser Version or standalone distribution

110.0.5481.100

### Operating System

Linux

**Comment by farmaazon** [comment] 2023-05-31 10:47
Duplicate of #6061

**Closed as not planned** 2023-06-12 08:37 UTC
Labels: s-duplicate, --bug
