### ISSUE TITLE
If a grouped component has an underscore as a placeholder input then double clicking on it does not open the group

### ISSUE THREAD

**Issue by AdRiley** [enso-org/enso#10281] opened 2024-06-13 13:29 UTC
![Image](https://github.com/enso-org/enso/assets/1720119/ec3970bf-78d8-436a-b40b-09882f34dfdb)

**Comment by farmaazon** [comment] 2024-06-13 13:32
Is it a proper screenshot? I don't see any grouped components there.

**Comment by kazcw** [comment] 2024-06-13 13:41
This is a complex issue. If the component has an underscore placeholder, the component doesn't call the method--it just creates a function that will call the method if completed with the missing argument. Currently, we can only enter a called method. We could add support for entering the un-executed definition of a method, though we'd have less information from the backend in that state.

**Comment by JaroslavTulach** [comment] 2024-06-27 14:30
The specification for [underscore arguments is here](https://github.com/enso-org/enso/blob/d95ebd483684f270cb1ee04ae126d3be3560b086/docs/syntax/function-arguments.md#underscore-arguments) and as far as I can tell, the current behavior is correct. The following `Main.enso` program assigns _lambda function_ to variable `node`:
```ruby
$ cat Main.enso 
from Standard.Base import all

foo a = a + 2

main =
    node = Main.foo _
    node
```
test with:
```
./built-distribution/enso-engine-0.0.0-dev-linux-amd64/enso-0.0.0-dev/bin/enso --run Main.enso
Main.main.node[Main.enso:6:12-21] <internal-0>=_
```
e.g. there is no invocation. If you want to invoke the function in `node`, change the last line to `node 40`, for example. This is different to
```ruby
main =
     node = Main.foo
     node
```
where there is an **attempt to partially invoke** function `foo` - e.g. the IDE gets notification about the attempt and also information that argument `a` has not been supplied.

**Comment by farmaazon** [comment] 2024-06-28 10:21
For GUI, the only way to handle this would be implementing some sort of name resolution, which is duplicating work the engine is already doing, and still I'm not sure if we get all the needed information. 

Alternatively, the engine could implement [an eta conversion](https://wiki.haskell.org/Eta_conversion) compiler step, to internally convert expressions like 
```
node = bar a _
```
to
```
node = bar a
```
or more complex example
```
node = bar _ a fourthArg=b
```
becomes 
```
node = bar secondArg=a fourthArg=b
```

Of course, handling also lambdas (`a -> foo a` ⇾ `foo`) would be nice if not particularly harder.

@AdRiley @JaroslavTulach @jdunkerley so I'm reassigning it to Dmitry to be planned for engine, as the second solution is much better IMO.

**Comment by farmaazon** [comment] 2024-07-05 07:04
From [Discord discussion](https://discord.com/channels/401396655599124480/1255794325447770164/1258418844868018187)

> I did it using the code editor as I think that is how James first taught me.
Perhaps if we don't need the _ and the GUI doesn't generate one then this isn't an issue any more. We just need to make sure I stop adding underscores and don't teach anyone else that way.

So I guess this issue may have low priority

**Comment by JaroslavTulach** [comment] 2024-07-08 05:47
> > I did it using the code editor 
> So I guess this issue may have low priority

I'd even claim it is **not a bug**. Enso is [Turing complete language](http://wiki.apidesign.org/wiki/Turing_complete) and we _cannot statically understand_ what the code does in 100% of cases. This one is an edge case, where we could improve, but the benefit seems small for now.

> > Perhaps  ... don't teach anyone else (adding underscores)

Enough to `Main.collapsed` instead of `Main.collapsed _`.

**Closed as not planned by JaroslavTulach** 2024-07-08 05:47 UTC
Labels: p-low, --bug, -language-server, -gui
