### ISSUE TITLE
Performance problems when diconnecting/reconnecting nodes

### ISSUE THREAD

**Issue by sylwiabr** [enso-org/enso#6471] opened 2023-04-28 12:34 UTC
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

When disconnecting the node by clicking on the connection -specially closer to the second node (the one that has the input connected), a significant perf drop can be observed. Connection is glued to the mouse pointer and there are issues with dropping it/reconnecting.

### Expected behaviour

Disconnecting/reconnecting nodes works smoothly.

### Screenshots or screencasts

![Enso_18NaPqDRuz](https://user-images.githubusercontent.com/12892578/235148338-e86ddcf1-a5f4-4583-b02c-3b8d23eeb5c2.gif)

### Enso Version

nightly 28.04.2023

### Browser or standalone distribution

Standalone distribution

### Browser Version or standalone distribution

standalone

### Operating System

Windows

**Comment by MichaelMauderer** [comment] 2023-05-01 11:53
I can't seem to reproduce it. Might be worth checking it out on our reference hardware, @kazcw?

**Comment by kazcw** [comment] 2023-05-01 15:04
1. The GUI is blocking while detaching a connection, probably while responding to updates from the backend resulting from the edit. This seems to happen consistently when disconnecting an input that causes a lot of nodes to enter the error state. It would be nice if handling these updates didn't block redraw, but first we should look at why they require so much CPU work in the frontend.
2. Sometimes a node's output can't be reconnected. This always co-occurs with a logged warning like `Internal error. Symbol ID Symbol { id: GlobalInstanceId(2221) } is not registered.`, however that type of warning is also observed when altering connections without observing any bug. In any case, this is a logic bug, while (1) seems like purely a performance issue. Since this bug seems to be encountered when the delay in (1) is particularly noticeable, it may be a concurrency problem.

**Comment by kazcw** [comment] 2023-06-12 19:56
(1) is fixed by #6954. (2) is #6772.

**Closed as completed** 2023-06-14 18:16 UTC
Labels: p-high, --bug, --low-performance
