### ISSUE TITLE
Component Browser Doc section hint string not cleared out from the node graph

### ISSUE THREAD

**Issue by xvcgreg** [enso-org/enso#6518] opened 2023-05-03 08:51 UTC
### What type of issue is this?

Intermittent – Occurring irregularly

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

Just noticed (barely visible) hint string hanging rendered on the blank canvas. Do not know when it was generated. Also I cannot determine if it's a regression or not - due to the fact it's hard to spot.

https://user-images.githubusercontent.com/108271897/235871286-e15523ba-c953-4325-bc46-e2832ddc7fe5.mp4

### Expected behaviour

Text should disappear after tooltip/hint fades out.

### Enso Version

2023.5.2 nightly

### Browser or standalone distribution

Standalone distribution

### Browser Version or standalone distribution

standalone

### Operating System

Windows

### Operating System Version

Win11pro 22H2 22621.1555

### Hardware you are using

12th Gen Intel(R) Core(TM) i9-12900HK / RTX3060 Laptop / Nvidia Drivers 531.68

**Comment by xvcgreg** [comment] 2023-05-03 08:52
It disappeared on CB open.

**Comment by vitvakatu** [comment] 2023-05-03 14:01
I've seen it once recently, but I can't reliably reproduce it. It is probably a race condition in FRP logic. I think adding some additional precautions to the documentation panel will fix it.

**Comment by wdanilo** [comment] 2023-05-03 14:03
> I've seen it once recently, but I can't reliably reproduce it. It is probably a race condition in FRP logic. I think adding some additional precautions to the documentation panel will fix it.

Hmmm, but if you are removing component browser from stage, all of its items should be dropped and thus should disappear. To me, that looks more like memory leak.

**Comment by vitvakatu** [comment] 2023-05-03 14:27
We do not drop component browser when it is not visible (because its creation is expensive), if I remember correctly. But it might be the memory leak indeed

**Comment by wdanilo** [comment] 2023-05-03 14:29
But you are detaching its root from the display object hierarchy, right? If so, all children should detach as well. If you are unsetting parent of any node in the display object hierarchy and something is still on the screen, this is a bug with our child-parent handling probably. Fixing that in the components logic is a bad solution. Anyway, could you please confirm to me that what happens here is that you are unsetting parent of the root element and some child elements are still visible?

**Comment by farmaazon** [comment] 2023-05-08 08:34
Yes, according to the code we detach searcher from display object hierarchy.

**Comment by farmaazon** [comment] 2024-02-26 09:54
Closing now, as GUI2 use different framework, so the problem should nod appear there.

**Closed as not planned by farmaazon** 2024-02-26 09:54 UTC
Labels: d-easy, p-lowest, --bug
