### ISSUE TITLE
16% startup regression after including GraalPy

### ISSUE THREAD

**Issue by JaroslavTulach** [enso-org/enso#8553] opened 2023-12-15 06:24 UTC
The [stdlib startup benchmarks](https://enso-org.github.io/engine-benchmark-results/stdlib-benchs.html) indicate startup time regression for:
- `Startup_empty_startup` - 16%
- `Startup_hello_world_startup` - 12%

The regression happened between Dec 1 and Dec 4 with the only two integrations being:
- #8432
- #8351 

Given the #8432 is only a test change, the slowdown is probably related to #8351. Why? Python isn't used during the startup at all - e.g. there is no reason for it to slow startup down!

**Comment by Akirathan** [comment] 2023-12-27 15:44
The additional startup time seems to be caused by the JVM boot module layer initialization. To proof that, I have designed an experiment at https://gist.github.com/Akirathan/9c30e10ec525eb09c91c3c94e2c36f40 that repeatedly invokes `java --module-path <component-directory> -m org.enso.runtime/EngineBootLoader --help` (i.e. `enso --help`) that does not do any polyglot stuff, just loads a bunch of classes and prints help. There are some comments in the experiment explaining the results.

In other words, if we exclude `graalpy-language-23.1.0.jar` and its dependencies from `--module-path`, the startup time is **852 ms**, if we include graalpy, the startup time is **1178 ms**.

<blockquote><img src="https://github.githubassets.com/assets/gist-og-image-54fd7dc0713e.png" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> Gist</div><div><strong><a href="https://gist.github.com/Akirathan/9c30e10ec525eb09c91c3c94e2c36f40">GraalPy startup experiment</a></strong></div><div>GraalPy startup experiment. GitHub Gist: instantly share code, notes, and snippets.</div></blockquote>

**Comment by Akirathan** [comment] 2023-12-27 15:56
As noted in https://gist.github.com/Akirathan/9c30e10ec525eb09c91c3c94e2c36f40?permalink_comment_id=4808928#gistcomment-4808928, the total size of all the GraalPy Jars is **201 MB**. All the GraalPy Jars that are additionally included are:
```python
['bcpkix-jdk18on-1.76.jar', 'bcprov-jdk18on-1.76.jar', 'bcutil-jdk18on-1.76.jar', 'insight-tool-23.1.0.jar', 'llvm-api-23.1.0.jar', 'python-language-23.1.0.jar', 'python-resources-23.1.0.jar', 'truffle-nfi-23.1.0.jar', 'truffle-nfi-libffi-23.1.0.jar', 'xz-1.9.jar']
```

How to inspect what does JVM do with these Jars during boot? Please help @JaroslavTulach.

<blockquote><img src="https://github.githubassets.com/assets/gist-og-image-54fd7dc0713e.png" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> Gist</div><div><strong><a href="https://gist.github.com/Akirathan/9c30e10ec525eb09c91c3c94e2c36f40">GraalPy startup experiment</a></strong></div><div>GraalPy startup experiment. GitHub Gist: instantly share code, notes, and snippets.</div></blockquote>

**Comment by JaroslavTulach** [comment] 2023-12-29 05:40
> How to inspect what does JVM do with these Jars during boot?

Please use [--profiling-path option](https://github.com/enso-org/enso/blob/27431c126c9ea2e487d5de77c2de359981c6f127/docs/profiler/engine-startup.md).

**Comment by JaroslavTulach** [comment] 2023-12-29 05:44
What happens during the startup? I am not sure, but one of the hypothesis is: Python _unpacks its resources_. If so, then the solution would be [somewhere along this copyResources method](https://www.graalvm.org/truffle/javadoc/org/graalvm/polyglot/Engine.html#copyResources-java.nio.file.Path-java.lang.String...-) and the properties it mentions `polyglot.engine.resourcePath` & co.

**Comment by Akirathan** [comment] 2023-12-29 12:19
> > How to inspect what does JVM do with these Jars during boot?
> 
> Please use [--profiling-path option](https://github.com/enso-org/enso/blob/27431c126c9ea2e487d5de77c2de359981c6f127/docs/profiler/engine-startup.md).

`--profiling-path` is only usable when you actually run some Enso code. If you just run `enso --help` (or `enso --version`), the profiler will not even start, resulting in an empty profiling file. The thing is that the slowdown is in the JVM initialization, without any `org.graalvm.polyglot.Context`.

I have a strong suspicion that the slowdown happens before the `main` method is executed.

## Experiments with -Xlog
I have decided to do additional experiments with a combination of `-Xlog` flags (https://docs.oracle.com/en/java/javase/21/docs/specs/man/java.html#enable-logging-with-the-jvm-unified-logging-framework) (All these experiments run just `enso --help`):

`-Xlog:class+load=trace` to look into all the loaded classes. There doesn't seem to be a significant difference between how many classes are loaded: 3011 vs 3116. No classes from any `graalpy` module nor its dependencies are loaded, obviously.
 
`-Xlog:module+load=trace` to look into the modules loading. Number of loaded modules differ, obviously. The duration of loading `python-language`, or `python-resources`, or any other graalpy-related module is negligible. The log files generated with something like:
```
java --module-path <comp-dir> -Xlog:module+load=trace:file=small
-modules.txt:uptime,timenanos,level,tags -m org.enso.runtime/org.ensoEngineRunnerBootLoader --help
```
are [small-modules.txt](https://github.com/enso-org/enso/files/13793391/small-modules.txt) and [big-modules.txt](https://github.com/enso-org/enso/files/13793394/big-modules.txt).

In these log files, we can see that the JVM loads `java.base` module as the very first module and that there is a delay before the second module is loaded. This delay is different for small-modules and big-modules. In `small-modules.txt`, the uptime of the second loaded module is `0.333s`, which in `big-modules.txt`, the uptime of the second loaded module is `0.555s`. So what happens after `java.base` module is loaded and before the second module is loaded, how do we find that out? The difference is **220 ms**!


<blockquote><div><strong><a href="https://docs.oracle.com/en/java/javase/21/docs/specs/man/java.html#enable-logging-with-the-jvm-unified-logging-framework">The java Command</a></strong></div></blockquote>

**Comment by Akirathan** [comment] 2023-12-29 12:21
> What happens during the startup? I am not sure, but one of the hypothesis is: Python _unpacks its resources_. If so, then the solution would be [somewhere along this copyResources method](https://www.graalvm.org/truffle/javadoc/org/graalvm/polyglot/Engine.html#copyResources-java.nio.file.Path-java.lang.String...-) and the properties it mentions `polyglot.engine.resourcePath` & co.

As mentioned in [my previous comment](https://github.com/enso-org/enso/issues/8553#issuecomment-1872010927), I am running these experiments with just `enso --help`. So no `org.graalvm.polyglot.Context` gets initialized. So no `EnsoLanguage`, neither `PythonLanguage` classes get loaded. The slowdown happens somewhere in JVM internals during boot, before `main` method is executed.

**Comment by JaroslavTulach** [comment] 2024-01-02 07:08
> I am running these experiments with just `enso --help`.

The real benchmarks can be executed as:
```bash
./built-distribution/enso-engine-0.0.0-dev-linux-amd64/enso-0.0.0-dev/bin/enso --run test/Benchmarks/ Startup
```
If you want to run exactly what "empty_startup" benchmark runs, then do:
```bash
./built-distribution/enso-engine-0.0.0-dev-linux-amd64/enso-0.0.0-dev/bin/enso --run test/Benchmarks/src/Startup/Empty_World.enso
```
if you add `--profiling-path slow.npss` to the above command, you'll see what the JVM does. I am attaching two `.npss` files [FastAndSlow.zip](https://github.com/enso-org/enso/files/13807752/FastAndSlow.zip) for your convenience. They differ by 400ms. Now the question is why and where do they differ?

**Comment by JaroslavTulach** [comment] 2024-01-02 10:17
The `slow.npss` file seems to spend 100ms in _JAR verification_. Module constructor seems to be slower: 

![obrazek](https://github.com/enso-org/enso/assets/26887752/0993355e-303d-4127-bd11-c4f5e2ee026a)

This is probably caused by having some signed JAR in the system. The JDK tries to verify it and slows things down.

**Comment by Akirathan** [comment] 2024-01-02 17:17
> The `slow.npss` file seems to spend 100ms in _JAR verification_. Module constructor seems to be slower:
> 
> ![obrazek](https://private-user-images.githubusercontent.com/26887752/293669930-0993355e-303d-4127-bd11-c4f5e2ee026a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxOTA5NTgsIm5iZiI6MTcwNDE5MDY1OCwicGF0aCI6Ii8yNjg4Nzc1Mi8yOTM2Njk5MzAtMDk5MzM1NWUtMzAzZC00MTI3LWJkMTEtYzRmNWUyZWUwMjZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAyVDEwMTczOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgzNDdmYTI0Njk0ODQ2MDVlZGRkYzdhN2VjNWQ4MWQwYzNhNWI3NjQ2MTU3YzExZTljNzgzODNjOWRlYmU5NTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.j3p5P2Quw4cbBBjO1YYeb7vVYE9dJJd5WRPJoWnwTDY)
> 
> This is probably caused by having some signed JAR in the system. The JDK tries to verify it and slows things down.

I can confirm this observation. The signed JARs are `bcpkix-jdk18on-1.76.jar`, `bcprov-jdk18on-1.76.jar` and `bcutil-jdk18on-1.76.jar`. These JARs were added as separate modules in #8351. Moreover, `org.enso.runtime` module has declared dependency in https://github.com/enso-org/enso/blob/21d164ec3eb37b9eff0e030146dff8963de31ca8/engine/runtime-fat-jar/src/main/java/module-info.java#L11 because we use it for simple SHA1 digest computation in `org.enso.interpreter.caches.ModuleCache`. We already have a task to remove this dependency - https://github.com/enso-org/enso/issues/8362.

I have also tried to manually remove signatures from these Jar archives, but failed to do so. I have tried to remove checksum entries from `META-INF/MANIFEST` as well as `*.DSA` and `*.SF` files from `META-INF`, but enso still failed on `ModuleInitializationError`.

Previously (before #8351), the bouncycastle modules used to be assembled in `runtime.jar` fat jar, so there was no signature checking by the JVM.

**Comment by Akirathan** [comment] 2024-01-04 16:19
`org.bouncycastle` dependencies were removed in #8664, but did not provide any benchmarks improvements.

**Comment by JaroslavTulach** [comment] 2024-01-05 11:12
> if you add `--profiling-path slow.npss` to the above command, you'll see what the JVM does. I am attaching two `.npss` files [FastAndSlow.zip](https://github.com/enso-org/enso/files/13807752/FastAndSlow.zip) for your convenience. They differ by 400ms. Now the question is why and where do they differ?

Here is a 3rd [ZIP with t.npss file](https://github.com/enso-org/enso/files/13841291/2024-01-05.zip). It runs in 1800ms - e.g. just in the middle of [FastAndSlow.zip](https://github.com/enso-org/enso/files/13807752/FastAndSlow.zip). Looks like the #8664 fix helped to give us 50% of the time back. We still need to find the next 50%.

**Comment by JaroslavTulach** [comment] 2024-01-05 13:34
Also reported
- #8692

**Comment by Akirathan** [comment] 2024-01-05 13:59
Another startup initialization issue revealed: https://github.com/enso-org/enso/issues/8690. It's not related to GraalPy though.

**Comment by Akirathan** [comment] 2024-01-05 15:15
> `org.bouncycastle` dependencies were removed in #8664, but did not provide any benchmarks improvements.

Edit: Removing `org.bouncycastle` helped the startup by 10%. Let's close this issue and continue with #8690.

**Closed as completed by Akirathan** 2024-01-05 15:15 UTC
Labels: p-high, -compiler, --low-performance
