### ISSUE TITLE
Python date fails with NullPointerException

### ISSUE THREAD

**Issue by Akirathan** [enso-org/enso#8913] opened 2024-01-31 12:36 UTC
During the migration of `Base_Tests` to the new test builder API in #8890, I declared the "Python Date" tests as pending, because they started to fail transiently. On the CI, the error is, e.g., in https://github.com/enso-org/enso/actions/runs/7725103039/job/21058624499?pr=8890#step:10:12999.

To reproduce, revert 94792cf0dbdd1a0fb197d2f8f7162b09bb0de2be, and run `enso --run test/Base_Tests/src/Data/Time/Date_Spec.enso`.

**Comment by JaroslavTulach** [comment] 2024-01-31 12:55
Duplicate of #8632

**Comment by JaroslavTulach** [comment] 2024-02-13 09:55
Closing this as duplicate.

**Closed as completed by JaroslavTulach** 2024-02-13 09:55 UTC
Labels: s-duplicate, --bug, -compiler
