### ISSUE TITLE
When scrolling the JSON visualisation the mouse cursor does not move. 

### ISSUE THREAD

**Issue by MichaelMauderer** [enso-org/enso#2941] opened 2021-04-26 10:23 UTC
### What did you do?
* Open a JSON visualization of a long list
* Scrolled the list. 

### What did you expect to see?
The cursor moving with the scrollbar.

### What did you see instead?
https://user-images.githubusercontent.com/1428930/116067876-e05f3b80-a689-11eb-8e2d-0071c353fe7b.mp4

### Enso Version
8a6d90e

**Comment by vitvakatu** [comment] 2021-11-03 13:08
Reproduced it on the latest develop (`c822256e6c531`), here are my thoughts:
It looks like JSON-visualization is now implemented as [RawText visualization](https://github.com/enso-org/enso/blob/22cefa7659e9a57513323692fcbef9259d956ac1/gui/src/rust/ide/view/graph-editor/src/builtin/visualization/native/raw_text.rs). This visualization uses simple `div` element with `overflow-y: auto` and `overflow-x: auto` CSS properties, and this is the reason scrollbars are actually exist.

However, we also have [ScrollArea](https://github.com/enso-org/enso/blob/22cefa7659e9a57513323692fcbef9259d956ac1/gui/src/rust/ensogl/lib/components/src/scroll_area.rs) component. I checked it, and it actually works in the [demo-scene](https://github.com/enso-org/enso/blob/22cefa7659e9a57513323692fcbef9259d956ac1/gui/src/rust/ensogl/example/src/scroll_area.rs) correctly (i.e. cursor moves when scrolling).

I'm not sure what exactly causes this issue, but it makes sense to try and rewrite `RawText` implementation to use `ScrollArea` for scrolling behavior. It is not that easy, as `ScrollArea` requires `Application` in its constructor, but [visualizations API](https://github.com/enso-org/enso/blob/22cefa7659e9a57513323692fcbef9259d956ac1/gui/src/rust/ide/view/graph-editor/src/component/visualization/definition.rs#L67) accepts `Scene` only.

My proposal:
1. Swap `Scene` with `Application` for native visualizations
2. Use `ScrollArea` in `RawText` for scrolling behavior
3. Hope that the issue will be fixed by this step

**Comment by farmaazon** [comment] 2021-11-03 13:38
ScrollArea in this case would affect the position of the div. And as I remember, the clipping is still not implemented (@wdanilo correct me if I'm wrong), we cannot do this by moving the text position.

Instead, we could use two scrollbar components (not ScrollArea) and update scrollLeft and scrollTop properties of div when the user is scrolling.

**Comment by vitvakatu** [comment] 2021-11-03 14:21
@farmaazon Scrollbar components also require `Scene` -> `Application` transition, but we can go that road. It seems that the correct long-term solution would be `ScrollArea` anyway, so perhaps it makes sense to finish `ScrollArea` implementation and then return to this issue.

**Comment by vitvakatu** [comment] 2021-11-08 14:56
The issue also applies to Documentation view

**Closed as completed** 2022-04-14 20:43 UTC
