### ISSUE TITLE
After stopping the project GUI still attempts to the connect to the language server

### ISSUE THREAD

**Issue by hubertp** [enso-org/enso#8966] opened 2024-02-05 12:05 UTC
To reproduce:
1. Open any project 
2. Once loaded switch to project manager
3. Click stop the project
4. Console starts to spit up errors about not being able to connect to the websocket

![Screenshot from 2024-02-05 13-03-14](https://github.com/enso-org/enso/assets/292128/67d0590e-1fac-4007-bb69-db89557613a4)

**Comment by farmaazon** [comment] 2024-02-05 13:02
Duplicate of [#8964](https://github.com/enso-org/enso/issues/8964)

**Closed as not planned by farmaazon** 2024-02-05 13:02 UTC
Labels: s-duplicate, -project-manager, -gui
