### ISSUE TITLE
Clicking inside vector editor in node does not focus the node

### ISSUE THREAD

**Issue by Akirathan** [enso-org/enso#6677] opened 2023-05-12 18:38 UTC
[Screencast from 2023-05-12 20-37-18.webm](https://github.com/enso-org/enso/assets/14013887/62e44e70-a87c-4917-a022-41b226feb8dc)

**Comment by wdanilo** [comment] 2023-05-17 05:44
This is NOT a bug. Clicking on widgets should interact with them. Here, the drop-downs should be opened (instead of clicking in the arrow icon, which will be soon removed). Node selection can't be done by clicking on widgets. Instead, you can click on the node icon (not yet implemented), node name, or node highlight (not yet implemented). The last thing - highlight, should be shown around node when mouse is close. Clicking it should select the node. CC @Frizi - would you be able to create a task for it and close this issue as WONTFIX then?

**Comment by farmaazon** [comment] 2023-05-22 10:13
@Frizi bump ^

**Comment by farmaazon** [comment] 2023-05-29 10:36
@Frizi bump^

**Comment by Frizi** [comment] 2023-05-29 11:43
Issue created: https://github.com/enso-org/enso/issues/6872

**Closed as not planned by Frizi** 2023-05-29 11:43 UTC
Labels: s-wontfix
