### ISSUE TITLE
Going back from table's visualization in full screen mode stretches the first column

### ISSUE THREAD

**Issue by hubertp** [enso-org/enso#6094] opened 2023-03-27 21:44 UTC
### What type of issue is this?

Permanent – Ocurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

When visualizing a table to a full screen mode it will, correctly, span to the whole width of the window.
When going back to the project view with all the nodes and the preview of the visualization it keeps the really long width of the first column making it unusable (see screenshot). Closing/reopening the visualization fixes the problem.

### Expected behaviour

Should consistently keep column widths, even when coming back from full screen mode.

### How we can reproduce it?

1. Visualize data from one of the bookclubs
2. Double-space to enter full screen mode
3. Single space to go back to the project 
4. Notice how the column has the wrong width

### Screenshots or screencasts

Bug in three acts:
![Screenshot from 2023-03-27 15-29-50](https://user-images.githubusercontent.com/292128/228073082-c4622091-cd7a-41d4-8187-63fb0e8d374f.png)
![Screenshot from 2023-03-27 15-30-14](https://user-images.githubusercontent.com/292128/228073109-ae6ae3d8-a600-4d66-a48d-e3063c1955f6.png)
![Screenshot from 2023-03-27 15-30-35](https://user-images.githubusercontent.com/292128/228073166-6cefaf24-3460-4c4d-aa6d-a9e9fe001eb2.png)

### Enso Version

develop

### Browser or standalone distribution

Chrome

### Browser Version or standalone distribution

110.0.5481.100

### Operating System

Linux

**Comment by farmaazon** [comment] 2023-03-28 08:45
Duplicate of https://github.com/enso-org/enso/issues/5966

**Closed as not planned by farmaazon** 2023-03-28 08:45 UTC
Labels: s-duplicate, --bug
