### ISSUE TITLE
Join tool widget

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5403] opened 2023-02-05 23:02 UTC
This task is automatically imported from the old Task Issue Board and it was originally created by Wojciech Daniło.
Original issue is [here](https://www.pivotaltracker.com/story/show/182746350).
<hr />

No description provided.

**Comment by jdunkerley** [comment] 2023-02-21 14:33
Duplicate of #5629

**Closed as completed by jdunkerley** 2023-02-21 14:33 UTC
Labels: x-new-feature
