### ISSUE TITLE
Widgets visualization appears to be cut/adjusted to the node's length

### ISSUE THREAD

**Issue by hubertp** [enso-org/enso#9442] opened 2024-03-15 09:15 UTC
As per screenshot
![Screenshot from 2024-03-14 16-40-34](https://github.com/enso-org/enso/assets/292128/1bc31495-0c02-4f81-9e40-4df148595d70)

**Comment by farmaazon** [comment] 2024-03-15 11:36
Duplicate of https://github.com/enso-org/enso/issues/9379

**Closed as not planned by farmaazon** 2024-03-15 11:36 UTC
Labels: s-duplicate, -gui
