### ISSUE TITLE
`HttpDownloaderTest.downloadBigFileWithProgress` failing

### ISSUE THREAD

**Issue by mwu-tow** [enso-org/enso#9193] opened 2024-02-26 23:48 UTC
[See the following CI run](https://github.com/enso-org/enso/actions/runs/8006012236/job/21866755453#step:8:1354): 

```
[error] Test org.enso.downloader.http.HttpDownloaderTest.downloadBigFileWithProgress failed: java.lang.AssertionError: Progress reported was called at least once
[error] Expected: a value greater than <0>
[error]      but: <0> was equal to <0>, took 0.016 sec
[error]     at org.enso.downloader.http.HttpDownloaderTest.downloadBigFileWithProgress(HttpDownloaderTest.java:132)
[error]     at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[error]     at java.lang.reflect.Method.invoke(Method.java:580)
[error]     ...
Finalizing HTTP server...
[info] ScalaTest
[info] Run completed in 4 seconds, 591 milliseconds.
[info] Total number of tests run: 5
[info] Suites: completed 3, aborted 0
[info] Tests: succeeded 5, failed 0, canceled 0, ignored 0, pending 0
[info] All tests passed.
[error] Failed: Total 11, Failed 1, Errors 0, Passed 10
[error] Failed tests:
[error] 	org.enso.downloader.http.HttpDownloaderTest
```

[Full log archive attached.](https://github.com/enso-org/enso/files/14412491/logs_21015869135.zip).

**Comment by Akirathan** [comment] 2024-02-27 09:29
This test was originally added by me. I was surprised about its flaky nature. I added https://github.com/enso-org/enso/pull/9094/files#diff-194758bc191e47ab478914cdd239bf59dd5aad05bd0116895efe5a9819cde5ae in one of my recent PRs to try to force the failure more often so that we can see whether we should somehow declare this test as *flaky*. The problem is, that this test uses JUnit, and I don't know how to declare a JUnit test as flaky.

<blockquote><img src="https://avatars.githubusercontent.com/u/14013887?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/enso-org/enso/pull/9094">Upload native-image argfiles by Akirathan · Pull Request #9094 · enso-org/enso</a></strong></div><div>Pull Request Description
In PR #8953, in commit ba0a69d, I have introduced argument files to the native-image. In this PR, let&#39;s try to upload these argfiles as artifacts on GH, so that we can ...</div></blockquote>

**Comment by JaroslavTulach** [comment] 2024-03-12 10:31
Isn't this resolved by 
- #9339

making the test flaky?

**Comment by Akirathan** [comment] 2024-03-12 12:08
> Isn't this resolved by
> 
>     * [Declare HTTPDownloaderTest as flaky #9339](https://github.com/enso-org/enso/pull/9339)
> 
> 
> making the test flaky?

Most probably yes. Let's close this issue for now, and potentially re-open it if there are any further problems with this test in the future.

**Closed as completed by Akirathan** 2024-03-12 12:08 UTC
Labels: -ci, p-low, -language-server
