### ISSUE TITLE
IDE sometimes replaces the node contents when edited

### ISSUE THREAD

**Issue by 4e6** [enso-org/enso#6580] opened 2023-05-05 13:10 UTC
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

IDE replaces the contents of the node when you ctrl-click to edit and then exit without editing. Reproducible with the `Text.characters` function (see the video).

### Expected behaviour

IDE does not replace the node contents.

### Screenshots or screencasts

https://user-images.githubusercontent.com/357683/236466156-399b0637-d6e5-4ec3-ba57-212a38d59f24.mp4

### Enso Version

a842130ff3162595f093e554a7d943c967146e63

### Browser or standalone distribution

Chromium

### Browser Version or standalone distribution

113.0.5672.63

### Operating System

Linux

**Comment by vitvakatu** [comment] 2023-05-07 22:08
Duplicate of #6411 

Fixed in #6594

**Closed as not planned by vitvakatu** 2023-05-07 22:08 UTC
Labels: s-duplicate, --bug
