### ISSUE TITLE
Unable to access constructor value in interactive mode

### ISSUE THREAD

**Issue by 4e6** [enso-org/enso#7184] opened 2023-07-03 11:51 UTC
## Issue

In the interactive mode, when trying to create a node with a type getter, it returns an error that the method is not available. The issue only affects the nodes created after the project is started. 

## How to reproduce

- Open the Unnamed project in the IDE [Unnamed.zip](https://github.com/enso-org/enso/files/11936431/Unnamed.zip)
   ```py
  from Standard.Base import all
  from Standard.Table import all
  import Standard.Visualization

  type Student
      Value id region

  main =
      operator1 = Student.Value 1 'EAST'
      operator2 = operator1.id
      operator2
   ```
- Create a new node `operator1.id`

### Expected result

Node evaluates to a value

### Actual result

Node evaluates to an error:
```
Method `id` of type Student could not be found
```

https://github.com/enso-org/enso/assets/357683/eb16f747-add9-452e-ad81-be3f709862f3

**Comment by radeusgd** [comment] 2023-07-04 09:35
This looks like duplicate of #5249, but good that you reported it because it apparently got unscheduled.

**Comment by hubertp** [comment] 2023-07-06 15:27
This was demoted for now, since users cannot define their own types (intuitively) in the project currently (other than the editor but that is not what we want).

**Comment by radeusgd** [comment] 2023-12-09 18:39
Hitting that issue again when doing Advent of Code - I tried defining my custom types and I cannot really define functions on them as that simply does not work:
![image](https://github.com/enso-org/enso/assets/1436948/9c1da8ac-a04f-4379-9f65-433211c985d7)

I also cannot rely on customizing `to_display_text` on such types, because it is not picked up either.

**Comment by jdunkerley** [comment] 2023-12-12 09:59
Possibly related to #8505

**Closed as completed** 2024-01-03 13:23 UTC
Labels: p-low, --bug, -compiler, -language-server
