### ISSUE TITLE
Right mouse button zooms in and out also on horizontal mouse movement

### ISSUE THREAD

**Issue by xvcgreg** [enso-org/enso#6387] opened 2023-04-24 11:03 UTC
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

Zooming with mouse is possible on left right mouse movement while having right mouse button pressed.

### Expected behaviour

Zoom in/out should only work on lateral mouse movement. Horizontal movement shouldn't zoom in and out nodes.

### Screenshots or screencasts

https://user-images.githubusercontent.com/108271897/233978215-45affe74-b968-41b5-b55b-0daf714886f4.mp4

### Enso Version

2023.04.20

### Browser or standalone distribution

Chrome

### Browser Version or standalone distribution

Version 112.0.5615.138 (Official Build) (64-bit)

### Operating System

Windows

### Operating System Version

Win11pro 22H2 22621.1555

### Hardware you are using

12th Gen Intel(R) Core(TM) i9-12900HK / RTX3060 Laptop / Nvidia Drivers 531.68

**Comment by wdanilo** [comment] 2023-04-24 11:51
This is done by design. There is not explanation why horizontal movement should not zoom in/out nodes, so closing it until we decide we don't want it.

**Closed as completed by wdanilo** 2023-04-24 11:51 UTC
Labels: --bug
