### ISSUE TITLE
Once entered an incorrect function when re-editing the node the CB doesn't offer any functions

### ISSUE THREAD

**Issue by jdunkerley** [enso-org/enso#6126] opened 2023-03-29 11:07 UTC
Having accepted via `Ctrl-Enter` an incorrect entry (like `use`) then when re-editing the CB shows nothing helpful.

https://user-images.githubusercontent.com/4699705/228514964-0550f060-2580-44d8-8dda-fce14dbf30cd.mp4

**Comment by vitvakatu** [comment] 2023-03-29 11:31
This was kind of expected when we implemented the cursor-aware CB. The reason is that we filter out all entries that do not match the already typed qualified name, and `operator2.` is considered to be a qualified name because of the current implementation. 

To mitigate the issue you can recreate a node.

Technically this exact issue should be fixed by #4967 
cc @farmaazon

**Comment by farmaazon** [comment] 2023-03-30 08:07
Note: it's not a regression introduced by cursor-aware CB, because such behavior was also before merging that one.

**Comment by farmaazon** [comment] 2023-03-31 07:42
Let's treat it as a duplicate of https://github.com/enso-org/enso/issues/5232 Updated its description to cover this bug

**Closed as not planned** 2023-03-31 07:44 UTC
Labels: s-duplicate, --bug
