### ISSUE TITLE
Loading dropdowns with many elements is too long.

### ISSUE THREAD

**Issue by radeusgd** [enso-org/enso#6865] opened 2023-05-26 10:49 UTC
https://github.com/enso-org/enso/assets/1436948/ed53ab2d-52eb-403b-9d31-515a3a0124e9

There are 3  issues in this video, but this task tracks only: 

3. Likely a separate issue but the video also shows that once the dropdown list has more elements it takes **ages** to load - the list from the video took **more than 10 seconds** to load. And during the whole time of it loading the IDE, the cursor were all frozen and no spinner was shown to tell the user that some operation is in progress - one may think that the application just crashed.

The other two are tracked in separate issues.

1. If I scroll with the mouse wheel, the dropdown _does scroll_ BUT along with it _the whole workspace_ also moves around. There is no focus management - both the whole viewport as well as the dropdown list are reacting to the scrolling events whereas only one should react at a time - probably when the mouse is over the dropdown list it should get 'focus' and scroll without scrolling the whole workspace. #6649 
2. If I click on the scrollbar displayed in the dropdown list and move it around using my mouse, it again does move, but that movement also causes 'dragging' of the related element for which the dropdown is shown in the vector editor - possibly reordering it (if multiple elements) or dragging out of the vector and deleting. Again - when dragging the scrollbar - the list should scroll without propagating the event further and moving the element. Overall, I think that clicking over the dropdown should not cause dragging of its parent element above it. #6823

**Comment by wdanilo** [comment] 2023-05-26 10:52
1. Good catch. 
2. Duplicate of https://github.com/enso-org/enso/issues/6823.
3. This is on our radar. CC @Frizi @kazcw – did anyone of you investigated it already?

**Comment by farmaazon** [comment] 2023-05-26 10:54
1. is also a duplicate: #6649 

So, I will take a chance and make it an issue about point 3 only.

**Comment by wdanilo** [comment] 2023-05-26 10:58
But I believe that 3 is also duplicate :P I just can't find it now, but @Frizi might know better, as if its there, it's assigned to him.

**Closed as completed** 2023-06-14 17:58 UTC
Labels: p-high, --low-performance
