### ISSUE TITLE
Create installation packages for Enso

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5239] opened 2023-02-05 22:54 UTC
This task is automatically imported from the old Task Issue Board and it was originally created by Dmitry Bushev.
Original issue is [here](https://www.pivotaltracker.com/story/show/184153161).
<hr />

## Notes
In order to handle custom `enso://` redirect links required for authentication, we need to install .desktop files in appropriate locations. 
Packaging is required for Windows and Linux platforms. The `dmg` file produced for macOS should already contain the required file structure, and we should be able to handle custom URLs

sbt-native-packager should be enough to create those bundles.

## Comments:
This is login redirection ticket - possibly a ticket for @murbanczyk. (James Dunkerley - Feb 3, 2023)
<hr />

**Comment by sylwiabr** [comment] 2023-02-28 08:27
@indiv0 @PabloBuchu this is relevant for you

**Comment by PabloBuchu** [comment] 2023-03-23 18:42
anyone knowing sbt can help with this one? I guess this one is blocking windows package from working @mwu-tow @4e6?

**Comment by mwu-tow** [comment] 2023-03-23 19:57
> anyone knowing sbt can help with this one? I guess this one is blocking windows package from working @mwu-tow @4e6?

I don't think sbt is relevant; this should be done identically as file extension associations.

**Comment by sylwiabr** [comment] 2023-03-24 14:17
@mwu-tow is there a way to quickly test if it solves the problem with authentication on Windows and guide @PabloBuchu and @indiv0 here? The problem is that when user tries to login with Google or GitHub account he is not redirected back to application.

**Comment by mwu-tow** [comment] 2023-03-24 15:45
> @mwu-tow is there a way to quickly test if it solves the problem with authentication on Windows and guide @PabloBuchu and @indiv0 here? The problem is that when user tries to login with Google or GitHub account he is not redirected back to application.

Is there a repro scenario that I can easily try?

**Comment by mwu-tow** [comment] 2023-04-04 23:48
This issue actually has two parts. The first part concerns the current setup's failure to properly register the custom protocol handler on Windows. However, resolving this does not seem particularly challenging. The second part, which is more interesting, is about handling custom protocol deep links.

Following discussions with @PabloBuchu, @wdanilo, and @sylwiabr, here are some key points:
* We support and want to continue supporting multiple instances of the IDE running simultaneously.
* We cannot rely on the system browser to send the `open-url` event to the correct instance of the IDE after opening our custom protocol deep link.
* On Windows, this event won't be sent at all. Instead, a new IDE instance will be spawned with the URL as a command-line argument.

Since we want to support multiple IDE instances, we cannot use the single-instance lock mechanism. It is the only cross-instance IPC mechanism available in Electron, so we need to handle IPC ourselves.

A possible solution is for the IDE that directs the user to the system browser to maintain an open WebSocket (or similar) listener on a specific port. This port number will be embedded in the custom protocol deep link. When the system browser opens the deep link, whichever IDE instance receives the deep link will establish a WebSocket connection to the port and forward the URL data. The IDE that opened the system browser will then receive the URL data and handle it, including bringing itself to the foreground.

@JaroslavTulach also asked why we chose to use custom protocol handling in the first place. An alternative might be for the IDE to redirect the browser to its HTTP server. This could potentially eliminate platform-specific differences in handling deep links. However, this approach would require the IDE to run in the background constantly (i.e., it won't be possible to just spawn it from the browser).

***

@indiv0
What do you think about this? How should I proceed? Additionally, can you provide some pointers on how to control the URL data flow from the IDE to the browser?

**Comment by indiv0** [comment] 2023-04-11 06:28
> We cannot rely on the system browser to send the open-url event to the correct instance of the IDE after opening our custom protocol deep link.

For the supporting of multiple instances of the IDE running simultaneously: the Electron docs don't seem to address how to handle deep links with multiple open instances. In fact, in the windows case, the docs [explicitly ensure there's only ever one instance running](https://www.electronjs.org/docs/latest/tutorial/launch-app-from-url-in-another-app#windows-code). I'm not sure about the behaviour, but if Electron fires the `open-url` (or equivalent event) in all the open instances, then we could potentially attach a unique instance identifier to the redirect URL. Then, we can configure it so that only the original requesting window handles the URL, and the rest ignore it. But I'm not sure if this is how Electron fires the `open-url` event outside of Windows. If Electron does not fire the event in all open instances, then I'm not quite sure how to handle this.

> On Windows, this event won't be sent at all. Instead, a new IDE instance will be spawned with the URL as a command-line argument.

This is not ideal, but perhaps we could close the originating window and have the user continue the flow in the new window, on Windows? The dashboard UI (at least) requires a full refresh after login, so perhaps this is OK on the IDE side too?

> A possible solution is for the IDE that directs the user to the system browser to maintain an open WebSocket (or similar) listener on a specific port. This port number will be embedded in the custom protocol deep link. When the system browser opens the deep link, whichever IDE instance receives the deep link will establish a WebSocket connection to the port and forward the URL data. The IDE that opened the system browser will then receive the URL data and handle it, including bringing itself to the foreground.

I can't say with certainty, but I think this approach would work and resolve the issues in a cross-platform way. It's a more complex flow but should work with multiple IDE instances.

> @JaroslavTulach also asked why we chose to use custom protocol handling in the first place. An alternative might be for the IDE to redirect the browser to its HTTP server. This could potentially eliminate platform-specific differences in handling deep links.

The original requirement to do so comes from a potential security UX concern. Users may be uncomfortable entering their credentials into an Electron application (since we could potentially log their credentials this way), but they are comfortable entering their credentials into their system browser. @wdanilo can weigh in here.

> However, this approach would require the IDE to run in the background constantly (i.e., it won't be possible to just spawn it from the browser).

Yes, that is another practical concern for the in-app authentication approach. It would be easy to solve this on macOS and Linux by using a combination of the two approaches. We could open an instance in the event that no existing instance is open to handle the event. On Windows the instance is opened regardless so we don't have that level of control.

> What do you think about this? How should I proceed? Additionally, can you provide some pointers on how to control the URL data flow from the IDE to the browser?

The WebSocket+port-based approach sounds like the ideal option. An overview of how we currently handle the URL data flow from the IDE to the browser can be [found here](https://github.com/enso-org/enso/blob/fa23e800e5d5a745042ea1ac4e086c431fcd3e37/app/ide-desktop/lib/client/src/authentication.ts#L1-L73).

1. You can pass in any extra information that you need for the flow to the redirect URL, via these functions: [Google](https://github.com/enso-org/enso/blob/0fc8683108bc1e7113d79cc6fa926673025218f4/app/ide-desktop/lib/dashboard/src/authentication/src/authentication/cognito.ts#L420-L424), [GitHub](https://github.com/enso-org/enso/blob/0fc8683108bc1e7113d79cc6fa926673025218f4/app/ide-desktop/lib/dashboard/src/authentication/src/authentication/cognito.ts#L431-L435), and [email+password](https://github.com/enso-org/enso/blob/0fc8683108bc1e7113d79cc6fa926673025218f4/app/ide-desktop/lib/dashboard/src/authentication/src/authentication/cognito.ts#L443). These functions allow you to pass in `customState` when calling the Amplify API, and this custom state can include the port that you wish to redirect the user to.
2. When the IDE receives the deep link, it is handled by the dashboard in [this function](https://github.com/enso-org/enso/blob/0fc8683108bc1e7113d79cc6fa926673025218f4/app/ide-desktop/lib/dashboard/src/authentication/src/authentication/service.tsx#L183-L229). It is in this function that you can extract the `customState` and either forward it to the [`handleAuthResponse` function](https://github.com/enso-org/enso/blob/0fc8683108bc1e7113d79cc6fa926673025218f4/app/ide-desktop/lib/dashboard/src/authentication/src/authentication/service.tsx#L183-L229) to complete the OAuth flow (as the code currently does), or send the information out via WebSocket.
3. You *may* (I'm not sure) need to pass the information back to the IDE to do so, as the sandboxed process may not have the necessary access to make requests to arbitrary `localhost:$PORT` URLs. If you need to pass the information back out of the sandboxed process, you can do so by registering a "proxied function" that the sandboxed process can use to talk to the main process. An example of how to register such a "proxied function" for use in the dashboard can be found [here](https://github.com/enso-org/enso/blob/0fc8683108bc1e7113d79cc6fa926673025218f4/app/ide-desktop/lib/client/src/preload.ts#L69-L102). An example of how to use such a "proxied function" can be found [here](https://github.com/enso-org/enso/blob/e7668ebc3ae39a489149bf0d0a51e45b7ef7b427/app/ide-desktop/lib/dashboard/src/authentication/src/authentication/service.tsx#L160-L162).

**Comment by somebody1234** [comment] 2023-04-11 06:44
another option might be to only ever have a single instance running, and let that single instance control all the windows?
i'm not 100% sure instance ≠ window, but [this SO answer](https://stackoverflow.com/questions/70615348/how-to-open-multiple-instances-of-an-electron-app) seems to indicate that it is

that said, i'm not sure what would be the downsides of doing things this way

**Comment by sylwiabr** [comment] 2023-04-20 08:38
@mwu-tow what is the status here? I don't see any progress update/standups.

**Closed as completed** 2023-04-24 14:12 UTC
Labels: p-high, -ci, x-new-feature
