### ISSUE TITLE
IDE replaces the node contents with the removed node

### ISSUE THREAD

**Issue by 4e6** [enso-org/enso#6581] opened 2023-05-05 13:17 UTC
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

When you delete a node, ctrl-click another node to edit, then exit without editing. The contents of the node is replaced with the deleted node.

### Expected behaviour

The node contents remain the same.

### Screenshots or screencasts

https://user-images.githubusercontent.com/357683/236467410-80247756-be1b-42c1-8d1d-872338fa7ad7.mp4

### Enso Version

a842130ff3162595f093e554a7d943c967146e63

### Browser or standalone distribution

Chromium

### Browser Version or standalone distribution

113.0.5672.63

### Operating System

Linux

**Comment by vitvakatu** [comment] 2023-05-07 22:02
Duplicate of #6411 

Removing node is not necessary here, the issue is fixed in #6594

**Closed as not planned by vitvakatu** 2023-05-07 22:02 UTC
Labels: s-duplicate, p-highest, --bug
