### ISSUE TITLE
Visualisation type selector left rendered after node preview visualisation was closed.

### ISSUE THREAD

**Issue by xvcgreg** [enso-org/enso#6501] opened 2023-05-02 10:19 UTC
### What type of issue is this?

Intermittent – Occurring irregularly

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

"Top bar" of a preview window where we can select the visualisation type, left rendered as top layer (at least it was obstructing nodes beneath it). Had to open the visualisation and close it for it to disappear.

https://user-images.githubusercontent.com/108271897/235640387-eb8e05ec-5da7-4a39-93cd-794a56c4947c.mp4

### Expected behaviour

After closing viz there should be no remaining components of that viz in the GUI

### How we can reproduce it?

It was random occurrence.

### Screenshots or screencasts

![image](https://user-images.githubusercontent.com/108271897/235641334-d6a2b4af-e052-4225-b69e-27293696272c.png)

[localhost-1683022687696.log](https://github.com/enso-org/enso/files/11372128/localhost-1683022687696.log)

### Enso Version

2023.5.2 nightly

### Browser or standalone distribution

Standalone distribution

### Browser Version or standalone distribution

standalone

### Operating System

Windows

### Operating System Version

Win11pro 22H2 22621.1555

### Hardware you are using

12th Gen Intel(R) Core(TM) i9-12900HK / RTX3060 Laptop / Nvidia Drivers 531.68

**Comment by farmaazon** [comment] 2023-05-02 10:46
Duplicate of [#6490](https://github.com/enso-org/enso/issues/6490), but I will merge that task to this, as this has more accurate information

**Closed as completed** 2023-05-09 07:56 UTC
Labels: p-high, --bug
