### ISSUE TITLE
Editing outside of the node appears to reshuffle all nodes and break the layout

### ISSUE THREAD

**Issue by hubertp** [enso-org/enso#9389] opened 2024-03-12 19:50 UTC
While waiting on the execution to finish, I start editing some node. Clicking outside of the node appears to collapse all nodes and order them in a single line. Video demonstrates the problem.

[Kazam_screencast_00039.webm](https://github.com/enso-org/enso/assets/292128/c5c3404b-16df-4d67-9ab0-0cb208811a2d)

There are two problems here
- [ ] GUI should not reshuffle nodes like that (restarting the projects brings the original layout)
- [x] there are some underlying crashes on the engine side

**Comment by hubertp** [comment] 2024-03-12 20:29
It appears that we end up with `()` being inserted for the value e.g.
```
    number6 =
        ()
```
by GUI? Language server?

**Comment by hubertp** [comment] 2024-03-12 21:19
Steps to reproduce:
- select the node 
- enter a space
- click outside of the node
- all nodes are reshuffled

**Comment by farmaazon** [comment] 2024-03-18 09:54
Reproduced; As currently numeric input accepts anything, we parse space and put it as "Block" node without lines, and probably then our "AST repairing system" inserts the parenthesis.

I think we should be careful in what is accepted in numeric input - the AST block should not be.

In this issue, undo is also broken sometimes.

**Comment by kazcw** [comment] 2024-03-18 13:34
This should also be handled differently in `Ast.syncToCode`--it could reject attempts to sync a non-block into a block, because that isn't safe in general.

**Comment by Frizi** [comment] 2024-04-04 15:00
We need to know what is the expected behavior here. Should the node be deleted, or should such edit be rejected?

**Comment by farmaazon** [comment] 2024-07-22 07:58
Technically, it is fixed by #10457 - now there is no way to put just any code into widgets.

But the problem here may re-appear when implementing [Code Input Widget](https://github.com/enso-org/enso/issues/8753) - added a section there about repairing AST to not break graph.

**Closed as completed by farmaazon** 2024-07-22 07:58 UTC
Labels: d-hard, p-medium, --bug, -gui
