### ISSUE TITLE
#1898 Broke Nightly Builds

### ISSUE THREAD

**Issue by iamrecursion** [enso-org/enso#1899] opened 2021-07-26 09:38 UTC
### Summary

#1898 broke nightly builds and has been reverted. This should be fixed ASAP. 

### Value
Working nightlies.

### Specification

- [ ] Fix it.

### Acceptance Criteria & Test Cases

- [ ] Nightlies work again.

**Comment by radeusgd** [comment] 2021-08-11 10:01
This was fixed in #1936 and it actually was not caused by #1898 at all.

**Closed as completed by radeusgd** 2021-08-11 10:01 UTC
Labels: p-high
