### ISSUE TITLE
Unclickable drop-down under `rows` node

### ISSUE THREAD

**Issue by sylwiabr** [enso-org/enso#6490] opened 2023-05-01 13:03 UTC
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

<img width="296" alt="image" src="https://user-images.githubusercontent.com/12892578/235455137-0ebb9f2a-686f-43b4-a82c-d9f19eeefc1e.png">

### Expected behaviour

The drop-down indicator should not be there

### Enso Version

develop @ 6b0c682b08b7745368cec3474cc774c51a5b48f5

### Browser or standalone distribution

Standalone distribution

### Browser Version or standalone distribution

Standalone

### Operating System

MacOS

**Comment by hubertp** [comment] 2023-05-02 08:23
@Frizi that sounds like a regression?

**Comment by farmaazon** [comment] 2023-05-02 09:34
It seems like regression.

Because this is not a drop-down _widget_: this is actually a visualization top bar, with drop down for choosing visualization.

I spotted the issue today (but not reproduced again). Showing and hiding visualization makes it disappear.

**Comment by farmaazon** [comment] 2023-05-02 10:47
Closing in favor of #6501

**Closed as not planned** 2023-05-02 10:48 UTC
Labels: s-duplicate, --bug, --regression
