### ISSUE TITLE
I lost my project

### ISSUE THREAD

**Issue by farmaazon** [enso-org/enso#7196] opened 2023-07-04 09:06 UTC
Today's I struggled a bit with my Enso package, as I got many "context lost". This includes multiple app restarts, with various sets of flags and refreshing the page with `ctrl+shift+R` shortcut.

At some point I realized **I lost one of my project** called "Daily_Bookclub_06_07". It wasn't on my project list anymore. I checked the `enso/project` directory, and where was a directory "Daily_Bookclub_06_07", but the `package.yaml` declared a "New_Project_10" instead and `src/Main.enso` was same as in newly created project. I tried to restore using VCS, but VCS also didn't have my old project in its history.

I don't know how to reproduce that, but losing a project entirely is very serious, so I put today's logs in hope someone from the engine will find the cause. Unfortunately, not all runs were with "verbose" flag, because - as I mentioned - I tried different flag configurations.

[logs.zip](https://github.com/enso-org/enso/files/11947339/logs.zip)

**Comment by hubertp** [comment] 2023-07-05 09:41
I spent a bit of time on those logs. Other than an unrelated problem refactored into a separate ticket I haven't noticed anything that  would cause the behaviour described. Since the config file seemed out-of-sync with the directory, I suppose that at some point a rename was attempted but nothing in the logs confirms that. 

I agree that from the sounds of it, the ticket sounds worrying, but I'm also not really able to reproduce or extract anything useful from the number of logs provided. So to me this sounds like a won't fix.

**Comment by vitvakatu** [comment] 2023-07-05 11:24
I think we can't do much here, in case this appears again – let's reopen this issue.

**Closed as not planned by vitvakatu** 2023-07-05 11:24 UTC
Labels: s-no-repro, --bug, --data corruption or loss
