### ISSUE TITLE
Blank fullscreen visualization when opened with `Shift+Space` without enabling small visualization first

### ISSUE THREAD

**Issue by kazcw** [enso-org/enso#6927] opened 2023-06-02 00:39 UTC
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

Highlighting a node that doesn't have a visualization enabled and pressing `Ctrl+Space` opens a full-screen visualization showing no data.

### Expected behaviour

When the fullscreen visualization is entered, it should show data.

### How we can reproduce it?

- Highlighting a node that doesn't already have a visualization enabled
- Press `Ctrl+Space`
- A full-screen visualization opens, showing no data

### Screenshots or screencasts

[vokoscreenNG-2023-06-01_17-30-25.webm](https://github.com/enso-org/enso/assets/1047859/15ff452e-5fd9-4d04-96ce-9e733570178a)

### Enso Version

develop (343b5fb)

### Browser or standalone distribution

Standalone distribution (cloud project)

### Browser Version or standalone distribution

standalone

### Operating System

Linux

**Comment by farmaazon** [comment] 2023-06-02 07:33
I believe it's a duplicate of https://github.com/enso-org/enso/issues/6561 @MichaelMauderer please confirm.

**Comment by MichaelMauderer** [comment] 2023-06-02 10:18
More accurately, a duplicate of #6770 (which is handled in https://github.com/enso-org/enso/issues/6561 ), but a duplicate.

**Closed as not planned** 2023-06-02 10:18 UTC
Labels: s-duplicate, --bug

**Comment by farmaazon** [comment] 2023-06-02 11:51
@MichaelMauderer remember to add appropriate label when closing.
