### ISSUE TITLE
CB adding extra space at the end of the string when editing a node

### ISSUE THREAD

**Issue by sylwiabr** [enso-org/enso#7349] opened 2023-07-20 09:49 UTC
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

https://github.com/enso-org/enso/assets/12892578/cbe9e5d3-a2d2-4488-8ddc-4ac77397050d

### Expected behaviour

Extra space should not be added and the expression should stay as it was when the node was edited.

### Enso Version

nightly 20.07

### Browser or standalone distribution

Standalone distribution (local project)

### Browser Version or standalone distribution

standalone

### Operating System

MacOS

**Comment by farmaazon** [comment] 2023-07-20 12:43
Duplicate of #5848 Feel free to bump priority @sylwiabr

**Closed as not planned** 2023-07-20 12:43 UTC
Labels: --bug
