### ISSUE TITLE
Improvements for fonts on Windows

### ISSUE THREAD

**Issue by sylwiabr** [enso-org/enso#6676] opened 2023-05-12 18:13 UTC
### How important is this feature to you?

2 – Somewhat important, but I can live without it

### Describe the idea you'd like to see implemented.

![image](https://github.com/enso-org/enso/assets/12892578/dc994e2e-1e89-4b2c-a4d9-8df9f6712e99)

Right now fonts on Windows are really ugly. Since Windows is main platform used by our end-users we should improve it.

### Would you be willing to help us implement this feature?

No

**Comment by Akirathan** [comment] 2023-05-15 08:43
Isn't this related to the *automatic low/high-resolution modes* as mentioned by @wdanilo in #6596? I think that the font also gets blurred on my machine once the FPS gets lower.

**Comment by Frizi** [comment] 2023-05-15 08:50
We are rendering fonts ourselves the same way on all operating systems. There shouldn't be any windows-specific behavior. Instead, this looks to be a consequence of low resolution/pixel density.

A possible solution would be to apply appropriate filtering or other rendering tricks to the font shapes to make it behave nicer on lower pixel densities.

**Comment by farmaazon** [comment] 2023-05-15 14:35
It maybe actually duplicate of #6552 because the text rendering was changed and tested to display mplus1 font in a pretty way. And currently, nodes still use DejaVu.

**Comment by wdanilo** [comment] 2023-05-16 10:17
@farmaazon I don't think it is duplicate of https://github.com/enso-org/enso/issues/6552, but it definitely should be resolved after that ticket is done. Font rendering was never adjusted on Windows. I remember when I was implementing it, I adjusted all parameters on MacOS, but I did not had Windows machine, so the parameters were adjusted more or less OK there.

**Comment by kazcw** [comment] 2023-05-16 14:47
> Isn't this related to the _automatic low/high-resolution modes_ as mentioned by @wdanilo in #6596? I think that the font also gets blurred on my machine once the FPS gets lower.

@Akirathan That hasn't been merged yet, so if you're observing the blurriness of fonts *changing*, that might be an independent bug.

**Comment by kazcw** [comment] 2023-05-16 14:55
> We are rendering fonts ourselves the same way on all operating systems. There shouldn't be any windows-specific behavior. Instead, this looks to be a consequence of low resolution/pixel density.
> 
> A possible solution would be to apply appropriate filtering or other rendering tricks to the font shapes to make it behave nicer on lower pixel densities.

@Frizi brings up an interesting point. We currently have logic [setting different hinting parameters depending on OS](https://github.com/enso-org/enso/blob/f38033b037800bddef55257a3374aa9f571678aa/lib/rust/ensogl/component/text/src/font.rs#L1010-L1025), but I don't see any reason the optimal values would be operating-system specific *per se*. Are we using OS as a proxy for pixel density here? It might be more accurate to calculate it from `device_pixel_ratio`.

**Comment by wdanilo** [comment] 2023-05-17 05:20
> > We are rendering fonts ourselves the same way on all operating systems. There shouldn't be any windows-specific behavior. Instead, this looks to be a consequence of low resolution/pixel density.
> > A possible solution would be to apply appropriate filtering or other rendering tricks to the font shapes to make it behave nicer on lower pixel densities.
> 
> @Frizi brings up an interesting point. We currently have logic [setting different hinting parameters depending on OS](https://github.com/enso-org/enso/blob/f38033b037800bddef55257a3374aa9f571678aa/lib/rust/ensogl/component/text/src/font.rs#L1010-L1025), but I don't see any reason the optimal values would be operating-system specific _per se_. Are we using OS as a proxy for pixel density here? It might be more accurate to calculate it from `device_pixel_ratio`.

You are 100% right. This is implemented wrongly and needs to be fixed based on `device_pixel_ratio`.

**Comment by farmaazon** [comment] 2024-02-26 10:01
No relevant in GUI2 where we rely on browser for displaying fonts.

**Closed as not planned by farmaazon** 2024-02-26 10:01 UTC
Labels: p-lowest
