### ISSUE TITLE
After removing widget from a node by dragging, cursor gets stuck on red circle with X state

### ISSUE THREAD

**Issue by xvcgreg** [enso-org/enso#6547] opened 2023-05-04 08:13 UTC
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

When I remove the widget from a node by dragging widget out of the node, cursor gets stuck on it's red circle with X state. It was discovered by accident when trying to drag node to a different position. This UX is not intuitive, as I wanted to move the node, now I need to find a spot on a node to be able to grab it and move it.

### Expected behaviour

Cursor changing back to its normal state after widget is released.

### How we can reproduce it?

as described above

### Screenshots or screencasts

https://user-images.githubusercontent.com/108271897/236147351-be225ecb-37de-4f8a-8dc3-c202fb710b6c.mp4

### Enso Version

2023.5.3 nightly

### Browser or standalone distribution

Standalone distribution

### Browser Version or standalone distribution

standalone

### Operating System

Windows

### Operating System Version

Win11pro 22H2 22621.1555

### Hardware you are using

12th Gen Intel(R) Core(TM) i9-12900HK / RTX3060 Laptop / Nvidia Drivers 531.68

**Comment by wdanilo** [comment] 2023-05-09 09:48
Duplicate of many issues regarding proper cursor management. @Frizi knows about it.

**Closed as completed by wdanilo** 2023-05-09 09:48 UTC
Labels: s-duplicate, --bug
