### ISSUE TITLE
Data.read (enso_project.data/"test.csv") renders incorrectly

### ISSUE THREAD

**Issue by AdRiley** [enso-org/enso#9971] opened 2024-05-16 14:01 UTC
![image](https://github.com/enso-org/enso/assets/1720119/5aa781b8-d95d-4e82-bb61-b3bfb0777bcc)

**Comment by farmaazon** [comment] 2024-05-16 14:17
Duplicate of #9688

**Closed as not planned** 2024-05-16 14:17 UTC
Labels: s-duplicate, p-high, --bug, -gui
