### ISSUE TITLE
Re-entering function after project close

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5140] opened 2023-02-05 22:49 UTC
This task is automatically imported from the old Task Issue Board and it was originally created by Greg Ociepka.
Original issue is [here](https://www.pivotaltracker.com/story/show/184303643).
<hr />

We can re-enter function only after ctrl+clicking it. Double click doesn't work prior of edit.

repro steps:
1. create several nodes
2. grup them into a function
3. close Enso
4. re open the project
5. double click to enter the function previously created doesn't work

to re-enable entering into the previously created function - ctrl-click it (w/o making changes) then entering the function is enabling back with DoubleClick

see attached video

## Comments:
 (Greg Ociepka - Jan 24, 2023)
<hr />
https://discordapp.com/channels/401396655599124480/1050064283096068158/1050064283096068158
 (James Dunkerley - Feb 1, 2023)
<hr />
This seems to be working for me on Linux, so I reckon this is an issue with GUI input processing on Windows. So, investigation should start on the GUI side.  (Michael Mauderer - Feb 1, 2023)
<hr />
	This seems much more stable on mine now as well.
@gregociepka - suggest we close for now. (James Dunkerley - Feb 2, 2023)
<hr />
	@jdunkerley for me it's still very random (most of the time it doesnt work)

I have noticed that if I move the camera before the nodes are fully loaded and when I create a group after they load, I cannot enter the group (in a fresh project).

Attaching 4 clips with issues with entering a function and log from all of those attempts. (Greg Ociepka - Feb 2, 2023)
<hr />

**Comment by JaroslavTulach** [comment] 2023-02-23 12:27
Thanks for CCing me. Now I am subscribed to the issue. I don't however think _ctrl-click_ has anything to do with my area of expertise. Unassigning myself for now.

**Comment by xvcgreg** [comment] 2023-03-14 15:43
@jdunkerley I believe it got better now, closing it (please reopen if it's still happening to you).

**Comment by wdanilo** [comment] 2023-03-15 01:00
I'm reopening, as the closing message is not clear enough. What do you mean @xvcgreg that it is "better now"? Is it working, or is it only better? If the latter, what do you mean exactly and what are you observing?

**Comment by xvcgreg** [comment] 2023-03-20 12:54
> I'm reopening, as the closing message is not clear enough. What do you mean @xvcgreg that it is "better now"? Is it working, or is it only better? If the latter, what do you mean exactly and what are you observing?

It's more question to @jdunkerley if he can still observe it as on his end it was happening the most often - I haven't heard about that issue in a long time nor I have observed it - so I have assumed it was fixed - ergo UX got improved and regression was averted. I have also tested it on my end on Windows and couldn't reproduce it on recent builds.

@wdanilo if that suffice to close it please do - if not, what are the next steps?

**Comment by wdanilo** [comment] 2023-03-21 02:41
@xvcgreg let's wait then for @jdunkerley if this is question to him :) But from your message I understand that it doesn't happen on your end anymore, right? If so, the message "it got better now" got me really confused, as "better" was not defined.

**Comment by jdunkerley** [comment] 2023-03-21 08:35
I haven't seen it in a while - the IDE stability is much higher than it was, so I'm guessing has been resolved.

**Closed as completed by jdunkerley** 2023-03-21 08:35 UTC
Labels: p-low, --bug, --regression
