### ISSUE TITLE
Auto node placing calculates visualization size incorrectly

### ISSUE THREAD

**Issue by vitvakatu** [enso-org/enso#7553] opened 2023-08-10 13:38 UTC
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

When creating nodes with automatic node placement (opening CB with the node being selected), the new node is placed on top of the visualization of the previous node.

https://github.com/enso-org/enso/assets/6566674/0e437f35-94ab-4f2a-80f3-f674a24b0363

### Expected behaviour

The node is placed below the visualization.

### Enso Version

af0e738dec643b1129facd95c745409a204d828e

### Browser or standalone distribution

Standalone distribution (local project), Standalone distribution (cloud project)

### Browser Version or standalone distribution

standalone

### Operating System

MacOS

**Comment by farmaazon** [comment] 2023-08-10 14:30
Duplicate of #7309

**Closed as not planned** 2023-08-10 14:30 UTC
Labels: s-duplicate, --bug
