### ISSUE TITLE
Unexpected result of failed folder name change - CB opened and node created in running project

### ISSUE THREAD

**Issue by xvcgreg** [enso-org/enso#7664] opened 2023-08-25 19:32 UTC
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

I was working on test cloud project. I have left it open and switched back to the dashboard. Created a folder there. Upon rename I have hit ``enter`` confirm the rename - got error: 
![image](https://github.com/enso-org/enso/assets/108271897/a7e648cd-7302-4eb8-9af8-6a239dd5ab27)
I retried and this time used the button to confirm name change (got same errror, folder hasn't had it's name changed).
The name I was trying to use was "Enso Test".
I have tested couple of other things (dragging and dropping, sorting, etc).
When I have got back to the still opened project I was welcomed with CB opened: 
![image](https://github.com/enso-org/enso/assets/108271897/aaad9bcb-ff14-47f1-bc00-36ca3e7f41dc)

 

https://github.com/enso-org/enso/assets/108271897/9bc5ea7d-b1d2-4ff8-87a6-98dec31f2d33

### Expected behaviour

Project that is left open is not accessed by the actions from dashboard.

### How we can reproduce it?

Pressing ``enter`` in dashboard opens CB in the running project
Typing again the new name for the folder is captured by the opened CB 

### Enso Version

2023.8.25 nightly

### Browser or standalone distribution

Standalone distribution (cloud project)

### Browser Version or standalone distribution

standalone

### Operating System

Windows

### Operating System Version

Win11pro 22H2 22621.2134

### Hardware you are using

12th Gen Intel(R) Core(TM) i9-12900HK / RTX3060 Laptop / Nvidia Drivers 537.13

**Comment by farmaazon** [comment] 2023-08-31 08:47
Reproduced. Seems like the keyboard events are handled by both dashboard and opened project (despite the latter is not visible).

I will check, but I think this is a regression, as I tested this scenario some time ago.

**Comment by farmaazon** [comment] 2024-02-26 09:01
I cannot make folder-rename error anymore - all names are accepted :) But my guess is that the problem was with focus, and it did not depend on error or not - and that is fixed in GUI2

**Closed as not planned by farmaazon** 2024-02-26 09:01 UTC
Labels: p-lowest, --bug
