### ISSUE TITLE
Inconsistent import and FQN

### ISSUE THREAD

**Issue by JaroslavTulach** [enso-org/enso#9329] opened 2024-03-08 08:06 UTC
As of Mar 8, 2024 there seems to be an inconsistency between `import` and using _fully qualified name_ in certain cases.

### When Main Does not Reexport Submodule

When [Main](https://github.com/enso-org/enso/blob/6c2b2383d34e29c5ce58634762172765ee1b30a7/distribution/lib/Standard/Table/0.0.0-dev/src/Main.enso) in root of library doesn't re-export a submodule, then the module is not going to be accessible via FQN. Example where import works:
```ruby
import Standard.Table.Data.Table
main = Table
```
but where FQN access doesn't work:
```ruby
import Standard.Table
main = Standard.Table.Data.Table
```
and it yields
```bash
Execution finished with an error: Method `Data` of type Main could not be found.
        at <enso> i.main<arg-0>(i.enso:2:8-26)
        at <enso> i.main(i.enso:2:8-32)
```
The same type of problem is also reported as #6553 - the FQN in question is `Standard.Database.Connection.Postgres_Details.Postgres_Details.Postgres` in that case.

### Any Other Case?

Not known yet...
 
### Requested Behavior

If `x.y.z.A` can be imported by such name, one shall be able to use the same name as FQN.

**Comment by JaroslavTulach** [comment] 2024-03-08 08:10
I managed to get the `Standard.Table.Data.Table` case working with following change:
```diff
diff --git engine/runtime/src/main/java/org/enso/interpreter/node/callable/InvokeMethodNode.java engine/runtime/src/main/java/org/enso/interpreter/node/callable/InvokeMethodNode.java
index 0998e55277..fe1cc688d6 100644
--- engine/runtime/src/main/java/org/enso/interpreter/node/callable/InvokeMethodNode.java
+++ engine/runtime/src/main/java/org/enso/interpreter/node/callable/InvokeMethodNode.java
@@ -210,6 +210,25 @@ public abstract class InvokeMethodNode extends BaseNode {
     Type selfTpe = typesLibrary.getType(self);
     Function function = resolveFunction(symbol, selfTpe, methodResolverNode);
     if (function == null) {
+      if (self instanceof Type t && t.getDefinitionScope().getAssociatedType() == t) {
+        CompilerDirectives.transferToInterpreter();
+        // if we represent a Module
+        var scope = t.getDefinitionScope();
+        var module = scope.getModule();
+        var ctx = EnsoContext.get(this);
+        var moduleName =
+            module.getName().item().equals("Main")
+                ? module.getPackage().libraryName().toString()
+                : module.getName().toString();
+        var subModuleName = moduleName + "." + symbol.getName();
+        var optionModule = ctx.getTopScope().getModule(subModuleName);
+        if (optionModule.isPresent()) {
+          var subType = optionModule.get().getScope().getAssociatedType();
+          if (subType != null) {
+            return subType;
+          }
+        }
+      }
       throw methodNotFound(symbol, self);
     }
     var resolvedFuncArgCount = function.getSchema().getArgumentsCount();
```
I am not really satisfied with the above code - it seems too brutally direct. When investigating what _import/export_ resolution does I found this stack:
```
ImportResolver.tryResolveImport() (runtime-compiler/src/main/scala/org/enso/compiler/phase/ImportResolver.scala:198)
ImportResolver.$anonfun$mapImports$3() (runtime-compiler/src/main/scala/org/enso/compiler/phase/ImportResolver.scala:85)
ImportResolver$$Lambda/0x00007f7c5c55a728.apply() (Unknown Source:0)
List.map() (List.scala:246)
ImportResolver.analyzeModule$1() (runtime-compiler/src/main/scala/org/enso/compiler/phase/ImportResolver.scala:83)
ImportResolver.go$1() (runtime-compiler/src/main/scala/org/enso/compiler/phase/ImportResolver.scala:150)
ImportResolver.mapImports() (runtime-compiler/src/main/scala/org/enso/compiler/phase/ImportResolver.scala:162)
Compiler.liftedTree1$1() (runtime-compiler/src/main/scala/org/enso/compiler/Compiler.scala:456)
Compiler.runImportsAndExportsResolution() (runtime-compiler/src/main/scala/org/enso/compiler/Compiler.scala:455)
Compiler.$anonfun$runCompilerPipeline$2() (runtime-compiler/src/main/scala/org/enso/compiler/Compiler.scala:273)
Compiler$$Lambda/0x00007f7c5c559120.apply() (Unknown Source:0)
List.flatMap() (List.scala:293)
Compiler.runCompilerPipeline() (runtime-compiler/src/main/scala/org/enso/compiler/Compiler.scala:268)
Compiler.go$1() (runtime-compiler/src/main/scala/org/enso/compiler/Compiler.scala:233)
Compiler.runInternal() (runtime-compiler/src/main/scala/org/enso/compiler/Compiler.scala:240)
Compiler.run() (runtime-compiler/src/main/scala/org/enso/compiler/Compiler.scala:131)
Module.compile() (runtime/src/main/java/org/enso/interpreter/runtime/Module.java:392)
```

### What the [ImportResolver.tryResolveImport](https://github.com/enso-org/enso/blob/6c2b2383d34e29c5ce58634762172765ee1b30a7/engine/runtime-compiler/src/main/scala/org/enso/compiler/phase/ImportResolver.scala#L198) does?

- it finds the _library name_ [here](https://github.com/enso-org/enso/blob/6c2b2383d34e29c5ce58634762172765ee1b30a7/engine/runtime-compiler/src/main/scala/org/enso/compiler/phase/ImportResolver.scala#L261)
- then it [ensures the library is loaded](https://github.com/enso-org/enso/blob/6c2b2383d34e29c5ce58634762172765ee1b30a7/engine/runtime-compiler/src/main/scala/org/enso/compiler/phase/ImportResolver.scala#L269)
- asks the compiler to gives us the [right module for FQN](https://github.com/enso-org/enso/blob/6c2b2383d34e29c5ce58634762172765ee1b30a7/engine/runtime-compiler/src/main/scala/org/enso/compiler/phase/ImportResolver.scala#L271)
   - that ends calling [TopScope.getModule("Standard.Table.Data")](https://github.com/enso-org/enso/blob/6c2b2383d34e29c5ce58634762172765ee1b30a7/engine/runtime/src/main/java/org/enso/interpreter/runtime/TruffleCompilerContext.java#L240)
- that creates [ResolvedImport with ResolvedModule](https://github.com/enso-org/enso/blob/6c2b2383d34e29c5ce58634762172765ee1b30a7/engine/runtime-compiler/src/main/scala/org/enso/compiler/phase/ImportResolver.scala#L279)  

I'd say  the functionality of the above diff is similar. It also uses `TopScope.getModule` - just the way it computes the name to search for (with `Main` check) seems wild...

**Comment by Akirathan** [comment] 2024-03-08 09:35
Might be a duplicate of https://github.com/enso-org/enso/issues/6553

**Comment by Akirathan** [comment] 2024-03-08 10:48
I believe the *proper fix* is in the compilation phase rather than fixing the runtime behavior, namely in [org.enso.compiler.pass.resolve.FullyQualifiedNames.scala](https://github.com/enso-org/enso/blob/7a9a5ba1ffaf2ef6ff64b806882982b9e589a9e2/engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/resolve/FullyQualifiedNames.scala) introduced by https://github.com/enso-org/enso/pull/4056. It appears that this compiler pass is inconsistent with the Import/export resolver.

**Comment by hubertp** [comment] 2024-03-20 16:32
Same situation I see with 
```
Standard.Visualization.Table.Visualization.prepare_visualization
```
when GUI sends `executeExpression`

**Closed as completed** 2024-03-29 15:34 UTC
Labels: -compiler
