### ISSUE TITLE
Unable to focus on the node by clicking on vector element

### ISSUE THREAD

**Issue by hubertp** [enso-org/enso#7013] opened 2023-06-12 09:43 UTC
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

If the node has a vector with elements, then it is not possible to move the current focus by clicking on the vector. The only way to workaround it is to click on anything outside of the vector, it seems.

### Expected behaviour

Clicking on the vector inside the node should focus on the whole node.

### How we can reproduce it?

See screenshot.

### Screenshots or screencasts

![Screenshot from 2023-06-12 11-36-31](https://github.com/enso-org/enso/assets/292128/3b02d2c7-fe15-405f-aa16-4d02b29b877a)

Node at the bottom is currently selected. Attempting to click where the mouse points does nothing. Has to click outside of the vector:
![Screenshot from 2023-06-12 11-42-21](https://github.com/enso-org/enso/assets/292128/53738604-e70c-4810-8fab-81be95c43286)

### Enso Version

develop

### Browser or standalone distribution

Chrome

### Browser Version or standalone distribution

110.0.5481.100

### Operating System

Linux

**Comment by farmaazon** [comment] 2023-06-12 10:25
Duplicate of [#6677](https://github.com/enso-org/enso/issues/6677)

**Closed as not planned** 2023-06-12 13:23 UTC
Labels: s-duplicate, p-low, --bug
