### ISSUE TITLE
Dataflow Warnings

### ISSUE THREAD

**Issue by kustosz** [enso-org/enso#1573] opened 2021-03-12 11:32 UTC
### Summary
Similar to our current system for dataflow errors, we need a warnings system that acts by decorating underlying values, in a way that neatly propagates through values.

### Value
This kind of functionality is important in:
1. Building data-validation pipelines, that can in the end report a set of "found problems".
2. Reporting implicit, possibly surprising, behaviors in libraries. Rather than fail, libraries may choose to allow to perform an operation with e.g. an implicit type coercion, but warn the user about the fact that it was indeed performed.

### Specification
These warnings should be able to decorate any value, in a way similar to dataflow errors. However, they should be completely transparent to the interpreter (i.e. delegate all operations to the decorated value), except for a few select methods (such as `Warnings.get my_value`).

### Acceptance Criteria & Test Cases
The functionality is well designed, tested, and causes no performance regressions when unused.

**Comment by kustosz** [comment] 2022-01-13 12:27
## A warning data type should include:
1. Information regarding the location in code (module, method name, text location) of the warning's origin.
2. An arbitrary value denoting the nature of the warning.

## Creating and modifying warnings:
1. `Warning.attach decorated_value warning_payload` attaches a new warning to `decorated_value`, carrying `warning_payload` as value, populating the code location with this method's call site. If `decorated_value` already carries warnings, the original warnings are preserved and the new one is added as the last one in the logical ordering of warnings.
2. `Warning.get_all my_value` returns a vector of all warnings associated with `my_value`, sorted in the order of warnings being attached.
3. `Warning.set my_value warnings` sets a new list of warnings on `my_value`. Any pre-attached warnings on `my_value` are removed and replaced with `warnings`.

## Semantics with regards to other language functionalities
1. If a value decorated with warnings is used as a method call target (i.e. `this`), or a function in function application, the return value of such call is additionally decorated with these warnings (on top of any warnings resulting from the body of the called function).
2. If a value decorated with warnings is used as an argument to a polyglot call, an atom constructor, or a builtin function, the undecorated value is used instead and the warnings are reattached to the result of such call. If multiple such arguments are used, the result carries all the identically unique warnings, in the order of call arguments.
3. If a value decorated with warnings is used as a scrutinee in a `case` expression, the warnings are attached to the value of the `case` expression.

**Comment by kustosz** [comment] 2022-01-15 11:09
# Additional requirements since last comment

## Creating and modifying warnings:

4. The ordering of warnings should be logically temporal. I.e. warnings attached earlier in a value's life-cycle should be placed later in the warnings list.

## Semantics with regards to other language functionalities

4. Whenever a warning is re-attached to a new value by way of interacting with different language constructs, the code location of such re-attachment should be recorded, such that it is possible construct a sort of dataflow paper-trail.

## IDE handling of warnings

1. The IDE should present a unified view of all warnings reported in the entire graph, with a way to navigate from such warning to the offending node.
2. The IDE should visually differentiate warnings inherent to the current value (i.e. ones that are attached directly to the return value of the current method) and warnings attached to the value by way of interacting with tainted values through different syntax elements.
3. It should be possible to trace the paper trail of a warning in the GUI, i.e. to navigate to the previous "point of interest" (i.e. creation or re-attachment) in a warning's life-cycle, either in the currently viewed graph, or down the execution stack.
4. The ordering of warnings in the IDE view should be temporal w.r.t. the value life-cycle.

## Library handling of warnings

1. There should be a way of rethrowing warnings as errors.
2. All "output"-type functions (e.g. writing to files, database updates) should, by default, panic when passed warning-ridden data. This behavior should be opt-out by an optional argument called `ignore_warnings`.

**Comment by radeusgd** [comment] 2022-01-17 11:06
I wanted to clarify two points related to the design of warning propagation.

#### Unused arguments

To my understanding, if we define the following function:

```
foo a b c =
   if a then 1+b else c
```

and then call it with `foo True x y`, then it will inherit any warnings from `x` but it will ignore any warnings that could have been in `y`, correct? I think this should be clearly described somewhere, as while it makes sense, it may be surprising to the users.

#### Stateful/imperative operations

Since we are sometimes using stateful operations, like `Vector.Builder` for example for efficiency, if I understand correctly, they will not automatically inherit some warnings. For example:

```
builder = Vector.new_builder
nope = foo.each e-> builder.append e
res = builder.to_vector
```

In such a case, if I understand the spec correctly, `res` will not have any warnings even if `foo` had them, right? Because there is no place for it to inherit them - the builder is created in a warning-free way, and any warnings from `foo` are only transferred to `nope` (which has "type" `Nothing + warnings`), but not to the stateful/imperative changes of the underlying vector in the builder.

I would suggest that maybe we should have another operation, something like:
```
Warning.inherit : Any -> Vector Any -> Any
Warning.inherit value dependant_values = ...
```
which would return `value` but decorated with any warnings present in `dependant_values`.

Thus, the code from above could be rephrased as:
```
builder = Vector.new_builder
nope = foo.each e-> builder.append e
res = Warning.inherit builder.to_vector [foo]
```

ensuring that the result inherits the warnings as we'd want.

**Comment by kustosz** [comment] 2022-01-17 23:30
1. Regarding the `unused arguments` points: yes, if an argument is dropped, warnings stop propagating. I don't think that is very important (as in: the broken thing is gone, all is fine), but let's summon @wdanilo 
2. Regarding `Warning.inherit`, I agree, it should exist. I will add such a function when building the library.

**Comment by ekmett** [comment] 2022-01-18 17:03
I think there's a possibility for doing something clever here.

Consider a `warn_once` node that we could place in the truffle syntax tree that is responsible for emitting a warning, and then rewriting itself to its second argument. Then the warning behavior gets a warning to the user but has zero runtime cost after it warms up. e.g. comparing two floating point numbers for equality could trip this. There's some nuance to be had here as you really want the rewrite to be once per source occurence of this node, not however many places it gets copied through the tree, so you'd really be asking for something a little more complicated to parse into, but I think this is the right general space of ideas.

Another case that could be quite useful is a more robust `warn_with_count` that 

a.) prints the warning
b.) allocates a counter for the use site (or more likely uses a global static counter for this error, possibly by source location so we don't need to deal with multiple uses while under function arguments)
c.) rewrites itself into a function that bumps that counter
d.) Either installs an `atexit(3)` style hook to print the final count on the command line, or provides an ID or source location with the warning for use in the IDE, that can be queried to get a running count as the program runs.

Feel free to bikeshed the names, and I'm not sure I've got the right idea for how to expose them in-language, but both would make effective use of Truffle on the backend while giving good warnings.

Zero-cost warnings could be a heck of a selling point.

**Comment by radeusgd** [comment] 2022-01-19 13:19
One additional note regarding `Warning.inherit`: as we will be sometimes reporting stuff as warnings and sometimes as errors, we actually need a way to 'inherit' both of these and usually in the same place (i.e. if we are using `inherit` to indicate a dependency of a result on something, I think everytime we want to inherit both the errors and the warnings that this dependency may introduce).
So a suggestion that `Warning.inherit` should probably not only make sure warnings are inherited, but also if any of the `dependant_values` is an error, the result should probably be an error too. In such scenario this function could be renamed to something like `introduce_dependencies` or similar.

**Comment by radeusgd** [comment] 2022-01-19 15:34
What is the expected behavior of `Warnings.attach decorated_value payload` if one of these two arguments already is a dataflow error?

**Comment by ekmett** [comment] 2022-01-19 16:50
FWIW- it is worth mentioning that the warning behavior I offered is orthogonal to this feature. Rather than tainting values with the set of warnings that fed into their construction (and forcing things onto slow paths) they let us back onto a faster path, but lose the correlation between values and the warnings the users see. Both are pretty cool features for a language to offer, though.

**Comment by ekmett** [comment] 2022-01-19 16:59
Another point in the design space that might be worth considering other than a tainting narrative would be for there to be a notion of 'warning scopes'. Enter into a scope, and now any warnings invoked get added to the set for the current scope. Exit the scope and you get your hand on that Set directly in the language. Current scope is always accessible via this stack discipline. Then something like a table join that needs to compute things would create the warning scope, do the operations, with no tainting causing us onto a slow Object-driven path for every single tainted value, and then you can exit the scope and bolt the information into the table that is the result as an extra field or some such, used to display the warnings to the user in the IDE in the visualization for the table itself, maybe with a set of colored warnings and the like. We get something like localization, in that the taint is tracked, but it is more manual but you retain the fast execution path.

Yet another option is to go further and mix these stories, but just tainting the object that is the result of the scope, so you'd locally stay on the fast path with untainted values in a tainted scope, and then exiting the scope taints the computed result.

**Closed as completed** 2022-04-14 20:46 UTC
